/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PayoffType = IDL.Variant({
	Put: IDL.Null,
	Binary: IDL.Null,
	Call: IDL.Null
});
export const SettlementAsset = IDL.Variant({
	Icp: IDL.Null,
	CkUsdc: IDL.Null
});
export const AddSeriesParams = IDL.Record({
	title: IDL.Text,
	strike: IDL.Opt(IDL.Nat64),
	payoff_type: PayoffType,
	settlement_asset: SettlementAsset,
	underlying: IDL.Text,
	description: IDL.Text,
	expiry: IDL.Nat64,
	oracle_source: IDL.Text
});
export const RegistryError = IDL.Variant({
	DescriptionTooLong: IDL.Null,
	TitleTooLong: IDL.Null,
	SeriesAlreadyExists: IDL.Null
});
export const AddSeriesResult = IDL.Variant({
	Ok: IDL.Text,
	Err: RegistryError
});
export const Series = IDL.Record({
	title: IDL.Text,
	strike: IDL.Opt(IDL.Nat64),
	creator: IDL.Principal,
	payoff_type: PayoffType,
	series_id: IDL.Text,
	settlement_asset: SettlementAsset,
	underlying: IDL.Text,
	description: IDL.Text,
	expiry: IDL.Nat64,
	oracle_source: IDL.Text
});

export const idlService = IDL.Service({
	add_series: IDL.Func([AddSeriesParams], [AddSeriesResult], []),
	get_series: IDL.Func([IDL.Text], [IDL.Opt(Series)], []),
	list_series: IDL.Func([], [IDL.Vec(Series)], ['query'])
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
	const PayoffType = IDL.Variant({
		Put: IDL.Null,
		Binary: IDL.Null,
		Call: IDL.Null
	});
	const SettlementAsset = IDL.Variant({
		Icp: IDL.Null,
		CkUsdc: IDL.Null
	});
	const AddSeriesParams = IDL.Record({
		title: IDL.Text,
		strike: IDL.Opt(IDL.Nat64),
		payoff_type: PayoffType,
		settlement_asset: SettlementAsset,
		underlying: IDL.Text,
		description: IDL.Text,
		expiry: IDL.Nat64,
		oracle_source: IDL.Text
	});
	const RegistryError = IDL.Variant({
		DescriptionTooLong: IDL.Null,
		TitleTooLong: IDL.Null,
		SeriesAlreadyExists: IDL.Null
	});
	const AddSeriesResult = IDL.Variant({
		Ok: IDL.Text,
		Err: RegistryError
	});
	const Series = IDL.Record({
		title: IDL.Text,
		strike: IDL.Opt(IDL.Nat64),
		creator: IDL.Principal,
		payoff_type: PayoffType,
		series_id: IDL.Text,
		settlement_asset: SettlementAsset,
		underlying: IDL.Text,
		description: IDL.Text,
		expiry: IDL.Nat64,
		oracle_source: IDL.Text
	});

	return IDL.Service({
		add_series: IDL.Func([AddSeriesParams], [AddSeriesResult], []),
		get_series: IDL.Func([IDL.Text], [IDL.Opt(Series)], []),
		list_series: IDL.Func([], [IDL.Vec(Series)], ['query'])
	});
};

export const init = ({ IDL }) => {
	return [];
};
