/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';

export interface AddSeriesParams {
	strike: [] | [bigint];
	payoff_type: PayoffType;
	settlement_asset: SettlementAsset;
	underlying: string;
	expiry: bigint;
	oracle_source: string;
}
export type AddSeriesResult = { Ok: string } | { Err: RegistryError };
export type PayoffType = { Put: null } | { Binary: null } | { Call: null };
export type RegistryError = { SeriesAlreadyExists: null };
export interface Series {
	strike: [] | [bigint];
	payoff_type: PayoffType;
	series_id: string;
	settlement_asset: SettlementAsset;
	underlying: string;
	expiry: bigint;
	oracle_source: string;
}
export type SettlementAsset = { Icp: null } | { CkUsdc: null };
export interface _SERVICE {
	/**
	 * Adds a new derivative series to the registry.
	 *
	 * This method generates a canonical [`SeriesId`] for the provided parameters.
	 * If the series already exists, it returns an error.
	 *
	 * # Arguments
	 * * `params` - The defining parameters for the new series.
	 *
	 * # Returns
	 * * [`AddSeriesResult::Ok`] containing the new [`SeriesId`] on success.
	 * * [`AddSeriesResult::Err`] with [`RegistryError::SeriesAlreadyExists`] if the series is already
	 * registered.
	 */
	add_series: ActorMethod<[AddSeriesParams], AddSeriesResult>;
	/**
	 * Retrieves a specific [`Series`] by its [`SeriesId`].
	 *
	 * # Arguments
	 * * `series_id` - The unique identifier of the series to retrieve.
	 *
	 * # Returns
	 * * `Some(Series)` if the series exists in the registry.
	 * * `None` otherwise.
	 */
	get_series: ActorMethod<[string], [] | [Series]>;
	/**
	 * Returns a list of all registered derivative series.
	 */
	list_series: ActorMethod<[], Array<Series>>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
