/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddOracleParams {
	metadata: OracleMetadata;
	authorized_principals: Array<Principal>;
	oracle_id: string;
}
export interface AddSeriesParams {
	title: string;
	strike: [] | [Price];
	payoff_type: PayoffType;
	payout_unit: PayoutUnit;
	expiry_ns: bigint;
	banner_url: [] | [string];
	underlying: string;
	description: Description;
	outcomes: [] | [Array<Outcome>];
	icon_url: [] | [string];
	price_precision: number;
	balance_domain: BalanceDomain;
	oracle_source: string;
}
export type AddSeriesResult = { Ok: string } | { Err: SeriesError };
export type Asset = { Erc20: ErcToken } | { Icrc: Principal } | { NativeEvm: NativeEvmAsset };
export type BalanceDomain = { Playground: null } | { Settlement: null };
export interface DecimalValue {
	decimals: number;
	value: bigint;
}
export interface Description {
	html: [] | [string];
	markdown: [] | [string];
	plain: string;
}
export interface ErcToken {
	decimals: number;
	token_address: string;
	chain_id: bigint;
}
export type FiatUnit = { Chf: null } | { Eur: null } | { Gbp: null } | { Usd: null };
export interface ListSeriesParams {
	strike: [] | [Price];
	creator: [] | [Principal];
	payoff_type: [] | [PayoffType];
	payout_unit: [] | [PayoutUnit];
	pagination: [] | [PaginationParams];
	underlying: [] | [string];
	search_term: [] | [string];
	balance_domain: [] | [BalanceDomain];
	oracle_source: [] | [string];
}
export interface ManageOraclePrincipalsParams {
	add_principals: Array<Principal>;
	remove_principals: Array<Principal>;
	oracle_id: string;
}
export interface NativeEvmAsset {
	decimals: number;
	chain_id: bigint;
}
export type NonMonetaryUnit = { Points: null };
export interface Oracle {
	manager: Principal;
	registered_at_ns: bigint;
	metadata: OracleMetadata;
	authorized_principals: Array<Principal>;
	oracle_id: string;
}
export type OracleError =
	| { UnauthorizedOracleManager: null }
	| { OracleAlreadyExists: null }
	| { OracleNotFound: null };
export interface OracleMetadata {
	name: string;
	description: [] | [Description];
	website: [] | [string];
}
export type OracleResult = { Ok: null } | { Err: OracleError };
export interface Outcome {
	id: string;
	title: string;
	description: [] | [Description];
	icon_url: [] | [string];
}
export interface PaginationParams {
	cursor: [] | [string];
	limit: [] | [bigint];
}
export type PayoffType = { Put: null } | { Binary: null } | { Call: null } | { Categorical: null };
export type PayoutUnit = { Fiat: FiatUnit } | { Asset: Asset } | { NonMonetary: NonMonetaryUnit };
export interface Price {
	timestamp: [] | [bigint];
	oracle_id: [] | [string];
	decimal: DecimalValue;
}
export interface Series {
	title: string;
	strike: [] | [Price];
	creator: Principal;
	payoff_type: PayoffType;
	payout_unit: PayoutUnit;
	expiry_ns: bigint;
	banner_url: [] | [string];
	series_id: string;
	underlying: string;
	description: Description;
	outcomes: [] | [Array<Outcome>];
	created_at_ns: bigint;
	icon_url: [] | [string];
	price_precision: number;
	balance_domain: BalanceDomain;
	oracle_source: string;
}
export type SeriesError =
	| { DescriptionTooLong: null }
	| { TitleTooLong: null }
	| { Unauthorized: null }
	| { UnsupportedPayoutUnit: null }
	| { SeriesAlreadyExists: null };
export interface SeriesPage {
	next_cursor: [] | [string];
	items: Array<Series>;
}
export interface UpdateOracleMetadataParams {
	metadata: OracleMetadata;
	oracle_id: string;
}
export interface _SERVICE {
	/**
	 * Authorizes a list of principals to create new derivative series.
	 *
	 * This method is gated to canister controllers.
	 */
	add_authorized_creators: ActorMethod<[Array<Principal>], undefined>;
	/**
	 * Registers a new price oracle in the registry.
	 */
	add_oracle: ActorMethod<[AddOracleParams], OracleResult>;
	/**
	 * Adds a new derivative series to the registry.
	 *
	 * This method generates a canonical [`SeriesId`] for the provided parameters.
	 * If the series already exists, it returns an error.
	 *
	 * # Arguments
	 * * `params` - The defining parameters for the new series.
	 *
	 * # Returns
	 * * [`AddSeriesResult::Ok`] containing the new [`SeriesId`] on success.
	 * * [`AddSeriesResult::Err`] with [`SeriesError::SeriesAlreadyExists`] if the series is already
	 * registered.
	 */
	add_series: ActorMethod<[AddSeriesParams], AddSeriesResult>;
	/**
	 * Retrieves the details of a specific oracle by its ID.
	 */
	get_oracle: ActorMethod<[string], [] | [Oracle]>;
	/**
	 * Retrieves a specific [`Series`] by its [`SeriesId`].
	 *
	 * # Arguments
	 * * `series_id` - The unique identifier of the series to retrieve.
	 *
	 * # Returns
	 * * `Some(Series)` if the series exists in the registry.
	 * * `None` otherwise.
	 */
	get_series: ActorMethod<[string], [] | [Series]>;
	/**
	 * Checks if a principal is authorized to create derivative series.
	 */
	is_authorized_creator: ActorMethod<[Principal], boolean>;
	/**
	 * Checks if a principal is authorized to push settlement data for a given oracle.
	 */
	is_oracle_authorized: ActorMethod<[string, Principal], boolean>;
	/**
	 * Returns a list of all principals currently authorized to create series.
	 *
	 * This method is gated to canister controllers.
	 */
	list_authorized_creators: ActorMethod<[], Array<Principal>>;
	/**
	 * Returns a paginated page of all registered derivative series.
	 */
	list_series: ActorMethod<[PaginationParams], SeriesPage>;
	/**
	 * Returns a paginated page of registered derivative series, optionally filtered.
	 */
	list_series_with: ActorMethod<[ListSeriesParams], SeriesPage>;
	/**
	 * Adds or removes authorised principals for an oracle.
	 */
	manage_oracle_principals: ActorMethod<[ManageOraclePrincipalsParams], OracleResult>;
	/**
	 * Removes authorization from a list of principals, preventing them from creating new series.
	 *
	 * This method is gated to canister controllers.
	 */
	remove_authorized_creators: ActorMethod<[Array<Principal>], undefined>;
	/**
	 * Updates the metadata of an existing oracle.
	 */
	update_oracle_metadata: ActorMethod<[UpdateOracleMetadataParams], OracleResult>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
