import { USD_DECIMALS, ZERO } from '$lib/constants/app.constants';
import { PORTFOLIO_DEFAULT_DECIMALS } from '$lib/constants/portfolio.constants';
import type { Market } from '$lib/types/market';
import type { Position } from '$lib/types/position';
import { decimalFixedValueToNumber } from '$lib/utils/format.utils';
import { isNullish, nonNullish } from '@dfinity/utils';

/**
 * Returns the settled value of a position on a resolved market, in the
 * position's native `netQty` bigint units. Mirrors the clearing engine's
 * binary / categorical payoff rules: the full `netQty` on the winning
 * outcome, `ZERO` on every other outcome. Returns `undefined` if we don't
 * know which outcome won so the caller can fall back to live probabilities.
 *
 * Uses bigint arithmetic end-to-end — avoid routing position quantities
 * through `Number` here, which would lose precision on positions larger
 * than `Number.MAX_SAFE_INTEGER` (2^53 − 1).
 */
const resolvedPositionValue = ({
	position,
	market
}: {
	position: Position;
	market: Market;
}): bigint | undefined => {
	if (isNullish(market.outcome)) {
		return;
	}

	return position.outcomeId === market.outcome ? position.netQty : ZERO;
};

/**
 * Calculates the current real-value of a user position.
 *
 * For open markets we use live implied probability from the order book.
 * For resolved markets we use the final outcome (full `netQty` if won, zero
 * if lost) so the portfolio reflects the settled value rather than
 * pre-resolution midpoints.
 */
export const calculatePositionValue = ({
	position,
	market
}: {
	position: Position;
	market?: Market;
}): bigint => {
	if (isNullish(market)) {
		return ZERO;
	}

	if (market.status === 'Resolved') {
		const settled = resolvedPositionValue({ position, market });

		if (nonNullish(settled)) {
			return settled;
		}
	}

	const prob =
		market.payoffType === 'Binary'
			? position.outcomeId === 'YES'
				? market.yesProbability
				: market.noProbability
			: 1 / (market.outcomes?.length ?? 1);

	return BigInt(Math.floor(Number(position.netQty) * prob));
};

/**
 * Calculates the absolute numerical profit or loss generated by a user position based on current value vs cost.
 */
export const calculatePositionPnL = ({
	position,
	market
}: {
	position: Position;
	market?: Market;
}): number => {
	if (isNullish(market)) {
		return 0;
	}

	const currentValue = calculatePositionValue({ position, market });

	// lockedCollateral is clearing USD (`USD_DECIMALS`). currentValue uses token decimals.
	const valNum = decimalFixedValueToNumber({
		value: currentValue,
		decimals: market.token.decimals ?? PORTFOLIO_DEFAULT_DECIMALS
	});
	const costNum = decimalFixedValueToNumber({
		value: position.lockedCollateral,
		decimals: USD_DECIMALS
	});

	return valNum - costNum;
};
