import { USD_DECIMALS, ZERO } from '$lib/constants/app.constants';
import { PORTFOLIO_DEFAULT_DECIMALS } from '$lib/constants/portfolio.constants';
import type { Market } from '$lib/types/market';
import type { Position } from '$lib/types/position';
import { decimalFixedValueToNumber } from '$lib/utils/format.utils';
import { isNullish } from '@dfinity/utils';

/**
 * Calculates the current real-value of a user position based on market probability.
 */
export const calculatePositionValue = ({
	position,
	market
}: {
	position: Position;
	market?: Market;
}): bigint => {
	if (isNullish(market)) {
		return ZERO;
	}

	const prob =
		market.payoffType === 'Binary'
			? position.outcomeId === 'YES'
				? market.yesProbability
				: market.noProbability
			: 1 / (market.outcomes?.length ?? 1);

	return BigInt(Math.floor(Number(position.netQty) * prob));
};

/**
 * Calculates the absolute numerical profit or loss generated by a user position based on current value vs cost.
 */
export const calculatePositionPnL = ({
	position,
	market
}: {
	position: Position;
	market?: Market;
}): number => {
	if (isNullish(market)) {
		return 0;
	}

	const currentValue = calculatePositionValue({ position, market });

	// lockedCollateral is clearing USD (`USD_DECIMALS`). currentValue uses token decimals.
	const valNum = decimalFixedValueToNumber({
		value: currentValue,
		decimals: market.token.decimals ?? PORTFOLIO_DEFAULT_DECIMALS
	});
	const costNum = decimalFixedValueToNumber({
		value: position.lockedCollateral,
		decimals: USD_DECIMALS
	});

	return valNum - costNum;
};
