import { USD_DECIMALS, ZERO } from '$lib/constants/app.constants';
import { PORTFOLIO_DEFAULT_DECIMALS } from '$lib/constants/portfolio.constants';
import type { Market } from '$lib/types/market';
import type { Position } from '$lib/types/position';
import { decimalFixedValueToNumber } from '$lib/utils/format.utils';
import { isNullish, nonNullish } from '@dfinity/utils';

/**
 * Returns the settlement multiplier (0..1) for a position on a resolved
 * market. Mirrors the clearing engine's payoff rules:
 *   - Binary / Categorical: 1 on the winning outcome, 0 otherwise.
 *   - Unknown winner (settlement activity without an outcome label): undefined
 *     so callers can fall back to live probabilities.
 */
const resolvedPositionMultiplier = ({
	position,
	market
}: {
	position: Position;
	market: Market;
}): number | undefined => {
	if (isNullish(market.outcome)) {
		return;
	}

	return position.outcomeId === market.outcome ? 1 : 0;
};

/**
 * Calculates the current real-value of a user position.
 *
 * For open markets we use live implied probability from the order book.
 * For resolved markets we use the final outcome (1 if won, 0 if lost) so the
 * portfolio reflects the settled value rather than pre-resolution midpoints.
 */
export const calculatePositionValue = ({
	position,
	market
}: {
	position: Position;
	market?: Market;
}): bigint => {
	if (isNullish(market)) {
		return ZERO;
	}

	if (market.status === 'Resolved') {
		const multiplier = resolvedPositionMultiplier({ position, market });

		if (nonNullish(multiplier)) {
			return BigInt(Math.floor(Number(position.netQty) * multiplier));
		}
	}

	const prob =
		market.payoffType === 'Binary'
			? position.outcomeId === 'YES'
				? market.yesProbability
				: market.noProbability
			: 1 / (market.outcomes?.length ?? 1);

	return BigInt(Math.floor(Number(position.netQty) * prob));
};

/**
 * Calculates the absolute numerical profit or loss generated by a user position based on current value vs cost.
 */
export const calculatePositionPnL = ({
	position,
	market
}: {
	position: Position;
	market?: Market;
}): number => {
	if (isNullish(market)) {
		return 0;
	}

	const currentValue = calculatePositionValue({ position, market });

	// lockedCollateral is clearing USD (`USD_DECIMALS`). currentValue uses token decimals.
	const valNum = decimalFixedValueToNumber({
		value: currentValue,
		decimals: market.token.decimals ?? PORTFOLIO_DEFAULT_DECIMALS
	});
	const costNum = decimalFixedValueToNumber({
		value: position.lockedCollateral,
		decimals: USD_DECIMALS
	});

	return valNum - costNum;
};
