/**
 * Roman/Latin handle pool — used to seed the onboarding handle
 * picker (Beat 2). The register matches the brand's Veni · Vidi ·
 * Vici framing: classical names (augustus, livia, seneca…), oracular
 * and augury terms (augur, oracle, cassandra, sibyl…), and short
 * Latin nouns (vesta, tactus, fortuna…).
 *
 * Every entry is lowercase ASCII, 3–16 chars, and matches the
 * onboarding handle validator (`^[a-z0-9._-]+$`) without filtering.
 *
 * The picker samples a small batch from this list per draw and
 * pre-filters each through the satellite availability query, so the
 * pool stays a *source* of suggestions rather than a fixed display
 * grid. Bundled inline (not fetched at runtime) so the picker works
 * offline. Frozen so accidental mutation is caught immediately.
 */
export const HANDLE_POOL: readonly string[] = Object.freeze([
	// Augury & oracle register
	'augur',
	'oracle',
	'cassandra',
	'sibyl',
	'omen',
	'auspex',
	'haruspex',
	'vates',
	'pythia',
	'delphi',
	'portent',
	'augury',
	'prophet',
	'seer',
	// Classical names
	'augustus',
	'tiberius',
	'livia',
	'seneca',
	'cato',
	'flavia',
	'octavia',
	'lucretia',
	'nero',
	'horatius',
	'plinius',
	'cicero',
	'antonia',
	'aurelia',
	'cornelia',
	'julia',
	'marcus',
	'aurelius',
	'cassius',
	'brutus',
	'cassia',
	'drusus',
	'galba',
	'gracchus',
	'hadrian',
	'sulla',
	'maximus',
	'valeria',
	'lucius',
	'gaius',
	'tullia',
	'claudia',
	'agrippa',
	'crassus',
	'pompeia',
	'remus',
	'romulus',
	'scipio',
	'tacitus',
	'varro',
	'vergil',
	'ovid',
	// Latin nouns & virtues
	'tactus',
	'vesta',
	'fortuna',
	'victrix',
	'laurel',
	'aquila',
	'legio',
	'consul',
	'senator',
	'forum',
	'tribune',
	'augusta',
	'imperium',
	'gloria',
	'virtus',
	'fides',
	'pax',
	'veritas',
	'lumen',
	'aurora',
	'nova',
	'astra',
	'caelum',
	'sol',
	'luna',
	'corvus',
	'lupus',
	'ursa',
	'draco',
	'leo',
	'taurus',
	'orion',
	'vega',
	'sirius',
	'titan',
	'atlas',
	'janus',
	'juno',
	'minerva',
	'mars',
	'mercury',
	'apollo',
	'diana',
	'ceres',
	'flora',
	'fortis',
	'sapiens',
	'audax',
	'celer',
	'magnus',
	'primus',
	'secundus',
	'tertius',
	'quintus',
	'sextus',
	'decimus',
	'maxima',
	'minima',
	'aurea',
	'argentum',
	'ferrum',
	'marmor',
	'columna',
	'arcus',
	'gladius',
	'scutum',
	'pilum',
	'hasta',
	'corona',
	'sigil',
	'castrum',
	'limes',
	'vexillum',
	'cohors',
	'centurio',
	'praetor',
	'quaestor',
	'edict',
	'decree',
	'novus',
	'verus',
	'fidelis',
	'invictus'
]);
