import { isNullish } from '@dfinity/utils';

/**
 * Temporary hardcoded World-Cup release schedule.
 *
 * Maps each release ("Show") date to the World-Cup questions that become
 * visible on that day. A market unlocks at **00:00 UTC of its Show Date**
 * and stays visible from then on; before that instant it is withheld from
 * every feed surface (Flow deck, Markets board).
 *
 * Markets are matched to this calendar by their question text — see
 * {@link normalizeWcQuestion} for the normalization contract both sides go
 * through. A World-Cup market whose question is **absent** from this table
 * is treated as not-yet-curated and stays hidden entirely (no release date)
 * until it is either added here or the schedule is retired.
 *
 * This is a deliberately temporary, hand-editable layer: to move a market's
 * release, cut its question from one date array and paste it under another;
 * to reveal a withheld market, add its exact question under a date. The
 * consuming logic lives in `$lib/utils/wc-schedule.utils`.
 */

/**
 * Release calendar: ISO `YYYY-MM-DD` Show Date -> the exact question text of
 * every World-Cup market that unlocks at 00:00 UTC on that date.
 */
export const WC_MARKET_SCHEDULE: Record<string, readonly string[]> = {
	'2026-06-10': [
		'Will Algeria win Group J?',
		'Will Argentina finish above Austria in Group J?',
		'Will Argentina win Group J?',
		'Will Australia vs Türkiye end in a draw?',
		'Will Austria win Group J?',
		'Will Bosnia and Herzegovina beat Canada?',
		'Will Brazil finish above Morocco in Group C?',
		'Will Brazil score 2 or more goals against Morocco?',
		'Will Brazil vs Morocco end in a draw?',
		'Will Canada reach the Round of 32?',
		'Will Canada score 2 or more goals against Bosnia and Herzegovina?',
		'Will Czechia beat Korea Republic?',
		'Will Czechia reach the Round of 32?',
		'Will England finish above Croatia in Group L?',
		'Will Haiti vs Scotland end in a draw?',
		'Will Korea Republic beat Czechia?',
		'Will Korea Republic keep a clean sheet against Czechia?',
		'Will Korea Republic reach the Round of 32?',
		'Will Korea Republic vs Czechia end in a draw?',
		'Will Mexico (vs South Africa), the USA (vs Paraguay) and Canada (vs Bosnia and Herzegovina) all win their opening matches?',
		'Will Mexico beat South Africa?',
		'Will Mexico keep a clean sheet against South Africa?',
		'Will Mexico reach the Round of 32?',
		'Will Mexico vs South Africa end in a draw?',
		'Will New Zealand vs Belgium end in a draw?',
		'Will Paraguay beat the United States?',
		'Will Portugal finish above Colombia in Group K?',
		'Will Qatar vs Switzerland end in a draw?',
		'Will Scotland keep a clean sheet against Haiti?',
		'Will South Africa beat Mexico?',
		'Will South Africa reach the Round of 32?',
		'Will Spain finish above Uruguay in Group H?',
		'Will Switzerland reach the Round of 32?',
		'Will a World Cup debutant reach the Round of 32?',
		'Will a goal be scored in the first half of Mexico vs South Africa?',
		'Will a host nation top its group?',
		'Will a penalty be awarded in Mexico vs South Africa?',
		'Will a penalty be awarded in the United States vs Paraguay?',
		'Will any group be decided by drawing of lots or fair-play points?',
		'Will any player receive a red card in Canada vs Bosnia and Herzegovina?',
		'Will any player receive a red card in Korea Republic vs Czechia?',
		'Will both teams score in Canada vs Bosnia and Herzegovina?',
		'Will both teams score in Korea Republic vs Czechia?',
		'Will both teams score in Mexico vs South Africa?',
		'Will both teams score in the United States vs Paraguay?',
		'Will the United States keep a clean sheet against Paraguay?',
		'Will the opening goal come inside the first 15 minutes of Korea Republic vs Czechia?',
		'Will the opening goal come inside the first 15 minutes of Qatar vs Switzerland?',
		'Will there be 3 or more goals in Australia vs Türkiye?',
		'Will there be 3 or more goals in Mexico vs South Africa?',
		'Will there be 4 or more goals in Korea Republic vs Czechia?',
		// Tournament-long outright / novelty / progression markets — bettable from
		// the opening day, so revealed with the first matchday set rather than tied
		// to a single fixture.
		'Who will win the 2026 FIFA World Cup?',
		'Will a coach get sent to the stands?',
		'Will a commentator break down in tears during the final?',
		'Will a host nation reach the final?',
		'Will a nation win the World Cup for the first time?',
		'Will a non-European, non-South-American nation reach the final?',
		'Will a pitch invader interrupt a knockout match?',
		'Will a player do "the dance" celebration?',
		'Will a player propose on the pitch?',
		'Will a pre-tournament top-five favorite exit in the Round of 32?',
		'Will a quarterfinal be decided by a shootout?',
		'Will a Round of 32 tie be decided on penalties?',
		'Will a South American nation reach the semifinals?',
		'Will a team win a Round of 32 tie after going two goals down?',
		'Will all four semifinalists come from the top eight seeds?',
		'Will an Asian nation reach the knockout rounds?',
		'Will an unseeded nation reach the semifinals?',
		'Will Argentina defend their World Cup title?',
		'Will Argentina reach the quarterfinals?',
		'Will at least one host nation reach the quarterfinals?',
		'Will both semifinals be decided inside 90 minutes?',
		'Will Brazil reach the final?',
		'Will Brazil reach the quarterfinals?',
		'Will Brazil win the 2026 World Cup?',
		'Will England reach the quarterfinals?',
		'Will France reach the quarterfinals?',
		'Will France win the 2026 World Cup?',
		'Will Mbappé win the Golden Boot?',
		'Will Mexico reach the Round of 16?',
		'Will Spain reach the quarterfinals?',
		'Will Spain win the 2026 World Cup?',
		'Will the Best Young Player be European?',
		'Will the final be decided on penalties?',
		'Will the final be Europe vs. South America?',
		'Will the final have over 3 goals?',
		'Will the Golden Ball go to a forward?',
		'Will the official mascot become a viral meme?',
		'Will the third-place playoff have three or more goals?',
		'Will the tournament top scorer reach six or more goals?',
		'Will the trophy be dropped during the ceremony?',
		'Will the USA reach the quarterfinals on home soil?',
		'Will the USA reach the Round of 16?',
		'Will there be a goal in the first half of the final?',
		'Will three or more Round-of-16 ties go to extra time?',
		"Will VAR overturn the final's first goal?"
	],
	'2026-06-11': [
		'Will Australia beat Türkiye?',
		'Will Bosnia and Herzegovina reach the Round of 32?',
		'Will Brazil reach the Round of 32?',
		'Will Canada beat Bosnia and Herzegovina?',
		'Will Canada vs Bosnia and Herzegovina end in a draw?',
		"Will Casemiro be booked in Brazil's opening match vs Morocco?",
		"Will Christian Pulisic score in the United States' opening match vs Paraguay?",
		'Will Ecuador score 2 or more goals against Ivory Coast?',
		'Will France finish above Senegal in Group I?',
		'Will Germany finish above Ecuador in Group E?',
		'Will Germany vs Curaçao end in a draw?',
		'Will Haiti beat Scotland?',
		'Will Haiti reach the Round of 32?',
		'Will Ivory Coast vs Ecuador end in a draw?',
		'Will Morocco beat Brazil?',
		'Will Morocco reach the Round of 32?',
		'Will Panama win Group L?',
		'Will Qatar beat Switzerland?',
		'Will Qatar reach the Round of 32?',
		'Will Scotland reach the Round of 32?',
		'Will Sweden vs Tunisia end in a draw?',
		'Will Switzerland keep a clean sheet against Qatar?',
		'Will a penalty be awarded in Australia vs Türkiye?',
		'Will a penalty be awarded in Canada vs Bosnia and Herzegovina?',
		'Will a penalty be awarded in Haiti vs Scotland?',
		'Will all three host nations reach the Round of 32?',
		'Will any player receive a red card in Brazil vs Morocco?',
		'Will any player receive a red card in Qatar vs Switzerland?',
		'Will both teams score in Australia vs Türkiye?',
		'Will the Netherlands finish above Japan in Group F?',
		'Will the Netherlands keep a clean sheet against Japan?',
		'Will the Netherlands vs Japan end in a draw?',
		'Will the United States beat Paraguay?',
		'Will the United States vs Paraguay end in a draw?',
		'Will the opening goal come inside the first 15 minutes of Sweden vs Tunisia?',
		'Will the opening goal come inside the first 15 minutes of the United States vs Paraguay?',
		'Will there be 3 or more goals in Brazil vs Morocco?',
		'Will there be 3 or more goals in Canada vs Bosnia and Herzegovina?',
		'Will there be 3 or more goals in Germany vs Curaçao?',
		'Will there be 3 or more goals in Haiti vs Scotland?',
		'Will there be 3 or more goals in the United States vs Paraguay?'
	],
	'2026-06-12': [
		'Will Australia reach the Round of 32?',
		'Will Belgium score 2 or more goals against Egypt?',
		'Will Belgium vs Egypt end in a draw?',
		'Will Brazil beat Morocco?',
		'Will Curaçao beat Germany?',
		'Will Ecuador reach the Round of 32?',
		"Will Florian Wirtz register an assist in Germany's opening match vs Curaçao?",
		'Will Germany keep a clean sheet against Curaçao?',
		'Will Germany reach the Round of 32?',
		"Will Granit Xhaka be booked in Switzerland's opening match vs Qatar?",
		'Will Iran vs New Zealand end in a draw?',
		'Will Ivory Coast beat Ecuador?',
		'Will Japan beat the Netherlands?',
		'Will Paraguay reach the Round of 32?',
		"Will Pedri register an assist in Spain's opening match vs Cape Verde?",
		'Will Saudi Arabia vs Uruguay end in a draw?',
		'Will Scotland beat Haiti?',
		'Will Spain vs Cape Verde end in a draw?',
		'Will Switzerland beat Qatar?',
		'Will Tunisia beat Sweden?',
		'Will Türkiye beat Australia?',
		'Will Türkiye keep a clean sheet against Australia?',
		'Will Türkiye reach the Round of 32?',
		'Will Uruguay keep a clean sheet against Saudi Arabia?',
		"Will Vinícius Júnior score in Brazil's opening match vs Morocco?",
		"Will Wataru Endo be booked in Japan's opening match vs the Netherlands?",
		'Will a goal be scored in the first half of Australia vs Türkiye?',
		'Will a penalty be awarded in Brazil vs Morocco?',
		'Will a penalty be awarded in Germany vs Curaçao?',
		'Will a penalty be awarded in Sweden vs Tunisia?',
		'Will any player receive a red card in Ivory Coast vs Ecuador?',
		'Will any player receive a red card in the Netherlands vs Japan?',
		'Will both teams score in Brazil vs Morocco?',
		'Will both teams score in Haiti vs Scotland?',
		'Will both teams score in Qatar vs Switzerland?',
		'Will the United States reach the Round of 32?',
		'Will the opening goal come inside the first 15 minutes of Haiti vs Scotland?',
		'Will the opening goal come inside the first 15 minutes of Spain vs Cape Verde?',
		'Will the opening goal come inside the first 15 minutes of the Netherlands vs Japan?',
		'Will there be 3 or more goals in Iran vs New Zealand?',
		'Will there be 3 or more goals in Ivory Coast vs Ecuador?',
		'Will there be 3 or more goals in Sweden vs Tunisia?',
		'Will there be 4 or more goals in Qatar vs Switzerland?'
	],
	'2026-06-13': [
		'Will Argentina vs Algeria end in a draw?',
		'Will Austria vs Jordan end in a draw?',
		'Will Cape Verde beat Spain?',
		'Will Curaçao reach the Round of 32?',
		'Will Ecuador beat Ivory Coast?',
		'Will Egypt beat Belgium?',
		'Will France vs Senegal end in a draw?',
		'Will Germany beat Curaçao?',
		'Will Iraq vs Norway end in a draw?',
		'Will Ivory Coast reach the Round of 32?',
		'Will Japan reach the Round of 32?',
		"Will Kai Havertz score in Germany's opening match vs Curaçao?",
		'Will New Zealand beat Iran?',
		"Will Nicolás Otamendi be booked in Argentina's opening match vs Algeria?",
		'Will Norway score 2 or more goals against Iraq?',
		"Will Pervis Estupiñán be booked in Ecuador's opening match vs Ivory Coast?",
		"Will Rodri be booked in Spain's opening match vs Cape Verde?",
		'Will Saudi Arabia beat Uruguay?',
		'Will Sweden beat Tunisia?',
		'Will Sweden keep a clean sheet against Tunisia?',
		'Will Sweden reach the Round of 32?',
		"Will Takefusa Kubo score in Japan's opening match vs the Netherlands?",
		'Will Tunisia reach the Round of 32?',
		"Will Viktor Gyökeres score in Sweden's opening match vs Tunisia?",
		'Will a goal be scored in the first half of Germany vs Curaçao?',
		'Will a penalty be awarded in Iran vs New Zealand?',
		'Will a penalty be awarded in Ivory Coast vs Ecuador?',
		'Will a penalty be awarded in Saudi Arabia vs Uruguay?',
		'Will any player receive a red card in Belgium vs Egypt?',
		'Will any player receive a red card in Spain vs Cape Verde?',
		'Will both teams score in Argentina vs Algeria?',
		'Will both teams score in Germany vs Curaçao?',
		'Will both teams score in Iran vs New Zealand?',
		'Will both teams score in Ivory Coast vs Ecuador?',
		'Will both teams score in Saudi Arabia vs Uruguay?',
		'Will both teams score in Spain vs Cape Verde?',
		'Will both teams score in Sweden vs Tunisia?',
		'Will both teams score in the Netherlands vs Japan?',
		'Will the Netherlands beat Japan?',
		'Will the Netherlands reach the Round of 32?',
		'Will the opening goal come inside the first 15 minutes of France vs Senegal?',
		'Will there be 3 or more goals in Austria vs Jordan?',
		'Will there be 3 or more goals in Belgium vs Egypt?',
		'Will there be 4 or more goals in the Netherlands vs Japan?'
	],
	'2026-06-14': [
		'Will Algeria beat Argentina?',
		'Will Argentina keep a clean sheet against Algeria?',
		'Will Belgium beat Egypt?',
		'Will Belgium reach the Round of 32?',
		'Will Colombia keep a clean sheet against Uzbekistan?',
		"Will Declan Rice be booked in England's opening match vs Croatia?",
		'Will Egypt reach the Round of 32?',
		'Will England keep a clean sheet against Croatia?',
		'Will England vs Croatia end in a draw?',
		'Will France keep a clean sheet against Senegal?',
		'Will Ghana score 2 or more goals against Panama?',
		'Will Ghana vs Panama end in a draw?',
		'Will Iran beat New Zealand?',
		'Will Iran keep a clean sheet against New Zealand?',
		'Will Iran reach the Round of 32?',
		'Will Iraq beat Norway?',
		'Will Jordan beat Austria?',
		"Will Julián Álvarez score in Argentina's opening match vs Algeria?",
		"Will Kevin De Bruyne register an assist in Belgium's opening match vs Egypt?",
		"Will Lamine Yamal score in Spain's opening match vs Cape Verde?",
		"Will Martin Ødegaard register an assist in Norway's opening match vs Iraq?",
		"Will Mohamed Salah score in Egypt's opening match vs Belgium?",
		'Will New Zealand reach the Round of 32?',
		'Will Portugal keep a clean sheet against DR Congo?',
		'Will Portugal vs DR Congo end in a draw?',
		'Will Senegal beat France?',
		'Will Spain beat Cape Verde?',
		'Will Spain keep a clean sheet against Cape Verde?',
		'Will Spain reach the Round of 32?',
		'Will Uruguay beat Saudi Arabia?',
		'Will Uruguay reach the Round of 32?',
		'Will Uzbekistan vs Colombia end in a draw?',
		'Will a goal be scored in the first half of Iran vs New Zealand?',
		'Will a penalty be awarded in Argentina vs Algeria?',
		'Will a penalty be awarded in Austria vs Jordan?',
		'Will a penalty be awarded in Belgium vs Egypt?',
		'Will any player receive a red card in France vs Senegal?',
		'Will any player receive a red card in Iraq vs Norway?',
		'Will both teams score in Austria vs Jordan?',
		'Will both teams score in Belgium vs Egypt?',
		'Will the opening goal come inside the first 15 minutes of Saudi Arabia vs Uruguay?',
		'Will there be 3 or more goals in Iraq vs Norway?',
		'Will there be 3 or more goals in Saudi Arabia vs Uruguay?',
		'Will there be 4 or more goals in Spain vs Cape Verde?'
	],
	'2026-06-15': [
		'Will Argentina beat Algeria?',
		'Will Austria beat Jordan?',
		'Will Austria keep a clean sheet against Jordan?',
		"Will Bruno Fernandes register an assist in Portugal's opening match vs DR Congo?",
		'Will Canada score 2 or more goals against Qatar?',
		'Will Canada vs Qatar end in a draw?',
		'Will Cape Verde reach the Round of 32?',
		'Will Croatia beat England?',
		'Will Czechia vs South Africa end in a draw?',
		'Will DR Congo beat Portugal?',
		"Will Erling Haaland score in Norway's opening match vs Iraq?",
		'Will France beat Senegal?',
		'Will France reach the Round of 32?',
		'Will Iraq reach the Round of 32?',
		"Will James Rodríguez register an assist in Colombia's opening match vs Uzbekistan?",
		"Will Jude Bellingham score in England's opening match vs Croatia?",
		"Will Kylian Mbappé score in France's opening match vs Senegal?",
		"Will Lionel Messi register an assist in Argentina's opening match vs Algeria?",
		"Will Lionel Messi score in Argentina's opening match vs Algeria?",
		'Will Mexico keep a clean sheet against Korea Republic?',
		'Will Mexico vs Korea Republic end in a draw?',
		'Will Norway beat Iraq?',
		'Will Norway reach the Round of 32?',
		'Will Panama beat Ghana?',
		"Will Sadio Mané score in Senegal's opening match vs France?",
		'Will Saudi Arabia reach the Round of 32?',
		'Will Senegal reach the Round of 32?',
		'Will Switzerland keep a clean sheet against Bosnia and Herzegovina?',
		'Will Switzerland vs Bosnia and Herzegovina end in a draw?',
		'Will Uzbekistan beat Colombia?',
		'Will a goal be scored in the first half of Austria vs Jordan?',
		'Will a penalty be awarded in Iraq vs Norway?',
		'Will a penalty be awarded in Portugal vs DR Congo?',
		'Will a penalty be awarded in Uzbekistan vs Colombia?',
		'Will any player receive a red card in England vs Croatia?',
		'Will any player receive a red card in Ghana vs Panama?',
		'Will both teams score in France vs Senegal?',
		'Will both teams score in Iraq vs Norway?',
		'Will both teams score in Uzbekistan vs Colombia?',
		'Will the opening goal come inside the first 15 minutes of Argentina vs Algeria?',
		'Will the opening goal come inside the first 15 minutes of England vs Croatia?',
		'Will there be 3 or more goals in Argentina vs Algeria?',
		'Will there be 3 or more goals in Czechia vs South Africa?',
		'Will there be 3 or more goals in Ghana vs Panama?',
		'Will there be 3 or more goals in Portugal vs DR Congo?',
		'Will there be 4 or more goals in France vs Senegal?'
	],
	'2026-06-16': [
		'Will Algeria reach the Round of 32?',
		'Will Argentina reach the Round of 32?',
		'Will Austria reach the Round of 32?',
		'Will Bosnia and Herzegovina beat Switzerland?',
		'Will Brazil vs Haiti end in a draw?',
		'Will Colombia beat Uzbekistan?',
		'Will Colombia reach the Round of 32?',
		"Will Cristiano Ronaldo score in Portugal's opening match vs DR Congo?",
		'Will England beat Croatia?',
		'Will Ghana beat Panama?',
		"Will Harry Kane score in England's opening match vs Croatia?",
		'Will Jordan reach the Round of 32?',
		"Will Jude Bellingham register an assist in England's opening match vs Croatia?",
		'Will Korea Republic beat Mexico?',
		"Will Luis Díaz score in Colombia's opening match vs Uzbekistan?",
		"Will Luka Modrić be booked in Croatia's opening match vs England?",
		'Will Morocco score 2 or more goals against Scotland?',
		'Will Portugal beat DR Congo?',
		'Will Portugal reach the Round of 32?',
		'Will Qatar beat Canada?',
		'Will Scotland vs Morocco end in a draw?',
		'Will South Africa beat Czechia?',
		'Will Türkiye vs Paraguay end in a draw?',
		'Will a goal be scored in the first half of Portugal vs DR Congo?',
		'Will a penalty be awarded in Czechia vs South Africa?',
		'Will a penalty be awarded in Ghana vs Panama?',
		'Will a penalty be awarded in Mexico vs Korea Republic?',
		'Will any player receive a red card in Canada vs Qatar?',
		'Will any player receive a red card in Switzerland vs Bosnia and Herzegovina?',
		'Will both teams score in Czechia vs South Africa?',
		'Will both teams score in England vs Croatia?',
		'Will both teams score in Ghana vs Panama?',
		'Will both teams score in Portugal vs DR Congo?',
		'Will the United States vs Australia end in a draw?',
		'Will the opening goal come inside the first 15 minutes of Brazil vs Haiti?',
		'Will the opening goal come inside the first 15 minutes of Switzerland vs Bosnia and Herzegovina?',
		'Will the opening goal come inside the first 15 minutes of Uzbekistan vs Colombia?',
		'Will the opening goal come inside the first 15 minutes of the United States vs Australia?',
		'Will there be 3 or more goals in Canada vs Qatar?',
		'Will there be 3 or more goals in Mexico vs Korea Republic?',
		'Will there be 3 or more goals in Türkiye vs Paraguay?',
		'Will there be 3 or more goals in Uzbekistan vs Colombia?',
		'Will there be 4 or more goals in England vs Croatia?'
	],
	'2026-06-17': [
		'Will Australia beat the United States?',
		'Will Canada beat Qatar?',
		'Will Croatia reach the Round of 32?',
		'Will Czechia beat South Africa?',
		'Will Czechia keep a clean sheet against South Africa?',
		'Will DR Congo reach the Round of 32?',
		'Will Ecuador keep a clean sheet against Curaçao?',
		'Will Ecuador vs Curaçao end in a draw?',
		'Will England reach the Round of 32?',
		'Will Germany vs Ivory Coast end in a draw?',
		'Will Ghana reach the Round of 32?',
		'Will Haiti beat Brazil?',
		'Will Mexico beat Korea Republic?',
		'Will Panama reach the Round of 32?',
		'Will Paraguay beat Türkiye?',
		'Will Saudi Arabia win Group H?',
		'Will Scotland beat Morocco?',
		'Will Switzerland beat Bosnia and Herzegovina?',
		'Will Tunisia vs Japan end in a draw?',
		'Will Uzbekistan reach the Round of 32?',
		'Will a goal be scored in the first half of Czechia vs South Africa?',
		'Will a penalty be awarded in Brazil vs Haiti?',
		'Will a penalty be awarded in Canada vs Qatar?',
		'Will a penalty be awarded in Türkiye vs Paraguay?',
		'Will any player receive a red card in Scotland vs Morocco?',
		'Will any player receive a red card in the United States vs Australia?',
		'Will both teams score in Canada vs Qatar?',
		'Will both teams score in Mexico vs Korea Republic?',
		'Will both teams score in Switzerland vs Bosnia and Herzegovina?',
		'Will both teams score in Türkiye vs Paraguay?',
		'Will the Netherlands vs Sweden end in a draw?',
		'Will the United States keep a clean sheet against Australia?',
		'Will the opening goal come inside the first 15 minutes of Mexico vs Korea Republic?',
		'Will the opening goal come inside the first 15 minutes of the Netherlands vs Sweden?',
		'Will there be 3 or more goals in Brazil vs Haiti?',
		'Will there be 3 or more goals in Germany vs Ivory Coast?',
		'Will there be 3 or more goals in Scotland vs Morocco?',
		'Will there be 3 or more goals in Tunisia vs Japan?',
		'Will there be 4 or more goals in Switzerland vs Bosnia and Herzegovina?'
	],
	'2026-06-18': [
		'Will Belgium vs Iran end in a draw?',
		'Will Brazil beat Haiti?',
		'Will Brazil keep a clean sheet against Haiti?',
		'Will Canada win Group B?',
		'Will Curaçao beat Ecuador?',
		'Will Czechia win Group A?',
		'Will Egypt keep a clean sheet against New Zealand?',
		'Will Ivory Coast beat Germany?',
		'Will Korea Republic win Group A?',
		'Will Mexico win Group A?',
		'Will Morocco beat Scotland?',
		'Will New Zealand vs Egypt end in a draw?',
		'Will South Africa win Group A?',
		'Will Spain vs Saudi Arabia end in a draw?',
		'Will Sweden beat the Netherlands?',
		'Will Switzerland win Group B?',
		'Will Tunisia beat Japan?',
		'Will Türkiye beat Paraguay?',
		'Will Türkiye keep a clean sheet against Paraguay?',
		'Will Uruguay vs Cape Verde end in a draw?',
		'Will a goal be scored in the first half of Türkiye vs Paraguay?',
		'Will a penalty be awarded in Ecuador vs Curaçao?',
		'Will a penalty be awarded in Scotland vs Morocco?',
		'Will a penalty be awarded in Tunisia vs Japan?',
		'Will any player receive a red card in Germany vs Ivory Coast?',
		'Will any player receive a red card in the Netherlands vs Sweden?',
		'Will both teams score in Brazil vs Haiti?',
		'Will both teams score in Germany vs Ivory Coast?',
		'Will both teams score in Scotland vs Morocco?',
		'Will both teams score in Tunisia vs Japan?',
		'Will both teams score in Uruguay vs Cape Verde?',
		'Will both teams score in the United States vs Australia?',
		'Will the Netherlands keep a clean sheet against Sweden?',
		'Will the United States beat Australia?',
		'Will the opening goal come inside the first 15 minutes of Belgium vs Iran?',
		'Will there be 3 or more goals in Ecuador vs Curaçao?',
		'Will there be 3 or more goals in Spain vs Saudi Arabia?',
		'Will there be 4 or more goals in the United States vs Australia?'
	],
	'2026-06-19': [
		'Will Argentina keep a clean sheet against Austria?',
		'Will Argentina vs Austria end in a draw?',
		'Will Belgium keep a clean sheet against Iran?',
		'Will Bosnia and Herzegovina win Group B?',
		'Will Brazil win Group C?',
		'Will Cape Verde beat Uruguay?',
		'Will Ecuador beat Curaçao?',
		'Will France vs Iraq end in a draw?',
		'Will France win Group I?',
		'Will Germany beat Ivory Coast?',
		'Will Germany score 2 or more goals against Ivory Coast?',
		'Will Haiti win Group C?',
		'Will Iran beat Belgium?',
		'Will Japan beat Tunisia?',
		'Will Japan keep a clean sheet against Tunisia?',
		'Will Jordan vs Algeria end in a draw?',
		'Will Morocco win Group C?',
		'Will New Zealand beat Egypt?',
		'Will Norway vs Senegal end in a draw?',
		'Will Qatar win Group B?',
		'Will Saudi Arabia beat Spain?',
		'Will Scotland win Group C?',
		'Will Senegal score 2 or more goals against Norway?',
		'Will Spain keep a clean sheet against Saudi Arabia?',
		'Will a goal be scored in the first half of Tunisia vs Japan?',
		'Will a penalty be awarded in Germany vs Ivory Coast?',
		'Will a penalty be awarded in New Zealand vs Egypt?',
		'Will a penalty be awarded in Spain vs Saudi Arabia?',
		'Will any player receive a red card in Belgium vs Iran?',
		'Will any player receive a red card in Uruguay vs Cape Verde?',
		'Will both teams score in Ecuador vs Curaçao?',
		'Will both teams score in the Netherlands vs Sweden?',
		'Will the Netherlands beat Sweden?',
		'Will the opening goal come inside the first 15 minutes of Ecuador vs Curaçao?',
		'Will the opening goal come inside the first 15 minutes of France vs Iraq?',
		'Will the opening goal come inside the first 15 minutes of Jordan vs Algeria?',
		'Will there be 3 or more goals in New Zealand vs Egypt?',
		'Will there be 3 or more goals in Uruguay vs Cape Verde?',
		'Will there be 4 or more goals in the Netherlands vs Sweden?'
	],
	'2026-06-20': [
		'Will Australia win Group D?',
		'Will Austria beat Argentina?',
		'Will Belgium beat Iran?',
		'Will Colombia keep a clean sheet against DR Congo?',
		'Will Colombia vs DR Congo end in a draw?',
		'Will Ecuador win Group E?',
		'Will Egypt beat New Zealand?',
		'Will England vs Ghana end in a draw?',
		'Will Germany win Group E?',
		'Will Iraq beat France?',
		'Will Jordan beat Algeria?',
		'Will Norway beat Senegal?',
		'Will Panama vs Croatia end in a draw?',
		'Will Paraguay win Group D?',
		'Will Portugal keep a clean sheet against Uzbekistan?',
		'Will Portugal vs Uzbekistan end in a draw?',
		'Will Spain beat Saudi Arabia?',
		'Will Türkiye win Group D?',
		'Will Uruguay beat Cape Verde?',
		'Will Uruguay score 2 or more goals against Cape Verde?',
		'Will a goal be scored in the first half of Spain vs Saudi Arabia?',
		'Will a penalty be awarded in Argentina vs Austria?',
		'Will a penalty be awarded in Jordan vs Algeria?',
		'Will a penalty be awarded in Uruguay vs Cape Verde?',
		'Will any player receive a red card in France vs Iraq?',
		'Will any player receive a red card in Norway vs Senegal?',
		'Will both teams score in Belgium vs Iran?',
		'Will both teams score in France vs Iraq?',
		'Will both teams score in New Zealand vs Egypt?',
		'Will both teams score in Panama vs Croatia?',
		'Will both teams score in Spain vs Saudi Arabia?',
		'Will the United States win Group D?',
		'Will the opening goal come inside the first 15 minutes of England vs Ghana?',
		'Will the opening goal come inside the first 15 minutes of New Zealand vs Egypt?',
		'Will there be 3 or more goals in Argentina vs Austria?',
		'Will there be 3 or more goals in Jordan vs Algeria?',
		'Will there be 3 or more goals in Norway vs Senegal?',
		'Will there be 4 or more goals in Belgium vs Iran?'
	],
	'2026-06-21': [
		'Will Algeria beat Jordan?',
		'Will Algeria keep a clean sheet against Jordan?',
		'Will Argentina beat Austria?',
		'Will Bosnia and Herzegovina keep a clean sheet against Qatar?',
		'Will Bosnia and Herzegovina vs Qatar end in a draw?',
		'Will Curaçao win Group E?',
		'Will Czechia vs Mexico end in a draw?',
		'Will DR Congo beat Colombia?',
		'Will France beat Iraq?',
		'Will France keep a clean sheet against Iraq?',
		'Will Ghana beat England?',
		'Will Iraq win Group I?',
		'Will Ivory Coast win Group E?',
		'Will Japan win Group F?',
		'Will Korea Republic keep a clean sheet against South Africa?',
		'Will Morocco vs Haiti end in a draw?',
		'Will Norway win Group I?',
		'Will Panama beat Croatia?',
		'Will Scotland vs Brazil end in a draw?',
		'Will Senegal beat Norway?',
		'Will Senegal win Group I?',
		'Will South Africa vs Korea Republic end in a draw?',
		'Will Sweden win Group F?',
		'Will Switzerland vs Canada end in a draw?',
		'Will Tunisia win Group F?',
		'Will Uzbekistan beat Portugal?',
		'Will a goal be scored in the first half of Argentina vs Austria?',
		'Will a penalty be awarded in Colombia vs DR Congo?',
		'Will a penalty be awarded in Norway vs Senegal?',
		'Will a penalty be awarded in Portugal vs Uzbekistan?',
		'Will any player receive a red card in England vs Ghana?',
		'Will any player receive a red card in Panama vs Croatia?',
		'Will both teams score in Argentina vs Austria?',
		'Will both teams score in England vs Ghana?',
		'Will both teams score in Jordan vs Algeria?',
		'Will both teams score in Morocco vs Haiti?',
		'Will both teams score in Norway vs Senegal?',
		'Will both teams score in Scotland vs Brazil?',
		'Will the Netherlands win Group F?',
		'Will there be 3 or more goals in Colombia vs DR Congo?',
		'Will there be 3 or more goals in Czechia vs Mexico?',
		'Will there be 3 or more goals in Panama vs Croatia?',
		'Will there be 3 or more goals in Portugal vs Uzbekistan?',
		'Will there be 3 or more goals in Switzerland vs Canada?',
		'Will there be 4 or more goals in France vs Iraq?'
	],
	'2026-06-22': [
		'Will Belgium win Group G?',
		'Will Canada beat Switzerland?',
		'Will Colombia beat DR Congo?',
		'Will Croatia beat Panama?',
		'Will Croatia score 2 or more goals against Panama?',
		'Will Curaçao vs Ivory Coast end in a draw?',
		'Will Czechia beat Mexico?',
		'Will Ecuador vs Germany end in a draw?',
		'Will Egypt win Group G?',
		'Will England beat Ghana?',
		'Will England keep a clean sheet against Ghana?',
		'Will Germany score 2 or more goals against Ecuador?',
		'Will Haiti beat Morocco?',
		'Will Iran win Group G?',
		'Will Ivory Coast keep a clean sheet against Curaçao?',
		'Will Japan vs Sweden end in a draw?',
		'Will Morocco keep a clean sheet against Haiti?',
		'Will New Zealand win Group G?',
		'Will Paraguay vs Australia end in a draw?',
		'Will Portugal beat Uzbekistan?',
		'Will Qatar beat Bosnia and Herzegovina?',
		'Will Scotland beat Brazil?',
		'Will South Africa beat Korea Republic?',
		'Will Spain win Group H?',
		'Will Switzerland keep a clean sheet against Canada?',
		'Will Tunisia vs the Netherlands end in a draw?',
		'Will Türkiye vs the United States end in a draw?',
		'Will Uruguay win Group H?',
		'Will a goal be scored in the first half of Portugal vs Uzbekistan?',
		'Will a penalty be awarded in Czechia vs Mexico?',
		'Will a penalty be awarded in Morocco vs Haiti?',
		'Will a penalty be awarded in Panama vs Croatia?',
		'Will any player receive a red card in Bosnia and Herzegovina vs Qatar?',
		'Will any player receive a red card in Scotland vs Brazil?',
		'Will any player receive a red card in South Africa vs Korea Republic?',
		'Will both teams score in Colombia vs DR Congo?',
		'Will both teams score in Czechia vs Mexico?',
		'Will both teams score in Portugal vs Uzbekistan?',
		'Will both teams score in Switzerland vs Canada?',
		'Will the United States score 2 or more goals against Türkiye?',
		'Will the opening goal come inside the first 15 minutes of Bosnia and Herzegovina vs Qatar?',
		'Will the opening goal come inside the first 15 minutes of Colombia vs DR Congo?',
		'Will the opening goal come inside the first 15 minutes of Paraguay vs Australia?',
		'Will the opening goal come inside the first 15 minutes of South Africa vs Korea Republic?',
		'Will the opening goal come inside the first 15 minutes of Tunisia vs the Netherlands?',
		'Will there be 3 or more goals in Japan vs Sweden?',
		'Will there be 3 or more goals in Scotland vs Brazil?',
		'Will there be 4 or more goals in England vs Ghana?'
	],
	'2026-06-23': [
		'Will Australia beat Paraguay?',
		'Will Bosnia and Herzegovina beat Qatar?',
		'Will Brazil beat Scotland?',
		'Will Brazil score 2 or more goals against Scotland?',
		'Will Cape Verde score 2 or more goals against Saudi Arabia?',
		'Will Cape Verde vs Saudi Arabia end in a draw?',
		'Will Cape Verde win Group H?',
		'Will Curaçao beat Ivory Coast?',
		'Will Ecuador beat Germany?',
		'Will Egypt vs Iran end in a draw?',
		'Will Korea Republic beat South Africa?',
		'Will Mexico beat Czechia?',
		'Will Mexico keep a clean sheet against Czechia?',
		'Will Morocco beat Haiti?',
		'Will Norway vs France end in a draw?',
		'Will Paraguay keep a clean sheet against Australia?',
		'Will Senegal vs Iraq end in a draw?',
		'Will Spain keep a clean sheet against Uruguay?',
		'Will Sweden beat Japan?',
		'Will Switzerland beat Canada?',
		'Will Tunisia beat the Netherlands?',
		'Will Türkiye beat the United States?',
		'Will Uruguay vs Spain end in a draw?',
		'Will a goal be scored in the first half of Czechia vs Mexico?',
		'Will a goal be scored in the first half of Switzerland vs Canada?',
		'Will a penalty be awarded in Curaçao vs Ivory Coast?',
		'Will a penalty be awarded in Japan vs Sweden?',
		'Will a penalty be awarded in Scotland vs Brazil?',
		'Will a penalty be awarded in Switzerland vs Canada?',
		'Will any player receive a red card in Ecuador vs Germany?',
		'Will any player receive a red card in Tunisia vs the Netherlands?',
		'Will any player receive a red card in Türkiye vs the United States?',
		'Will both teams score in Bosnia and Herzegovina vs Qatar?',
		'Will both teams score in Japan vs Sweden?',
		'Will both teams score in Norway vs France?',
		'Will both teams score in South Africa vs Korea Republic?',
		'Will the Netherlands keep a clean sheet against Tunisia?',
		'Will the opening goal come inside the first 15 minutes of Morocco vs Haiti?',
		'Will the opening goal come inside the first 15 minutes of New Zealand vs Belgium?',
		'Will the opening goal come inside the first 15 minutes of Senegal vs Iraq?',
		'Will there be 3 or more goals in Curaçao vs Ivory Coast?',
		'Will there be 3 or more goals in Ecuador vs Germany?',
		'Will there be 3 or more goals in Egypt vs Iran?',
		'Will there be 3 or more goals in Morocco vs Haiti?',
		'Will there be 3 or more goals in Paraguay vs Australia?',
		'Will there be 3 or more goals in Türkiye vs the United States?',
		'Will there be 4 or more goals in Bosnia and Herzegovina vs Qatar?',
		'Will there be 4 or more goals in South Africa vs Korea Republic?'
	],
	'2026-06-24': [
		'Will Algeria vs Austria end in a draw?',
		'Will Austria score 2 or more goals against Algeria?',
		'Will Colombia vs Portugal end in a draw?',
		'Will Croatia keep a clean sheet against Ghana?',
		'Will Croatia vs Ghana end in a draw?',
		'Will DR Congo vs Uzbekistan end in a draw?',
		'Will Egypt keep a clean sheet against Iran?',
		'Will Germany beat Ecuador?',
		'Will Iran beat Egypt?',
		'Will Iraq beat Senegal?',
		'Will Ivory Coast beat Curaçao?',
		'Will Japan beat Sweden?',
		'Will Japan keep a clean sheet against Sweden?',
		'Will Jordan vs Argentina end in a draw?',
		'Will New Zealand beat Belgium?',
		'Will Norway beat France?',
		'Will Panama vs England end in a draw?',
		'Will Paraguay beat Australia?',
		'Will Saudi Arabia beat Cape Verde?',
		'Will Senegal keep a clean sheet against Iraq?',
		'Will Uruguay beat Spain?',
		'Will a goal be scored in the first half of Japan vs Sweden?',
		'Will a penalty be awarded in Ecuador vs Germany?',
		'Will a penalty be awarded in Norway vs France?',
		'Will a penalty be awarded in Paraguay vs Australia?',
		'Will a penalty be awarded in Türkiye vs the United States?',
		'Will a penalty be awarded in Uruguay vs Spain?',
		'Will any player receive a red card in Cape Verde vs Saudi Arabia?',
		'Will any player receive a red card in New Zealand vs Belgium?',
		'Will any player receive a red card in Senegal vs Iraq?',
		'Will both teams score in Curaçao vs Ivory Coast?',
		'Will both teams score in Ecuador vs Germany?',
		'Will both teams score in Egypt vs Iran?',
		'Will both teams score in Jordan vs Argentina?',
		'Will both teams score in New Zealand vs Belgium?',
		'Will both teams score in Panama vs England?',
		'Will both teams score in Paraguay vs Australia?',
		'Will both teams score in Tunisia vs the Netherlands?',
		'Will both teams score in Türkiye vs the United States?',
		'Will the Netherlands beat Tunisia?',
		'Will the United States beat Türkiye?',
		'Will the opening goal come inside the first 15 minutes of Curaçao vs Ivory Coast?',
		'Will there be 3 or more goals in Cape Verde vs Saudi Arabia?',
		'Will there be 3 or more goals in Colombia vs Portugal?',
		'Will there be 3 or more goals in Norway vs France?',
		'Will there be 3 or more goals in Uruguay vs Spain?',
		'Will there be 4 or more goals in DR Congo vs Uzbekistan?',
		'Will there be 4 or more goals in Tunisia vs the Netherlands?'
	],
	'2026-06-25': [
		'Will Algeria beat Austria?',
		'Will Belgium beat New Zealand?',
		'Will Belgium keep a clean sheet against New Zealand?',
		'Will Cape Verde beat Saudi Arabia?',
		'Will Colombia beat Portugal?',
		'Will Colombia win Group K?',
		'Will DR Congo win Group K?',
		'Will Egypt beat Iran?',
		'Will England win Group L?',
		'Will France beat Norway?',
		'Will France keep a clean sheet against Norway?',
		'Will Ghana beat Croatia?',
		'Will Jordan beat Argentina?',
		'Will Jordan win Group J?',
		'Will Panama beat England?',
		'Will Portugal win Group K?',
		'Will Senegal beat Iraq?',
		'Will Spain beat Uruguay?',
		'Will Uzbekistan beat DR Congo?',
		'Will Uzbekistan win Group K?',
		'Will a goal be scored in the first half of Egypt vs Iran?',
		'Will a goal be scored in the first half of Norway vs France?',
		'Will a penalty be awarded in Cape Verde vs Saudi Arabia?',
		'Will a penalty be awarded in Colombia vs Portugal?',
		'Will a penalty be awarded in Croatia vs Ghana?',
		'Will a penalty be awarded in Egypt vs Iran?',
		'Will a penalty be awarded in Jordan vs Argentina?',
		'Will any player receive a red card in Algeria vs Austria?',
		'Will any player receive a red card in DR Congo vs Uzbekistan?',
		'Will any player receive a red card in Panama vs England?',
		'Will both teams score in Cape Verde vs Saudi Arabia?',
		'Will both teams score in Colombia vs Portugal?',
		'Will both teams score in Senegal vs Iraq?',
		'Will both teams score in Uruguay vs Spain?',
		'Will the opening goal come inside the first 15 minutes of DR Congo vs Uzbekistan?',
		'Will the opening goal come inside the first 15 minutes of Uruguay vs Spain?',
		'Will there be 3 or more goals in Algeria vs Austria?',
		'Will there be 3 or more goals in Croatia vs Ghana?',
		'Will there be 3 or more goals in Jordan vs Argentina?',
		'Will there be 3 or more goals in Panama vs England?',
		'Will there be 4 or more goals in New Zealand vs Belgium?',
		'Will there be 4 or more goals in Senegal vs Iraq?'
	],
	'2026-06-26': [
		'Will Argentina beat Jordan?',
		'Will Argentina keep a clean sheet against Jordan?',
		'Will Austria beat Algeria?',
		'Will Croatia beat Ghana?',
		'Will Croatia win Group L?',
		'Will DR Congo beat Uzbekistan?',
		'Will DR Congo keep a clean sheet against Uzbekistan?',
		'Will England beat Panama?',
		'Will England score 2 or more goals against Panama?',
		'Will Ghana win Group L?',
		'Will Portugal beat Colombia?',
		'Will Portugal keep a clean sheet against Colombia?',
		'Will a goal be scored in the first half of Colombia vs Portugal?',
		'Will a penalty be awarded in Algeria vs Austria?',
		'Will a penalty be awarded in Panama vs England?',
		'Will both teams score in Algeria vs Austria?',
		'Will both teams score in Croatia vs Ghana?',
		'Will both teams score in DR Congo vs Uzbekistan?',
		'Will the opening goal come inside the first 15 minutes of Croatia vs Ghana?',
		'Will the opening goal come inside the first 15 minutes of Jordan vs Argentina?'
	],
	'2026-06-29': [
		'Will Brazil vs Japan be decided by a single goal?',
		'Will Brazil win against Japan in normal time?',
		'Will Cody Gakpo score against Morocco?',
		'Will Germany vs Paraguay be decided by a single goal?',
		'Will Germany win against Paraguay in normal time?',
		'Will Jamal Musiala score or assist against Paraguay?',
		'Will Julio Enciso score against Germany?',
		'Will Kai Havertz score against Paraguay?',
		'Will Kaoru Mitoma score against Brazil?',
		'Will Memphis Depay score or assist against Morocco?',
		'Will Netherlands vs Morocco be decided by a single goal?',
		'Will Netherlands vs Morocco go to extra time or penalties?',
		'Will Netherlands win against Morocco in normal time?',
		'Will Raphinha score or assist against Japan?',
		'Will Vinícius Júnior score against Japan?',
		'Will Youssef En-Nesyri score against Netherlands?',
		'Will a goal be scored from outside the penalty area in Brazil vs Japan?',
		'Will a goal be scored from outside the penalty area in Germany vs Paraguay?',
		'Will a goal be scored from outside the penalty area in Netherlands vs Morocco?',
		'Will a goal be scored in the eightieth minute or later of Brazil vs Japan?',
		'Will a goal be scored in the eightieth minute or later of Germany vs Paraguay?',
		'Will a goal be scored in the eightieth minute or later of Netherlands vs Morocco?',
		'Will a header be scored in Brazil vs Japan?',
		'Will a header be scored in Germany vs Paraguay?',
		'Will a header be scored in Netherlands vs Morocco?',
		'Will a player aged nineteen or younger score in the Round of 32?',
		'Will any team win a Round of 32 match after trailing by two or more goals?',
		'Will five or more Round of 32 matches be won by the lower-ranked team?',
		'Will four or more Round of 32 matches be decided by a penalty shootout?',
		'Will more than two and a half goals be scored in Brazil vs Japan?',
		'Will more than two and a half goals be scored in Germany vs Paraguay?',
		'Will more than two and a half goals be scored in Netherlands vs Morocco?',
		'Will the Round of 32 average more than two and a half goals per match?',
		'Will the score be level at half-time in Brazil vs Japan?',
		'Will the score be level at half-time in Germany vs Paraguay?',
		'Will the score be level at half-time in Netherlands vs Morocco?',
		'Will the second half of Brazil vs Japan produce more goals than the first?',
		'Will the second half of Germany vs Paraguay produce more goals than the first?',
		'Will the second half of Netherlands vs Morocco produce more goals than the first?',
		'Will three or more yellow cards be shown in Brazil vs Japan?',
		'Will three or more yellow cards be shown in Germany vs Paraguay?',
		'Will three or more yellow cards be shown in Netherlands vs Morocco?'
	],
	'2026-06-30': [
		'Will Alexander Isak score against France?',
		'Will Enner Valencia score against Mexico?',
		'Will Erling Haaland score against Ivory Coast?',
		'Will France vs Sweden be decided by a single goal?',
		'Will Hirving Lozano score or assist against Ecuador?',
		'Will Ivory Coast vs Norway be decided by a single goal?',
		'Will Ivory Coast vs Norway go to extra time or penalties?',
		'Will Kylian Mbappé score against Sweden?',
		'Will Martin Ødegaard score or assist against Ivory Coast?',
		'Will Mexico vs Ecuador be decided by a single goal?',
		'Will Mexico vs Ecuador go to extra time or penalties?',
		'Will Mexico win against Ecuador in normal time?',
		'Will Norway win against Ivory Coast in normal time?',
		'Will Ousmane Dembélé score or assist against Sweden?',
		'Will Santiago Giménez score against Ecuador?',
		'Will Sébastien Haller score against Norway?',
		'Will a goal be scored from outside the penalty area in France vs Sweden?',
		'Will a goal be scored from outside the penalty area in Ivory Coast vs Norway?',
		'Will a goal be scored from outside the penalty area in Mexico vs Ecuador?',
		'Will a goal be scored in the eightieth minute or later of France vs Sweden?',
		'Will a goal be scored in the eightieth minute or later of Ivory Coast vs Norway?',
		'Will a goal be scored in the eightieth minute or later of Mexico vs Ecuador?',
		'Will a header be scored in France vs Sweden?',
		'Will a header be scored in Ivory Coast vs Norway?',
		'Will a header be scored in Mexico vs Ecuador?',
		'Will more than two and a half goals be scored in France vs Sweden?',
		'Will more than two and a half goals be scored in Ivory Coast vs Norway?',
		'Will more than two and a half goals be scored in Mexico vs Ecuador?',
		'Will the score be level at half-time in France vs Sweden?',
		'Will the score be level at half-time in Ivory Coast vs Norway?',
		'Will the score be level at half-time in Mexico vs Ecuador?',
		'Will the second half of France vs Sweden produce more goals than the first?',
		'Will the second half of Ivory Coast vs Norway produce more goals than the first?',
		'Will the second half of Mexico vs Ecuador produce more goals than the first?',
		'Will three or more yellow cards be shown in France vs Sweden?',
		'Will three or more yellow cards be shown in Ivory Coast vs Norway?',
		'Will three or more yellow cards be shown in Mexico vs Ecuador?'
	],
	'2026-07-01': [
		'Will Belgium vs Senegal be decided by a single goal?',
		'Will Belgium vs Senegal go to extra time or penalties?',
		'Will Belgium win against Senegal in normal time?',
		'Will Christian Pulisic score or assist against Bosnia and Herzegovina?',
		'Will Edin Džeko score against United States?',
		'Will England vs DR Congo be decided by a single goal?',
		'Will England win against DR Congo in normal time?',
		'Will Folarin Balogun score against Bosnia and Herzegovina?',
		'Will Harry Kane score against DR Congo?',
		'Will Jude Bellingham score or assist against DR Congo?',
		'Will Kevin De Bruyne score or assist against Senegal?',
		'Will Romelu Lukaku score against Senegal?',
		'Will Sadio Mané score against Belgium?',
		'Will United States vs Bosnia and Herzegovina be decided by a single goal?',
		'Will United States vs Bosnia and Herzegovina go to extra time or penalties?',
		'Will United States win against Bosnia and Herzegovina in normal time?',
		'Will Yoane Wissa score against England?',
		'Will a goal be scored from outside the penalty area in Belgium vs Senegal?',
		'Will a goal be scored from outside the penalty area in England vs DR Congo?',
		'Will a goal be scored from outside the penalty area in United States vs Bosnia and Herzegovina?',
		'Will a goal be scored in the eightieth minute or later of Belgium vs Senegal?',
		'Will a goal be scored in the eightieth minute or later of England vs DR Congo?',
		'Will a goal be scored in the eightieth minute or later of United States vs Bosnia and Herzegovina?',
		'Will a header be scored in Belgium vs Senegal?',
		'Will a header be scored in England vs DR Congo?',
		'Will a header be scored in United States vs Bosnia and Herzegovina?',
		'Will more than two and a half goals be scored in Belgium vs Senegal?',
		'Will more than two and a half goals be scored in England vs DR Congo?',
		'Will more than two and a half goals be scored in United States vs Bosnia and Herzegovina?',
		'Will the score be level at half-time in Belgium vs Senegal?',
		'Will the score be level at half-time in England vs DR Congo?',
		'Will the score be level at half-time in United States vs Bosnia and Herzegovina?',
		'Will the second half of Belgium vs Senegal produce more goals than the first?',
		'Will the second half of England vs DR Congo produce more goals than the first?',
		'Will the second half of United States vs Bosnia and Herzegovina produce more goals than the first?',
		'Will three or more yellow cards be shown in Belgium vs Senegal?',
		'Will three or more yellow cards be shown in England vs DR Congo?',
		'Will three or more yellow cards be shown in United States vs Bosnia and Herzegovina?'
	],
	'2026-07-02': [
		'Will Andrej Kramarić score against Portugal?',
		'Will Breel Embolo score against Algeria?',
		'Will Bruno Fernandes score or assist against Croatia?',
		'Will Cristiano Ronaldo score against Croatia?',
		'Will Granit Xhaka score or assist against Algeria?',
		'Will Lamine Yamal score or assist against Austria?',
		'Will Marko Arnautović score against Spain?',
		'Will Portugal vs Croatia be decided by a single goal?',
		'Will Portugal vs Croatia go to extra time or penalties?',
		'Will Portugal win against Croatia in normal time?',
		'Will Riyad Mahrez score against Switzerland?',
		'Will Spain vs Austria be decided by a single goal?',
		'Will Spain win against Austria in normal time?',
		'Will Switzerland vs Algeria be decided by a single goal?',
		'Will Switzerland vs Algeria go to extra time or penalties?',
		'Will Switzerland win against Algeria in normal time?',
		'Will a goal be scored from outside the penalty area in Portugal vs Croatia?',
		'Will a goal be scored from outside the penalty area in Spain vs Austria?',
		'Will a goal be scored from outside the penalty area in Switzerland vs Algeria?',
		'Will a goal be scored in the eightieth minute or later of Portugal vs Croatia?',
		'Will a goal be scored in the eightieth minute or later of Spain vs Austria?',
		'Will a goal be scored in the eightieth minute or later of Switzerland vs Algeria?',
		'Will a header be scored in Portugal vs Croatia?',
		'Will a header be scored in Spain vs Austria?',
		'Will a header be scored in Switzerland vs Algeria?',
		'Will more than two and a half goals be scored in Portugal vs Croatia?',
		'Will more than two and a half goals be scored in Spain vs Austria?',
		'Will more than two and a half goals be scored in Switzerland vs Algeria?',
		'Will the score be level at half-time in Portugal vs Croatia?',
		'Will the score be level at half-time in Spain vs Austria?',
		'Will the score be level at half-time in Switzerland vs Algeria?',
		'Will the second half of Portugal vs Croatia produce more goals than the first?',
		'Will the second half of Spain vs Austria produce more goals than the first?',
		'Will the second half of Switzerland vs Algeria produce more goals than the first?',
		'Will three or more yellow cards be shown in Portugal vs Croatia?',
		'Will three or more yellow cards be shown in Spain vs Austria?',
		'Will three or more yellow cards be shown in Switzerland vs Algeria?',
		'Will Álvaro Morata score against Austria?'
	],
	'2026-07-03': [
		'Will Argentina vs Cape Verde be decided by a single goal?',
		'Will Australia vs Egypt be decided by a single goal?',
		'Will Australia vs Egypt go to extra time or penalties?',
		'Will Colombia vs Ghana be decided by a single goal?',
		'Will Colombia vs Ghana go to extra time or penalties?',
		'Will Colombia win against Ghana in normal time?',
		'Will Egypt win against Australia in normal time?',
		'Will James Rodríguez score or assist against Ghana?',
		'Will Julián Álvarez score against Cape Verde?',
		'Will Lautaro Martínez score against Cape Verde?',
		'Will Lionel Messi score or assist against Cape Verde?',
		'Will Luis Díaz score against Ghana?',
		'Will Mitchell Duke score against Egypt?',
		'Will Mohamed Salah score against Australia?',
		'Will Mohammed Kudus score against Colombia?',
		'Will Omar Marmoush score or assist against Australia?',
		'Will a goal be scored from outside the penalty area in Argentina vs Cape Verde?',
		'Will a goal be scored from outside the penalty area in Australia vs Egypt?',
		'Will a goal be scored from outside the penalty area in Colombia vs Ghana?',
		'Will a goal be scored in the eightieth minute or later of Argentina vs Cape Verde?',
		'Will a goal be scored in the eightieth minute or later of Australia vs Egypt?',
		'Will a goal be scored in the eightieth minute or later of Colombia vs Ghana?',
		'Will a header be scored in Argentina vs Cape Verde?',
		'Will a header be scored in Australia vs Egypt?',
		'Will a header be scored in Colombia vs Ghana?',
		'Will more than two and a half goals be scored in Argentina vs Cape Verde?',
		'Will more than two and a half goals be scored in Australia vs Egypt?',
		'Will more than two and a half goals be scored in Colombia vs Ghana?',
		'Will the score be level at half-time in Argentina vs Cape Verde?',
		'Will the score be level at half-time in Australia vs Egypt?',
		'Will the score be level at half-time in Colombia vs Ghana?',
		'Will the second half of Argentina vs Cape Verde produce more goals than the first?',
		'Will the second half of Australia vs Egypt produce more goals than the first?',
		'Will the second half of Colombia vs Ghana produce more goals than the first?',
		'Will three or more yellow cards be shown in Argentina vs Cape Verde?',
		'Will three or more yellow cards be shown in Australia vs Egypt?',
		'Will three or more yellow cards be shown in Colombia vs Ghana?'
	]
};

/**
 * Normalizes a market question into the key both the schedule table and the
 * lookups are indexed by: trimmed, internal whitespace collapsed to single
 * spaces, lower-cased. Accents and apostrophes are intentionally preserved —
 * they are part of the team names that distinguish questions. Both the table
 * (build time) and incoming market titles (lookup time) pass through this so
 * a match never hinges on incidental spacing or casing differences.
 */
export const normalizeWcQuestion = (question: string): string =>
	question.trim().replace(/\s+/g, ' ').toLowerCase();

/**
 * Builds the `normalized question -> earliest reveal (ms, 00:00 UTC of the
 * Show Date)` lookup from {@link WC_MARKET_SCHEDULE}. A question listed under
 * more than one date resolves to its earliest release, so a market is never
 * held back past the first day it was scheduled to appear.
 *
 * The **first** scheduled day is seeded as always-on (reveal `0`) so the WC
 * feed is never empty before the calendar formally begins — the opening set
 * is live the moment this ships, and every later set still unlocks at 00:00
 * UTC of its own Show Date. Once the opening day is in the past this clamp is
 * a no-op (its real timestamp would already be revealed), so it only bridges
 * the pre-launch gap and never leaks a future day into the current one.
 */
const buildRevealMap = (): ReadonlyMap<string, number> => {
	const map = new Map<string, number>();

	// Object key order is insertion order: the calendar is authored
	// chronologically, so the first date is the opening set we seed as live.
	const [openingDate] = Object.keys(WC_MARKET_SCHEDULE);

	for (const [showDate, questions] of Object.entries(WC_MARKET_SCHEDULE)) {
		// This calendar is hand-edited, so a typo'd Show Date would otherwise
		// parse to `NaN` and silently hide its whole set forever. Fail loud at
		// module load (dev/CI) instead so the mistake is caught immediately.
		const parsedMs = Date.parse(`${showDate}T00:00:00.000Z`);

		if (Number.isNaN(parsedMs)) {
			throw new Error(
				`Invalid WC schedule Show Date "${showDate}" — expected an ISO YYYY-MM-DD key.`
			);
		}

		const revealMs = showDate === openingDate ? 0 : parsedMs;

		for (const question of questions) {
			const key = normalizeWcQuestion(question);
			const existing = map.get(key);

			if (isNullish(existing) || revealMs < existing) {
				map.set(key, revealMs);
			}
		}
	}

	return map;
};

/**
 * `normalized question -> reveal timestamp (ms)` for every scheduled
 * World-Cup market. A missing key means the market is not on the calendar
 * and must stay hidden.
 */
export const WC_QUESTION_REVEAL_MS: ReadonlyMap<string, number> = buildRevealMap();
