import type { AffiliationKind } from '$lib/types/affiliation';

/**
 * Static rosters for the FE Worlds picker. The satellite keys
 * affiliations by `(kind, affiliationIdentifier)` without validating against
 * an external list, so the FE owns the curated set of choices.
 *
 * Future: an admin-curated registry collection can replace these
 * hardcoded arrays without touching the satellite assert (the assert
 * only enforces shape + lock, not the affiliation id's existence).
 */

export interface WorldsAffiliationOption {
	/** External id stored on `AffiliationDoc.affiliationIdentifier`. */
	id: string;
	/** Display name. */
	name: string;
	/** Decorative glyph — emoji flag for countries, short acronym for
	 *  universities (mirrors {@link short} for the university roster so
	 *  every existing consumer keeps rendering a tile). */
	glyph: string;
	/** University-only fields below — countries never carry them. */
	/** Short acronym shown on the picker tile. */
	short?: string;
	/** ISO-3166-1 alpha-2 home country, drives the picker's "Near you"
	 *  pinning. */
	country?: string;
	/** Coarse region bucket backing the picker's region tabs. `LATAM`
	 *  and `MEA` entries surface only under the "All" tab or search. */
	region?: 'NA' | 'UK' | 'EU' | 'AS' | 'AU' | 'LATAM' | 'MEA';
	/** Verified email domains — reserved for a later membership-
	 *  verification pass; unused by the current picker. */
	domains?: readonly string[];
	/** Approximate QS World Rank, used as the default browse sort. */
	rank?: number;
	/** Brand colour for the tile background (hex). */
	color?: string;
	/** Foreground colour over {@link color} (hex). */
	text?: string;
}

/**
 * University roster — the full global directory (~278 institutions)
 * spanning every region bucket. Each entry carries its acronym
 * (`glyph`/`short`), home `country`, `region`, brand colours, QS
 * `rank`, and verified email `domains`. Ordered by region then rank;
 * the picker re-sorts at render time. Additions are append-only (no
 * satellite migration needed). The Worlds leaderboard reads live
 * `affiliation_stats`, not this list — so editing it drops no data.
 */
export const WORLDS_UNIVERSITIES: readonly WorldsAffiliationOption[] = [
	// North America · United States
	{
		id: 'mit',
		name: 'MIT',
		glyph: 'MIT',
		short: 'MIT',
		country: 'US',
		region: 'NA',
		domains: ['mit.edu'],
		rank: 1,
		color: '#A31F34',
		text: '#F2ECDC'
	},
	{
		id: 'stanford',
		name: 'Stanford',
		glyph: 'STAN',
		short: 'STAN',
		country: 'US',
		region: 'NA',
		domains: ['stanford.edu'],
		rank: 2,
		color: '#8C1515',
		text: '#F2ECDC'
	},
	{
		id: 'harvard',
		name: 'Harvard',
		glyph: 'HARV',
		short: 'HARV',
		country: 'US',
		region: 'NA',
		domains: ['harvard.edu', 'college.harvard.edu', 'hbs.edu'],
		rank: 4,
		color: '#A51C30',
		text: '#F2ECDC'
	},
	{
		id: 'caltech',
		name: 'Caltech',
		glyph: 'CAL',
		short: 'CAL',
		country: 'US',
		region: 'NA',
		domains: ['caltech.edu'],
		rank: 10,
		color: '#FF6C0C',
		text: '#1A1A1A'
	},
	{
		id: 'berkeley',
		name: 'UC Berkeley',
		glyph: 'BERK',
		short: 'BERK',
		country: 'US',
		region: 'NA',
		domains: ['berkeley.edu'],
		rank: 12,
		color: '#003262',
		text: '#FDB515'
	},
	{
		id: 'princeton',
		name: 'Princeton',
		glyph: 'PRIN',
		short: 'PRIN',
		country: 'US',
		region: 'NA',
		domains: ['princeton.edu'],
		rank: 17,
		color: '#FF8F1C',
		text: '#1A1A1A'
	},
	{
		id: 'yale',
		name: 'Yale',
		glyph: 'YALE',
		short: 'YALE',
		country: 'US',
		region: 'NA',
		domains: ['yale.edu', 'som.yale.edu'],
		rank: 23,
		color: '#0F4D92',
		text: '#F2ECDC'
	},
	{
		id: 'upenn',
		name: 'Penn (UPenn)',
		glyph: 'PENN',
		short: 'PENN',
		country: 'US',
		region: 'NA',
		domains: ['upenn.edu', 'wharton.upenn.edu'],
		rank: 11,
		color: '#011F5B',
		text: '#F2ECDC'
	},
	{
		id: 'cornell',
		name: 'Cornell',
		glyph: 'CORN',
		short: 'CORN',
		country: 'US',
		region: 'NA',
		domains: ['cornell.edu'],
		rank: 16,
		color: '#B31B1B',
		text: '#F2ECDC'
	},
	{
		id: 'columbia',
		name: 'Columbia',
		glyph: 'COLU',
		short: 'COLU',
		country: 'US',
		region: 'NA',
		domains: ['columbia.edu', 'gsb.columbia.edu'],
		rank: 34,
		color: '#9BCBEB',
		text: '#1A1A1A'
	},
	{
		id: 'chicago',
		name: 'University of Chicago',
		glyph: 'UCHI',
		short: 'UCHI',
		country: 'US',
		region: 'NA',
		domains: ['uchicago.edu', 'chicagobooth.edu'],
		rank: 21,
		color: '#800000',
		text: '#F2ECDC'
	},
	{
		id: 'dartmouth',
		name: 'Dartmouth',
		glyph: 'DART',
		short: 'DART',
		country: 'US',
		region: 'NA',
		domains: ['dartmouth.edu', 'tuck.dartmouth.edu'],
		rank: 219,
		color: '#00693E',
		text: '#F2ECDC'
	},
	{
		id: 'brown',
		name: 'Brown',
		glyph: 'BROW',
		short: 'BROW',
		country: 'US',
		region: 'NA',
		domains: ['brown.edu'],
		rank: 64,
		color: '#4E3629',
		text: '#F2ECDC'
	},
	{
		id: 'jhu',
		name: 'Johns Hopkins',
		glyph: 'JHU',
		short: 'JHU',
		country: 'US',
		region: 'NA',
		domains: ['jhu.edu', 'jh.edu'],
		rank: 37,
		color: '#002D72',
		text: '#F2ECDC'
	},
	{
		id: 'northwestern',
		name: 'Northwestern',
		glyph: 'NWST',
		short: 'NWST',
		country: 'US',
		region: 'NA',
		domains: ['northwestern.edu', 'kellogg.northwestern.edu'],
		rank: 50,
		color: '#4E2A84',
		text: '#F2ECDC'
	},
	{
		id: 'duke',
		name: 'Duke',
		glyph: 'DUKE',
		short: 'DUKE',
		country: 'US',
		region: 'NA',
		domains: ['duke.edu', 'fuqua.duke.edu'],
		rank: 51,
		color: '#012169',
		text: '#F2ECDC'
	},
	{
		id: 'cmu',
		name: 'Carnegie Mellon',
		glyph: 'CMU',
		short: 'CMU',
		country: 'US',
		region: 'NA',
		domains: ['cmu.edu', 'andrew.cmu.edu'],
		rank: 58,
		color: '#C41230',
		text: '#F2ECDC'
	},
	{
		id: 'umich',
		name: 'Michigan (Ann Arbor)',
		glyph: 'UMIC',
		short: 'UMIC',
		country: 'US',
		region: 'NA',
		domains: ['umich.edu', 'ross.umich.edu'],
		rank: 44,
		color: '#00274C',
		text: '#FFCB05'
	},
	{
		id: 'ucla',
		name: 'UCLA',
		glyph: 'UCLA',
		short: 'UCLA',
		country: 'US',
		region: 'NA',
		domains: ['ucla.edu', 'anderson.ucla.edu'],
		rank: 42,
		color: '#2774AE',
		text: '#FFD100'
	},
	{
		id: 'usc',
		name: 'USC',
		glyph: 'USC',
		short: 'USC',
		country: 'US',
		region: 'NA',
		domains: ['usc.edu', 'marshall.usc.edu'],
		rank: 116,
		color: '#990000',
		text: '#FFCC00'
	},
	{
		id: 'nyu',
		name: 'NYU',
		glyph: 'NYU',
		short: 'NYU',
		country: 'US',
		region: 'NA',
		domains: ['nyu.edu', 'stern.nyu.edu'],
		rank: 38,
		color: '#57068C',
		text: '#F2ECDC'
	},
	{
		id: 'georgetown',
		name: 'Georgetown',
		glyph: 'GTWN',
		short: 'GTWN',
		country: 'US',
		region: 'NA',
		domains: ['georgetown.edu', 'msb.edu'],
		rank: 244,
		color: '#041E42',
		text: '#F2ECDC'
	},
	{
		id: 'georgiatech',
		name: 'Georgia Tech',
		glyph: 'GT',
		short: 'GT',
		country: 'US',
		region: 'NA',
		domains: ['gatech.edu'],
		rank: 80,
		color: '#B3A369',
		text: '#1A1A1A'
	},
	{
		id: 'umd',
		name: 'Maryland',
		glyph: 'UMD',
		short: 'UMD',
		country: 'US',
		region: 'NA',
		domains: ['umd.edu', 'umaryland.edu'],
		rank: 142,
		color: '#E03A3E',
		text: '#FFD200'
	},
	{
		id: 'utexas',
		name: 'UT Austin',
		glyph: 'UT',
		short: 'UT',
		country: 'US',
		region: 'NA',
		domains: ['utexas.edu', 'mccombs.utexas.edu'],
		rank: 58,
		color: '#BF5700',
		text: '#F2ECDC'
	},
	{
		id: 'wustl',
		name: 'Washington (St. Louis)',
		glyph: 'WUST',
		short: 'WUST',
		country: 'US',
		region: 'NA',
		domains: ['wustl.edu', 'olin.wustl.edu'],
		rank: 142,
		color: '#A51417',
		text: '#F2ECDC'
	},
	{
		id: 'rice',
		name: 'Rice',
		glyph: 'RICE',
		short: 'RICE',
		country: 'US',
		region: 'NA',
		domains: ['rice.edu'],
		rank: 141,
		color: '#00205B',
		text: '#F2ECDC'
	},
	{
		id: 'emory',
		name: 'Emory',
		glyph: 'EMOR',
		short: 'EMOR',
		country: 'US',
		region: 'NA',
		domains: ['emory.edu', 'goizueta.emory.edu'],
		rank: 162,
		color: '#012169',
		text: '#F2ECDC'
	},
	{
		id: 'notredame',
		name: 'Notre Dame',
		glyph: 'ND',
		short: 'ND',
		country: 'US',
		region: 'NA',
		domains: ['nd.edu', 'mendoza.nd.edu'],
		rank: 173,
		color: '#0C2340',
		text: '#C99700'
	},
	{
		id: 'vanderbilt',
		name: 'Vanderbilt',
		glyph: 'VAND',
		short: 'VAND',
		country: 'US',
		region: 'NA',
		domains: ['vanderbilt.edu', 'owen.vanderbilt.edu'],
		rank: 196,
		color: '#866D4B',
		text: '#F2ECDC'
	},
	{
		id: 'tufts',
		name: 'Tufts',
		glyph: 'TUFT',
		short: 'TUFT',
		country: 'US',
		region: 'NA',
		domains: ['tufts.edu'],
		rank: 213,
		color: '#3E8EDE',
		text: '#F2ECDC'
	},
	{
		id: 'unc',
		name: 'UNC Chapel Hill',
		glyph: 'UNC',
		short: 'UNC',
		country: 'US',
		region: 'NA',
		domains: ['unc.edu', 'kenan-flagler.unc.edu'],
		rank: 87,
		color: '#7BAFD4',
		text: '#1A1A1A'
	},
	{
		id: 'uva',
		name: 'Virginia (UVA)',
		glyph: 'UVA',
		short: 'UVA',
		country: 'US',
		region: 'NA',
		domains: ['virginia.edu', 'darden.virginia.edu'],
		rank: 254,
		color: '#232D4B',
		text: '#E57200'
	},
	{
		id: 'uwisc',
		name: 'Wisconsin–Madison',
		glyph: 'WISC',
		short: 'WISC',
		country: 'US',
		region: 'NA',
		domains: ['wisc.edu'],
		rank: 89,
		color: '#C5050C',
		text: '#F2ECDC'
	},
	{
		id: 'uiuc',
		name: 'Illinois Urbana-Champaign',
		glyph: 'UIUC',
		short: 'UIUC',
		country: 'US',
		region: 'NA',
		domains: ['illinois.edu'],
		rank: 69,
		color: '#13294B',
		text: '#E84A27'
	},
	{
		id: 'osu',
		name: 'Ohio State',
		glyph: 'OSU',
		short: 'OSU',
		country: 'US',
		region: 'NA',
		domains: ['osu.edu'],
		rank: 152,
		color: '#BB0000',
		text: '#F2ECDC'
	},
	{
		id: 'psu',
		name: 'Penn State',
		glyph: 'PSU',
		short: 'PSU',
		country: 'US',
		region: 'NA',
		domains: ['psu.edu'],
		rank: 81,
		color: '#1E407C',
		text: '#F2ECDC'
	},
	{
		id: 'purdue',
		name: 'Purdue',
		glyph: 'PURD',
		short: 'PURD',
		country: 'US',
		region: 'NA',
		domains: ['purdue.edu'],
		rank: 91,
		color: '#CEB888',
		text: '#1A1A1A'
	},
	{
		id: 'wm',
		name: 'William & Mary',
		glyph: 'WM',
		short: 'WM',
		country: 'US',
		region: 'NA',
		domains: ['wm.edu', 'mason.wm.edu'],
		rank: 612,
		color: '#115740',
		text: '#F2ECDC'
	},
	{
		id: 'bc',
		name: 'Boston College',
		glyph: 'BC',
		short: 'BC',
		country: 'US',
		region: 'NA',
		domains: ['bc.edu'],
		rank: 282,
		color: '#8A100B',
		text: '#F2ECDC'
	},
	{
		id: 'tulane',
		name: 'Tulane',
		glyph: 'TULA',
		short: 'TULA',
		country: 'US',
		region: 'NA',
		domains: ['tulane.edu', 'freeman.tulane.edu'],
		rank: 487,
		color: '#418FDE',
		text: '#F2ECDC'
	},
	{
		id: 'lehigh',
		name: 'Lehigh',
		glyph: 'LEH',
		short: 'LEH',
		country: 'US',
		region: 'NA',
		domains: ['lehigh.edu'],
		rank: 480,
		color: '#522D80',
		text: '#F2ECDC'
	},
	{
		id: 'rpi',
		name: 'Rensselaer',
		glyph: 'RPI',
		short: 'RPI',
		country: 'US',
		region: 'NA',
		domains: ['rpi.edu'],
		rank: 391,
		color: '#D6001C',
		text: '#F2ECDC'
	},
	{
		id: 'uw',
		name: 'Washington (Seattle)',
		glyph: 'UW',
		short: 'UW',
		country: 'US',
		region: 'NA',
		domains: ['uw.edu', 'foster.uw.edu'],
		rank: 68,
		color: '#4B2E83',
		text: '#F2ECDC'
	},
	{
		id: 'ucsd',
		name: 'UC San Diego',
		glyph: 'UCSD',
		short: 'UCSD',
		country: 'US',
		region: 'NA',
		domains: ['ucsd.edu'],
		rank: 72,
		color: '#182B49',
		text: '#FFCD00'
	},
	{
		id: 'uci',
		name: 'UC Irvine',
		glyph: 'UCI',
		short: 'UCI',
		country: 'US',
		region: 'NA',
		domains: ['uci.edu', 'merage.uci.edu'],
		rank: 73,
		color: '#FFC72C',
		text: '#0064A4'
	},
	{
		id: 'ucsb',
		name: 'UC Santa Barbara',
		glyph: 'UCSB',
		short: 'UCSB',
		country: 'US',
		region: 'NA',
		domains: ['ucsb.edu'],
		rank: 144,
		color: '#003660',
		text: '#FEBC11'
	},
	{
		id: 'ucdavis',
		name: 'UC Davis',
		glyph: 'UCD',
		short: 'UCD',
		country: 'US',
		region: 'NA',
		domains: ['ucdavis.edu'],
		rank: 129,
		color: '#022851',
		text: '#FFBF00'
	},
	{
		id: 'bu',
		name: 'Boston University',
		glyph: 'BU',
		short: 'BU',
		country: 'US',
		region: 'NA',
		domains: ['bu.edu', 'questrom.bu.edu'],
		rank: 108,
		color: '#CC0000',
		text: '#F2ECDC'
	},
	{
		id: 'umn',
		name: 'Minnesota (Twin Cities)',
		glyph: 'UMN',
		short: 'UMN',
		country: 'US',
		region: 'NA',
		domains: ['umn.edu', 'carlsonschool.umn.edu'],
		rank: 117,
		color: '#7A0019',
		text: '#FFCC33'
	},
	{
		id: 'asu',
		name: 'Arizona State',
		glyph: 'ASU',
		short: 'ASU',
		country: 'US',
		region: 'NA',
		domains: ['asu.edu'],
		rank: 199,
		color: '#8C1D40',
		text: '#FFC627'
	},
	{
		id: 'uf',
		name: 'Florida',
		glyph: 'UF',
		short: 'UF',
		country: 'US',
		region: 'NA',
		domains: ['ufl.edu', 'warrington.ufl.edu'],
		rank: 122,
		color: '#0021A5',
		text: '#FA4616'
	},
	{
		id: 'uconn',
		name: 'Connecticut',
		glyph: 'UCON',
		short: 'UCON',
		country: 'US',
		region: 'NA',
		domains: ['uconn.edu'],
		rank: 356,
		color: '#000E2F',
		text: '#F2ECDC'
	},
	{
		id: 'miami',
		name: 'Miami',
		glyph: 'MIA',
		short: 'MIA',
		country: 'US',
		region: 'NA',
		domains: ['miami.edu', 'bus.miami.edu'],
		rank: 264,
		color: '#F47321',
		text: '#005030'
	},
	{
		id: 'rutgers',
		name: 'Rutgers',
		glyph: 'RUT',
		short: 'RUT',
		country: 'US',
		region: 'NA',
		domains: ['rutgers.edu', 'business.rutgers.edu'],
		rank: 234,
		color: '#CC0033',
		text: '#F2ECDC'
	},
	{
		id: 'vt',
		name: 'Virginia Tech',
		glyph: 'VT',
		short: 'VT',
		country: 'US',
		region: 'NA',
		domains: ['vt.edu'],
		rank: 281,
		color: '#861F41',
		text: '#E5751F'
	},
	{
		id: 'rochester',
		name: 'Rochester',
		glyph: 'ROCH',
		short: 'ROCH',
		country: 'US',
		region: 'NA',
		domains: ['rochester.edu', 'simon.rochester.edu'],
		rank: 161,
		color: '#003B71',
		text: '#FFD100'
	},
	{
		id: 'northeastern',
		name: 'Northeastern',
		glyph: 'NEU',
		short: 'NEU',
		country: 'US',
		region: 'NA',
		domains: ['northeastern.edu', 'damore-mckim.northeastern.edu'],
		rank: 53,
		color: '#C8102E',
		text: '#F2ECDC'
	},
	{
		id: 'case',
		name: 'Case Western Reserve',
		glyph: 'CWRU',
		short: 'CWRU',
		country: 'US',
		region: 'NA',
		domains: ['case.edu', 'weatherhead.case.edu'],
		rank: 184,
		color: '#0A304E',
		text: '#F2ECDC'
	},
	{
		id: 'uri',
		name: 'Rhode Island',
		glyph: 'URI',
		short: 'URI',
		country: 'US',
		region: 'NA',
		domains: ['uri.edu'],
		rank: 624,
		color: '#002147',
		text: '#F2ECDC'
	},
	{
		id: 'uga',
		name: 'Georgia',
		glyph: 'UGA',
		short: 'UGA',
		country: 'US',
		region: 'NA',
		domains: ['uga.edu', 'terry.uga.edu'],
		rank: 451,
		color: '#BA0C2F',
		text: '#000000'
	},
	{
		id: 'iowa',
		name: 'Iowa',
		glyph: 'UIOW',
		short: 'UIOW',
		country: 'US',
		region: 'NA',
		domains: ['uiowa.edu', 'tippie.uiowa.edu'],
		rank: 401,
		color: '#FFCD00',
		text: '#000000'
	},
	{
		id: 'su',
		name: 'Syracuse',
		glyph: 'SU',
		short: 'SU',
		country: 'US',
		region: 'NA',
		domains: ['syr.edu', 'whitman.syr.edu'],
		rank: 559,
		color: '#F76900',
		text: '#000E54'
	},
	{
		id: 'drexel',
		name: 'Drexel',
		glyph: 'DREX',
		short: 'DREX',
		country: 'US',
		region: 'NA',
		domains: ['drexel.edu', 'lebow.drexel.edu'],
		rank: 391,
		color: '#07294D',
		text: '#FFC600'
	},
	{
		id: 'uic',
		name: 'Illinois Chicago',
		glyph: 'UIC',
		short: 'UIC',
		country: 'US',
		region: 'NA',
		domains: ['uic.edu', 'liautaud.uic.edu'],
		rank: 252,
		color: '#001E62',
		text: '#D50032'
	},
	{
		id: 'pitt',
		name: 'Pittsburgh',
		glyph: 'PITT',
		short: 'PITT',
		country: 'US',
		region: 'NA',
		domains: ['pitt.edu', 'katz.pitt.edu'],
		rank: 168,
		color: '#003594',
		text: '#FFB81C'
	},
	{
		id: 'msu',
		name: 'Michigan State',
		glyph: 'MSU',
		short: 'MSU',
		country: 'US',
		region: 'NA',
		domains: ['msu.edu', 'broad.msu.edu'],
		rank: 113,
		color: '#18453B',
		text: '#F2ECDC'
	},
	{
		id: 'uoregon',
		name: 'Oregon',
		glyph: 'UO',
		short: 'UO',
		country: 'US',
		region: 'NA',
		domains: ['uoregon.edu', 'lcb.uoregon.edu'],
		rank: 333,
		color: '#154733',
		text: '#FEE123'
	},
	{
		id: 'villanova',
		name: 'Villanova',
		glyph: 'NOVA',
		short: 'NOVA',
		country: 'US',
		region: 'NA',
		domains: ['villanova.edu'],
		rank: 705,
		color: '#003366',
		text: '#F2ECDC'
	},
	{
		id: 'cu',
		name: 'Colorado Boulder',
		glyph: 'CU',
		short: 'CU',
		country: 'US',
		region: 'NA',
		domains: ['colorado.edu', 'leeds.colorado.edu'],
		rank: 199,
		color: '#CFB87C',
		text: '#000000'
	},
	{
		id: 'utah',
		name: 'Utah',
		glyph: 'UTAH',
		short: 'UTAH',
		country: 'US',
		region: 'NA',
		domains: ['utah.edu', 'eccles.utah.edu'],
		rank: 281,
		color: '#CC0000',
		text: '#F2ECDC'
	},
	{
		id: 'umass',
		name: 'UMass Amherst',
		glyph: 'UMAS',
		short: 'UMAS',
		country: 'US',
		region: 'NA',
		domains: ['umass.edu', 'isenberg.umass.edu'],
		rank: 232,
		color: '#881C1C',
		text: '#F2ECDC'
	},
	{
		id: 'texasam',
		name: 'Texas A&M',
		glyph: 'TAMU',
		short: 'TAMU',
		country: 'US',
		region: 'NA',
		domains: ['tamu.edu', 'mays.tamu.edu'],
		rank: 154,
		color: '#500000',
		text: '#F2ECDC'
	},
	{
		id: 'uok',
		name: 'Oklahoma',
		glyph: 'OU',
		short: 'OU',
		country: 'US',
		region: 'NA',
		domains: ['ou.edu', 'price.ou.edu'],
		rank: 447,
		color: '#841617',
		text: '#F2ECDC'
	},
	{
		id: 'clemson',
		name: 'Clemson',
		glyph: 'CLEM',
		short: 'CLEM',
		country: 'US',
		region: 'NA',
		domains: ['clemson.edu'],
		rank: 701,
		color: '#F66733',
		text: '#522D80'
	},
	{
		id: 'babson',
		name: 'Babson College',
		glyph: 'BABS',
		short: 'BABS',
		country: 'US',
		region: 'NA',
		domains: ['babson.edu'],
		rank: 581,
		color: '#00482B',
		text: '#F2ECDC'
	},
	{
		id: 'bentley',
		name: 'Bentley',
		glyph: 'BENT',
		short: 'BENT',
		country: 'US',
		region: 'NA',
		domains: ['bentley.edu'],
		rank: 801,
		color: '#0033A0',
		text: '#F2ECDC'
	},
	{
		id: 'claremont',
		name: 'Claremont McKenna',
		glyph: 'CMC',
		short: 'CMC',
		country: 'US',
		region: 'NA',
		domains: ['cmc.edu'],
		rank: 481,
		color: '#871719',
		text: '#F2ECDC'
	},
	{
		id: 'hmc',
		name: 'Harvey Mudd',
		glyph: 'HMC',
		short: 'HMC',
		country: 'US',
		region: 'NA',
		domains: ['hmc.edu'],
		rank: 491,
		color: '#000000',
		text: '#F2ECDC'
	},
	{
		id: 'wellesley',
		name: 'Wellesley',
		glyph: 'WELS',
		short: 'WELS',
		country: 'US',
		region: 'NA',
		domains: ['wellesley.edu'],
		rank: 451,
		color: '#1F3A93',
		text: '#F2ECDC'
	},
	{
		id: 'amherst',
		name: 'Amherst',
		glyph: 'AMH',
		short: 'AMH',
		country: 'US',
		region: 'NA',
		domains: ['amherst.edu'],
		rank: 451,
		color: '#3F1F69',
		text: '#FFFFFF'
	},
	{
		id: 'williams',
		name: 'Williams',
		glyph: 'WMS',
		short: 'WMS',
		country: 'US',
		region: 'NA',
		domains: ['williams.edu'],
		rank: 431,
		color: '#500082',
		text: '#FFBE0A'
	},
	// United Kingdom
	{
		id: 'oxford',
		name: 'Oxford',
		glyph: 'OXF',
		short: 'OXF',
		country: 'GB',
		region: 'UK',
		domains: ['ox.ac.uk', 'sbs.ox.ac.uk'],
		rank: 3,
		color: '#002147',
		text: '#F2ECDC'
	},
	{
		id: 'cambridge',
		name: 'Cambridge',
		glyph: 'CAM',
		short: 'CAM',
		country: 'GB',
		region: 'UK',
		domains: ['cam.ac.uk', 'jbs.cam.ac.uk'],
		rank: 5,
		color: '#A3C1AD',
		text: '#1A1A1A'
	},
	{
		id: 'imperial',
		name: 'Imperial College London',
		glyph: 'IC',
		short: 'IC',
		country: 'GB',
		region: 'UK',
		domains: ['imperial.ac.uk', 'imperial.edu'],
		rank: 6,
		color: '#003E74',
		text: '#F2ECDC'
	},
	{
		id: 'lse',
		name: 'LSE',
		glyph: 'LSE',
		short: 'LSE',
		country: 'GB',
		region: 'UK',
		domains: ['lse.ac.uk'],
		rank: 48,
		color: '#820D1F',
		text: '#F2ECDC'
	},
	{
		id: 'ucl',
		name: 'UCL',
		glyph: 'UCL',
		short: 'UCL',
		country: 'GB',
		region: 'UK',
		domains: ['ucl.ac.uk'],
		rank: 8,
		color: '#500778',
		text: '#F2ECDC'
	},
	{
		id: 'edinburgh',
		name: 'Edinburgh',
		glyph: 'EDIN',
		short: 'EDIN',
		country: 'GB',
		region: 'UK',
		domains: ['ed.ac.uk', 'business-school.ed.ac.uk'],
		rank: 25,
		color: '#041E42',
		text: '#F2ECDC'
	},
	{
		id: 'kings',
		name: "King's College London",
		glyph: 'KCL',
		short: 'KCL',
		country: 'GB',
		region: 'UK',
		domains: ['kcl.ac.uk'],
		rank: 40,
		color: '#E2231A',
		text: '#F2ECDC'
	},
	{
		id: 'warwick',
		name: 'Warwick',
		glyph: 'WARW',
		short: 'WARW',
		country: 'GB',
		region: 'UK',
		domains: ['warwick.ac.uk', 'wbs.ac.uk'],
		rank: 67,
		color: '#3C2052',
		text: '#F2ECDC'
	},
	{
		id: 'manchester',
		name: 'Manchester',
		glyph: 'MAN',
		short: 'MAN',
		country: 'GB',
		region: 'UK',
		domains: ['manchester.ac.uk', 'mbs.ac.uk'],
		rank: 53,
		color: '#FFBB1C',
		text: '#1A1A1A'
	},
	{
		id: 'bristol',
		name: 'Bristol',
		glyph: 'BRIS',
		short: 'BRIS',
		country: 'GB',
		region: 'UK',
		domains: ['bristol.ac.uk'],
		rank: 54,
		color: '#AB2328',
		text: '#F2ECDC'
	},
	{
		id: 'durham',
		name: 'Durham',
		glyph: 'DUR',
		short: 'DUR',
		country: 'GB',
		region: 'UK',
		domains: ['durham.ac.uk'],
		rank: 81,
		color: '#68246D',
		text: '#F2ECDC'
	},
	{
		id: 'standrews',
		name: 'St Andrews',
		glyph: 'STA',
		short: 'STA',
		country: 'GB',
		region: 'UK',
		domains: ['st-andrews.ac.uk'],
		rank: 100,
		color: '#0036A0',
		text: '#F2ECDC'
	},
	{
		id: 'glasgow',
		name: 'Glasgow',
		glyph: 'GLA',
		short: 'GLA',
		country: 'GB',
		region: 'UK',
		domains: ['glasgow.ac.uk'],
		rank: 76,
		color: '#003865',
		text: '#F2ECDC'
	},
	{
		id: 'lbs',
		name: 'London Business School',
		glyph: 'LBS',
		short: 'LBS',
		country: 'GB',
		region: 'UK',
		domains: ['london.edu'],
		color: '#181818',
		text: '#F2ECDC'
	},
	{
		id: 'leeds',
		name: 'Leeds',
		glyph: 'LDS',
		short: 'LDS',
		country: 'GB',
		region: 'UK',
		domains: ['leeds.ac.uk'],
		rank: 82,
		color: '#2A6FBA',
		text: '#F2ECDC'
	},
	{
		id: 'birmingham',
		name: 'Birmingham',
		glyph: 'BHAM',
		short: 'BHAM',
		country: 'GB',
		region: 'UK',
		domains: ['bham.ac.uk'],
		rank: 80,
		color: '#00205B',
		text: '#FFCC00'
	},
	{
		id: 'southampton',
		name: 'Southampton',
		glyph: 'SOTN',
		short: 'SOTN',
		country: 'GB',
		region: 'UK',
		domains: ['soton.ac.uk'],
		rank: 80,
		color: '#005C84',
		text: '#F2ECDC'
	},
	{
		id: 'nottingham',
		name: 'Nottingham',
		glyph: 'NOTT',
		short: 'NOTT',
		country: 'GB',
		region: 'UK',
		domains: ['nottingham.ac.uk'],
		rank: 108,
		color: '#003F66',
		text: '#F2ECDC'
	},
	{
		id: 'sheffield',
		name: 'Sheffield',
		glyph: 'SHEF',
		short: 'SHEF',
		country: 'GB',
		region: 'UK',
		domains: ['sheffield.ac.uk'],
		rank: 105,
		color: '#1295D8',
		text: '#F2ECDC'
	},
	{
		id: 'queenmary',
		name: 'Queen Mary',
		glyph: 'QMUL',
		short: 'QMUL',
		country: 'GB',
		region: 'UK',
		domains: ['qmul.ac.uk'],
		rank: 125,
		color: '#0078D7',
		text: '#F2ECDC'
	},
	{
		id: 'cardiff',
		name: 'Cardiff',
		glyph: 'CARD',
		short: 'CARD',
		country: 'GB',
		region: 'UK',
		domains: ['cardiff.ac.uk'],
		rank: 186,
		color: '#E32726',
		text: '#F2ECDC'
	},
	{
		id: 'lancaster',
		name: 'Lancaster',
		glyph: 'LANC',
		short: 'LANC',
		country: 'GB',
		region: 'UK',
		domains: ['lancaster.ac.uk'],
		rank: 179,
		color: '#B40F4D',
		text: '#F2ECDC'
	},
	{
		id: 'exeter',
		name: 'Exeter',
		glyph: 'EXE',
		short: 'EXE',
		country: 'GB',
		region: 'UK',
		domains: ['exeter.ac.uk'],
		rank: 169,
		color: '#022851',
		text: '#F2ECDC'
	},
	{
		id: 'bath',
		name: 'Bath',
		glyph: 'BATH',
		short: 'BATH',
		country: 'GB',
		region: 'UK',
		domains: ['bath.ac.uk'],
		rank: 150,
		color: '#B12C2C',
		text: '#F2ECDC'
	},
	{
		id: 'hull',
		name: 'Hull',
		glyph: 'HULL',
		short: 'HULL',
		country: 'GB',
		region: 'UK',
		domains: ['hull.ac.uk'],
		rank: 480,
		color: '#000000',
		text: '#FFD100'
	},
	// Europe
	{
		id: 'whu',
		name: 'WHU – Otto Beisheim School of Management',
		glyph: 'WHU',
		short: 'WHU',
		country: 'DE',
		region: 'EU',
		domains: ['whu.edu'],
		color: '#003978',
		text: '#E2B842'
	},
	{
		id: 'eth',
		name: 'ETH Zürich',
		glyph: 'ETH',
		short: 'ETH',
		country: 'CH',
		region: 'EU',
		domains: ['ethz.ch'],
		rank: 7,
		color: '#215CAF',
		text: '#F2ECDC'
	},
	{
		id: 'epfl',
		name: 'EPFL',
		glyph: 'EPFL',
		short: 'EPFL',
		country: 'CH',
		region: 'EU',
		domains: ['epfl.ch'],
		rank: 26,
		color: '#FF0000',
		text: '#F2ECDC'
	},
	{
		id: 'tum',
		name: 'TU Munich',
		glyph: 'TUM',
		short: 'TUM',
		country: 'DE',
		region: 'EU',
		domains: ['tum.de'],
		rank: 28,
		color: '#3070B3',
		text: '#F2ECDC'
	},
	{
		id: 'lmu',
		name: 'LMU Munich',
		glyph: 'LMU',
		short: 'LMU',
		country: 'DE',
		region: 'EU',
		domains: ['lmu.de', 'campus.lmu.de'],
		rank: 59,
		color: '#00883A',
		text: '#F2ECDC'
	},
	{
		id: 'humboldt',
		name: 'Humboldt Berlin',
		glyph: 'HUM',
		short: 'HUM',
		country: 'DE',
		region: 'EU',
		domains: ['hu-berlin.de'],
		rank: 120,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'fu-berlin',
		name: 'Freie Universität Berlin',
		glyph: 'FUB',
		short: 'FUB',
		country: 'DE',
		region: 'EU',
		domains: ['fu-berlin.de'],
		rank: 98,
		color: '#990000',
		text: '#F2ECDC'
	},
	{
		id: 'heidelberg',
		name: 'Heidelberg',
		glyph: 'HEID',
		short: 'HEID',
		country: 'DE',
		region: 'EU',
		domains: ['uni-heidelberg.de'],
		rank: 84,
		color: '#A8133A',
		text: '#F2ECDC'
	},
	{
		id: 'rwth',
		name: 'RWTH Aachen',
		glyph: 'RWTH',
		short: 'RWTH',
		country: 'DE',
		region: 'EU',
		domains: ['rwth-aachen.de'],
		rank: 99,
		color: '#00549F',
		text: '#F2ECDC'
	},
	{
		id: 'mannheim',
		name: 'Mannheim',
		glyph: 'MHM',
		short: 'MHM',
		country: 'DE',
		region: 'EU',
		domains: ['uni-mannheim.de'],
		rank: 229,
		color: '#7F2B33',
		text: '#F2ECDC'
	},
	{
		id: 'frankfurt',
		name: 'Frankfurt (Goethe)',
		glyph: 'GU',
		short: 'GU',
		country: 'DE',
		region: 'EU',
		domains: ['uni-frankfurt.de'],
		rank: 348,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'koeln',
		name: 'Cologne (Köln)',
		glyph: 'KOLN',
		short: 'KOLN',
		country: 'DE',
		region: 'EU',
		domains: ['uni-koeln.de'],
		rank: 329,
		color: '#9B2E3D',
		text: '#F2ECDC'
	},
	{
		id: 'bonn',
		name: 'Bonn',
		glyph: 'BONN',
		short: 'BONN',
		country: 'DE',
		region: 'EU',
		domains: ['uni-bonn.de'],
		rank: 239,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'hsg',
		name: 'St. Gallen (HSG)',
		glyph: 'HSG',
		short: 'HSG',
		country: 'CH',
		region: 'EU',
		domains: ['unisg.ch', 'student.unisg.ch'],
		color: '#006334',
		text: '#F2ECDC'
	},
	{
		id: 'uzh',
		name: 'Zürich',
		glyph: 'UZH',
		short: 'UZH',
		country: 'CH',
		region: 'EU',
		domains: ['uzh.ch'],
		rank: 91,
		color: '#0028A5',
		text: '#F2ECDC'
	},
	{
		id: 'ebs',
		name: 'EBS Oestrich-Winkel',
		glyph: 'EBS',
		short: 'EBS',
		country: 'DE',
		region: 'EU',
		domains: ['ebs.edu'],
		color: '#003E7E',
		text: '#F2ECDC'
	},
	{
		id: 'hhl',
		name: 'HHL Leipzig',
		glyph: 'HHL',
		short: 'HHL',
		country: 'DE',
		region: 'EU',
		domains: ['hhl.de'],
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'esmt',
		name: 'ESMT Berlin',
		glyph: 'ESMT',
		short: 'ESMT',
		country: 'DE',
		region: 'EU',
		domains: ['esmt.org'],
		color: '#E2231A',
		text: '#F2ECDC'
	},
	{
		id: 'sorbonne',
		name: 'Sorbonne',
		glyph: 'SORB',
		short: 'SORB',
		country: 'FR',
		region: 'EU',
		domains: ['sorbonne-universite.fr'],
		rank: 74,
		color: '#003C82',
		text: '#F2ECDC'
	},
	{
		id: 'sciencespo',
		name: 'Sciences Po',
		glyph: 'SCPO',
		short: 'SCPO',
		country: 'FR',
		region: 'EU',
		domains: ['sciencespo.fr'],
		rank: 284,
		color: '#FF4F00',
		text: '#F2ECDC'
	},
	{
		id: 'ens',
		name: 'ENS Paris',
		glyph: 'ENS',
		short: 'ENS',
		country: 'FR',
		region: 'EU',
		domains: ['ens.psl.eu', 'ens.fr'],
		rank: 33,
		color: '#841B2D',
		text: '#F2ECDC'
	},
	{
		id: 'insead',
		name: 'INSEAD',
		glyph: 'INSD',
		short: 'INSD',
		country: 'FR',
		region: 'EU',
		domains: ['insead.edu'],
		color: '#00263A',
		text: '#F2ECDC'
	},
	{
		id: 'hec',
		name: 'HEC Paris',
		glyph: 'HEC',
		short: 'HEC',
		country: 'FR',
		region: 'EU',
		domains: ['hec.edu'],
		color: '#00205B',
		text: '#F2ECDC'
	},
	{
		id: 'essec',
		name: 'ESSEC',
		glyph: 'ESSE',
		short: 'ESSE',
		country: 'FR',
		region: 'EU',
		domains: ['essec.edu'],
		color: '#001E62',
		text: '#F2ECDC'
	},
	{
		id: 'escp',
		name: 'ESCP',
		glyph: 'ESCP',
		short: 'ESCP',
		country: 'FR',
		region: 'EU',
		domains: ['escp.eu'],
		color: '#1B365D',
		text: '#F2ECDC'
	},
	{
		id: 'emlyon',
		name: 'emlyon',
		glyph: 'EMLY',
		short: 'EMLY',
		country: 'FR',
		region: 'EU',
		domains: ['em-lyon.com', 'emlyon.com'],
		color: '#E2231A',
		text: '#F2ECDC'
	},
	{
		id: 'paris-dauphine',
		name: 'Paris Dauphine',
		glyph: 'DAUP',
		short: 'DAUP',
		country: 'FR',
		region: 'EU',
		domains: ['dauphine.psl.eu', 'dauphine.fr'],
		rank: 351,
		color: '#002257',
		text: '#F2ECDC'
	},
	{
		id: 'polytechnique',
		name: 'École Polytechnique',
		glyph: 'X',
		short: 'X',
		country: 'FR',
		region: 'EU',
		domains: ['polytechnique.edu'],
		rank: 40,
		color: '#F2A900',
		text: '#1A1A1A'
	},
	{
		id: 'bocconi',
		name: 'Bocconi',
		glyph: 'BOCC',
		short: 'BOCC',
		country: 'IT',
		region: 'EU',
		domains: ['unibocconi.it'],
		rank: 133,
		color: '#003299',
		text: '#F2ECDC'
	},
	{
		id: 'polimi',
		name: 'Politecnico di Milano',
		glyph: 'PoMI',
		short: 'PoMI',
		country: 'IT',
		region: 'EU',
		domains: ['polimi.it'],
		rank: 111,
		color: '#000000',
		text: '#F2ECDC'
	},
	{
		id: 'sapienza',
		name: 'Sapienza Roma',
		glyph: 'SAP',
		short: 'SAP',
		country: 'IT',
		region: 'EU',
		domains: ['uniroma1.it'],
		rank: 132,
		color: '#820B17',
		text: '#F2ECDC'
	},
	{
		id: 'iese',
		name: 'IESE',
		glyph: 'IESE',
		short: 'IESE',
		country: 'ES',
		region: 'EU',
		domains: ['iese.edu', 'iese.net'],
		color: '#003594',
		text: '#F2ECDC'
	},
	{
		id: 'iebusiness',
		name: 'IE Business School',
		glyph: 'IE',
		short: 'IE',
		country: 'ES',
		region: 'EU',
		domains: ['ie.edu', 'student.ie.edu'],
		color: '#CC0033',
		text: '#F2ECDC'
	},
	{
		id: 'esade',
		name: 'ESADE',
		glyph: 'ESAD',
		short: 'ESAD',
		country: 'ES',
		region: 'EU',
		domains: ['esade.edu'],
		color: '#005CB9',
		text: '#F2ECDC'
	},
	{
		id: 'barcelona',
		name: 'Barcelona (UB)',
		glyph: 'UB',
		short: 'UB',
		country: 'ES',
		region: 'EU',
		domains: ['ub.edu'],
		rank: 168,
		color: '#A50034',
		text: '#F2ECDC'
	},
	{
		id: 'uam',
		name: 'Madrid Autónoma',
		glyph: 'UAM',
		short: 'UAM',
		country: 'ES',
		region: 'EU',
		domains: ['uam.es'],
		rank: 201,
		color: '#000000',
		text: '#F2ECDC'
	},
	{
		id: 'uc3m',
		name: 'Carlos III Madrid',
		glyph: 'UC3M',
		short: 'UC3M',
		country: 'ES',
		region: 'EU',
		domains: ['uc3m.es'],
		rank: 311,
		color: '#000F46',
		text: '#F2ECDC'
	},
	{
		id: 'tudelft',
		name: 'TU Delft',
		glyph: 'TUD',
		short: 'TUD',
		country: 'NL',
		region: 'EU',
		domains: ['tudelft.nl'],
		rank: 47,
		color: '#00A6D6',
		text: '#F2ECDC'
	},
	{
		id: 'utrecht',
		name: 'Utrecht',
		glyph: 'UTR',
		short: 'UTR',
		country: 'NL',
		region: 'EU',
		domains: ['uu.nl', 'students.uu.nl'],
		rank: 107,
		color: '#FFCD00',
		text: '#1A1A1A'
	},
	{
		id: 'leiden',
		name: 'Leiden',
		glyph: 'LEI',
		short: 'LEI',
		country: 'NL',
		region: 'EU',
		domains: ['leidenuniv.nl', 'universiteitleiden.nl'],
		rank: 119,
		color: '#001158',
		text: '#F2ECDC'
	},
	{
		id: 'amsterdam',
		name: 'Amsterdam (UvA)',
		glyph: 'UVA',
		short: 'UVA',
		country: 'NL',
		region: 'EU',
		domains: ['uva.nl', 'student.uva.nl'],
		rank: 60,
		color: '#B5121B',
		text: '#F2ECDC'
	},
	{
		id: 'rsm',
		name: 'Rotterdam (RSM)',
		glyph: 'RSM',
		short: 'RSM',
		country: 'NL',
		region: 'EU',
		domains: ['rsm.nl', 'eur.nl'],
		rank: 172,
		color: '#003D7E',
		text: '#F2ECDC'
	},
	{
		id: 'vu',
		name: 'VU Amsterdam',
		glyph: 'VU',
		short: 'VU',
		country: 'NL',
		region: 'EU',
		domains: ['vu.nl'],
		rank: 148,
		color: '#0077B3',
		text: '#F2ECDC'
	},
	{
		id: 'groningen',
		name: 'Groningen',
		glyph: 'RUG',
		short: 'RUG',
		country: 'NL',
		region: 'EU',
		domains: ['rug.nl'],
		rank: 139,
		color: '#E2001A',
		text: '#F2ECDC'
	},
	{
		id: 'eindhoven',
		name: 'TU Eindhoven',
		glyph: 'TUE',
		short: 'TUE',
		country: 'NL',
		region: 'EU',
		domains: ['tue.nl'],
		rank: 124,
		color: '#E2001A',
		text: '#F2ECDC'
	},
	{
		id: 'kuleuven',
		name: 'KU Leuven',
		glyph: 'KUL',
		short: 'KUL',
		country: 'BE',
		region: 'EU',
		domains: ['kuleuven.be'],
		rank: 61,
		color: '#1D3D6F',
		text: '#F2ECDC'
	},
	{
		id: 'ulb',
		name: 'Université Libre de Bruxelles',
		glyph: 'ULB',
		short: 'ULB',
		country: 'BE',
		region: 'EU',
		domains: ['ulb.be'],
		rank: 205,
		color: '#E2001A',
		text: '#F2ECDC'
	},
	{
		id: 'ghent',
		name: 'Ghent',
		glyph: 'UGE',
		short: 'UGE',
		country: 'BE',
		region: 'EU',
		domains: ['ugent.be'],
		rank: 149,
		color: '#1E64C8',
		text: '#F2ECDC'
	},
	{
		id: 'copenhagen',
		name: 'Copenhagen',
		glyph: 'COP',
		short: 'COP',
		country: 'DK',
		region: 'EU',
		domains: ['ku.dk'],
		rank: 100,
		color: '#901A1E',
		text: '#F2ECDC'
	},
	{
		id: 'cbs',
		name: 'Copenhagen Business School',
		glyph: 'CBS',
		short: 'CBS',
		country: 'DK',
		region: 'EU',
		domains: ['cbs.dk', 'student.cbs.dk'],
		color: '#005A9C',
		text: '#F2ECDC'
	},
	{
		id: 'aarhus',
		name: 'Aarhus',
		glyph: 'AU',
		short: 'AU',
		country: 'DK',
		region: 'EU',
		domains: ['au.dk'],
		rank: 145,
		color: '#003D6B',
		text: '#F2ECDC'
	},
	{
		id: 'dtu',
		name: 'Technical Univ of Denmark',
		glyph: 'DTU',
		short: 'DTU',
		country: 'DK',
		region: 'EU',
		domains: ['dtu.dk'],
		rank: 121,
		color: '#990000',
		text: '#F2ECDC'
	},
	{
		id: 'karolinska',
		name: 'Karolinska Institutet',
		glyph: 'KARO',
		short: 'KARO',
		country: 'SE',
		region: 'EU',
		domains: ['ki.se', 'student.ki.se'],
		rank: 125,
		color: '#005F71',
		text: '#F2ECDC'
	},
	{
		id: 'lund',
		name: 'Lund',
		glyph: 'LUND',
		short: 'LUND',
		country: 'SE',
		region: 'EU',
		domains: ['lu.se', 'student.lu.se'],
		rank: 75,
		color: '#9D2235',
		text: '#F2ECDC'
	},
	{
		id: 'uppsala',
		name: 'Uppsala',
		glyph: 'UU',
		short: 'UU',
		country: 'SE',
		region: 'EU',
		domains: ['uu.se', 'student.uu.se'],
		rank: 124,
		color: '#990033',
		text: '#F2ECDC'
	},
	{
		id: 'sse',
		name: 'Stockholm School of Economics',
		glyph: 'SSE',
		short: 'SSE',
		country: 'SE',
		region: 'EU',
		domains: ['hhs.se', 'student.hhs.se'],
		color: '#1F3A93',
		text: '#F2ECDC'
	},
	{
		id: 'kth',
		name: 'KTH Stockholm',
		glyph: 'KTH',
		short: 'KTH',
		country: 'SE',
		region: 'EU',
		domains: ['kth.se'],
		rank: 73,
		color: '#1954A6',
		text: '#F2ECDC'
	},
	{
		id: 'helsinki',
		name: 'Helsinki',
		glyph: 'HEL',
		short: 'HEL',
		country: 'FI',
		region: 'EU',
		domains: ['helsinki.fi', 'student.helsinki.fi'],
		rank: 115,
		color: '#107EB0',
		text: '#F2ECDC'
	},
	{
		id: 'aalto',
		name: 'Aalto',
		glyph: 'AAL',
		short: 'AAL',
		country: 'FI',
		region: 'EU',
		domains: ['aalto.fi', 'student.aalto.fi'],
		rank: 110,
		color: '#000000',
		text: '#F2ECDC'
	},
	{
		id: 'oslo',
		name: 'Oslo',
		glyph: 'OSL',
		short: 'OSL',
		country: 'NO',
		region: 'EU',
		domains: ['uio.no', 'student.uio.no'],
		rank: 102,
		color: '#2B4A9D',
		text: '#F2ECDC'
	},
	{
		id: 'nhh',
		name: 'NHH Bergen',
		glyph: 'NHH',
		short: 'NHH',
		country: 'NO',
		region: 'EU',
		domains: ['nhh.no', 'student.nhh.no'],
		color: '#003366',
		text: '#F2ECDC'
	},
	{
		id: 'vienna',
		name: 'Vienna (Universität Wien)',
		glyph: 'UWIE',
		short: 'UWIE',
		country: 'AT',
		region: 'EU',
		domains: ['univie.ac.at', 'unet.univie.ac.at'],
		rank: 137,
		color: '#0063A6',
		text: '#F2ECDC'
	},
	{
		id: 'wu-vienna',
		name: 'WU Vienna',
		glyph: 'WU',
		short: 'WU',
		country: 'AT',
		region: 'EU',
		domains: ['wu.ac.at', 's.wu.ac.at'],
		rank: 356,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'trinity',
		name: 'Trinity College Dublin',
		glyph: 'TCD',
		short: 'TCD',
		country: 'IE',
		region: 'EU',
		domains: ['tcd.ie'],
		rank: 87,
		color: '#0E4D92',
		text: '#F2ECDC'
	},
	{
		id: 'ucd',
		name: 'UCD Dublin',
		glyph: 'UCD',
		short: 'UCD',
		country: 'IE',
		region: 'EU',
		domains: ['ucd.ie'],
		rank: 126,
		color: '#005AA0',
		text: '#F2ECDC'
	},
	{
		id: 'lisbon',
		name: 'Lisbon (ULisboa)',
		glyph: 'ULIS',
		short: 'ULIS',
		country: 'PT',
		region: 'EU',
		domains: ['ulisboa.pt'],
		rank: 275,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'nova-sbe',
		name: 'Nova SBE',
		glyph: 'NSBE',
		short: 'NSBE',
		country: 'PT',
		region: 'EU',
		domains: ['novasbe.pt', 'novasbe.unl.pt'],
		color: '#00347A',
		text: '#F2ECDC'
	},
	{
		id: 'warsaw',
		name: 'Warsaw',
		glyph: 'UW-W',
		short: 'UW-W',
		country: 'PL',
		region: 'EU',
		domains: ['uw.edu.pl'],
		rank: 262,
		color: '#80003F',
		text: '#F2ECDC'
	},
	{
		id: 'charles',
		name: 'Charles University Prague',
		glyph: 'CUNI',
		short: 'CUNI',
		country: 'CZ',
		region: 'EU',
		domains: ['cuni.cz'],
		rank: 246,
		color: '#A8133A',
		text: '#F2ECDC'
	},
	{
		id: 'elte',
		name: 'Eötvös Loránd',
		glyph: 'ELTE',
		short: 'ELTE',
		country: 'HU',
		region: 'EU',
		domains: ['elte.hu', 'student.elte.hu'],
		rank: 558,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'athens',
		name: 'Athens (NKUA)',
		glyph: 'NKUA',
		short: 'NKUA',
		country: 'GR',
		region: 'EU',
		domains: ['uoa.gr'],
		rank: 494,
		color: '#003E7E',
		text: '#F2ECDC'
	},
	// Asia
	{
		id: 'tokyo',
		name: 'Tokyo',
		glyph: 'TOK',
		short: 'TOK',
		country: 'JP',
		region: 'AS',
		domains: ['u-tokyo.ac.jp', 'g.ecc.u-tokyo.ac.jp'],
		rank: 32,
		color: '#A21531',
		text: '#F2ECDC'
	},
	{
		id: 'kyoto',
		name: 'Kyoto',
		glyph: 'KYO',
		short: 'KYO',
		country: 'JP',
		region: 'AS',
		domains: ['kyoto-u.ac.jp', 'st.kyoto-u.ac.jp'],
		rank: 46,
		color: '#7B1F26',
		text: '#F2ECDC'
	},
	{
		id: 'osaka',
		name: 'Osaka',
		glyph: 'OSA',
		short: 'OSA',
		country: 'JP',
		region: 'AS',
		domains: ['osaka-u.ac.jp'],
		rank: 65,
		color: '#003F87',
		text: '#F2ECDC'
	},
	{
		id: 'tokyo-tech',
		name: 'Science Tokyo (Tokyo Tech)',
		glyph: 'SCT',
		short: 'SCT',
		country: 'JP',
		region: 'AS',
		domains: ['titech.ac.jp', 'isct.ac.jp'],
		rank: 84,
		color: '#1A2A5E',
		text: '#F2ECDC'
	},
	{
		id: 'keio',
		name: 'Keio',
		glyph: 'KEIO',
		short: 'KEIO',
		country: 'JP',
		region: 'AS',
		domains: ['keio.jp', 'keio.ac.jp'],
		rank: 188,
		color: '#003E92',
		text: '#F2ECDC'
	},
	{
		id: 'waseda',
		name: 'Waseda',
		glyph: 'WAS',
		short: 'WAS',
		country: 'JP',
		region: 'AS',
		domains: ['waseda.jp', 'aoni.waseda.jp'],
		rank: 181,
		color: '#882526',
		text: '#F2ECDC'
	},
	{
		id: 'tohoku',
		name: 'Tohoku',
		glyph: 'TOH',
		short: 'TOH',
		country: 'JP',
		region: 'AS',
		domains: ['tohoku.ac.jp', 'dc.tohoku.ac.jp'],
		rank: 110,
		color: '#5C0F0F',
		text: '#F2ECDC'
	},
	{
		id: 'hitotsubashi',
		name: 'Hitotsubashi',
		glyph: 'HTBS',
		short: 'HTBS',
		country: 'JP',
		region: 'AS',
		domains: ['hit-u.ac.jp'],
		rank: 420,
		color: '#003F87',
		text: '#F2ECDC'
	},
	{
		id: 'tsinghua',
		name: 'Tsinghua',
		glyph: 'THU',
		short: 'THU',
		country: 'CN',
		region: 'AS',
		domains: ['tsinghua.edu.cn', 'mails.tsinghua.edu.cn'],
		rank: 20,
		color: '#660874',
		text: '#F2ECDC'
	},
	{
		id: 'peking',
		name: 'Peking',
		glyph: 'PKU',
		short: 'PKU',
		country: 'CN',
		region: 'AS',
		domains: ['pku.edu.cn', 'stu.pku.edu.cn'],
		rank: 14,
		color: '#7B1A2E',
		text: '#F2ECDC'
	},
	{
		id: 'fudan',
		name: 'Fudan',
		glyph: 'FUD',
		short: 'FUD',
		country: 'CN',
		region: 'AS',
		domains: ['fudan.edu.cn', 'm.fudan.edu.cn'],
		rank: 39,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'sjtu',
		name: 'Shanghai Jiao Tong',
		glyph: 'SJTU',
		short: 'SJTU',
		country: 'CN',
		region: 'AS',
		domains: ['sjtu.edu.cn'],
		rank: 45,
		color: '#A8133A',
		text: '#F2ECDC'
	},
	{
		id: 'zju',
		name: 'Zhejiang',
		glyph: 'ZJU',
		short: 'ZJU',
		country: 'CN',
		region: 'AS',
		domains: ['zju.edu.cn'],
		rank: 47,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'ceibs',
		name: 'CEIBS',
		glyph: 'CEIB',
		short: 'CEIB',
		country: 'CN',
		region: 'AS',
		domains: ['ceibs.edu'],
		color: '#003A6F',
		text: '#F2ECDC'
	},
	{
		id: 'hku',
		name: 'HKU',
		glyph: 'HKU',
		short: 'HKU',
		country: 'HK',
		region: 'AS',
		domains: ['hku.hk', 'connect.hku.hk'],
		rank: 17,
		color: '#006847',
		text: '#F2ECDC'
	},
	{
		id: 'hkust',
		name: 'HKUST',
		glyph: 'HKUST',
		short: 'HKUST',
		country: 'HK',
		region: 'AS',
		domains: ['ust.hk', 'connect.ust.hk'],
		rank: 47,
		color: '#003366',
		text: '#F2ECDC'
	},
	{
		id: 'cuhk',
		name: 'CUHK',
		glyph: 'CUHK',
		short: 'CUHK',
		country: 'HK',
		region: 'AS',
		domains: ['cuhk.edu.hk', 'link.cuhk.edu.hk'],
		rank: 36,
		color: '#7B1F2A',
		text: '#F2ECDC'
	},
	{
		id: 'cityuhk',
		name: 'City University of Hong Kong',
		glyph: 'CITYU',
		short: 'CITYU',
		country: 'HK',
		region: 'AS',
		domains: ['cityu.edu.hk'],
		rank: 62,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'polyuhk',
		name: 'PolyU Hong Kong',
		glyph: 'POLY',
		short: 'POLY',
		country: 'HK',
		region: 'AS',
		domains: ['polyu.edu.hk', 'connect.polyu.hk'],
		rank: 57,
		color: '#9C1F25',
		text: '#F2ECDC'
	},
	{
		id: 'nus',
		name: 'NUS',
		glyph: 'NUS',
		short: 'NUS',
		country: 'SG',
		region: 'AS',
		domains: ['nus.edu.sg', 'u.nus.edu'],
		rank: 8,
		color: '#003D7C',
		text: '#EF7C00'
	},
	{
		id: 'ntu',
		name: 'NTU Singapore',
		glyph: 'NTU',
		short: 'NTU',
		country: 'SG',
		region: 'AS',
		domains: ['ntu.edu.sg', 'e.ntu.edu.sg'],
		rank: 15,
		color: '#003D7C',
		text: '#FFD200'
	},
	{
		id: 'smu-sg',
		name: 'SMU Singapore',
		glyph: 'SMU',
		short: 'SMU',
		country: 'SG',
		region: 'AS',
		domains: ['smu.edu.sg'],
		rank: 511,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'snu',
		name: 'Seoul National',
		glyph: 'SNU',
		short: 'SNU',
		country: 'KR',
		region: 'AS',
		domains: ['snu.ac.kr'],
		rank: 31,
		color: '#003876',
		text: '#F2ECDC'
	},
	{
		id: 'kaist',
		name: 'KAIST',
		glyph: 'KAI',
		short: 'KAI',
		country: 'KR',
		region: 'AS',
		domains: ['kaist.ac.kr'],
		rank: 53,
		color: '#004EA2',
		text: '#F2ECDC'
	},
	{
		id: 'yonsei',
		name: 'Yonsei',
		glyph: 'YON',
		short: 'YON',
		country: 'KR',
		region: 'AS',
		domains: ['yonsei.ac.kr'],
		rank: 56,
		color: '#00499D',
		text: '#F2ECDC'
	},
	{
		id: 'korea-u',
		name: 'Korea University',
		glyph: 'KU',
		short: 'KU',
		country: 'KR',
		region: 'AS',
		domains: ['korea.ac.kr'],
		rank: 67,
		color: '#9C1F25',
		text: '#F2ECDC'
	},
	{
		id: 'postech',
		name: 'POSTECH',
		glyph: 'POS',
		short: 'POS',
		country: 'KR',
		region: 'AS',
		domains: ['postech.ac.kr'],
		rank: 98,
		color: '#9C1F25',
		text: '#F2ECDC'
	},
	{
		id: 'iitb',
		name: 'IIT Bombay',
		glyph: 'IITB',
		short: 'IITB',
		country: 'IN',
		region: 'AS',
		domains: ['iitb.ac.in'],
		rank: 118,
		color: '#003F87',
		text: '#F2ECDC'
	},
	{
		id: 'iitd',
		name: 'IIT Delhi',
		glyph: 'IITD',
		short: 'IITD',
		country: 'IN',
		region: 'AS',
		domains: ['iitd.ac.in'],
		rank: 150,
		color: '#9C1D1D',
		text: '#F2ECDC'
	},
	{
		id: 'iitm',
		name: 'IIT Madras',
		glyph: 'IITM',
		short: 'IITM',
		country: 'IN',
		region: 'AS',
		domains: ['iitm.ac.in', 'smail.iitm.ac.in'],
		rank: 227,
		color: '#931e1f',
		text: '#F2ECDC'
	},
	{
		id: 'iitk',
		name: 'IIT Kanpur',
		glyph: 'IITK',
		short: 'IITK',
		country: 'IN',
		region: 'AS',
		domains: ['iitk.ac.in'],
		rank: 222,
		color: '#9C1D1D',
		text: '#F2ECDC'
	},
	{
		id: 'iitkgp',
		name: 'IIT Kharagpur',
		glyph: 'IITKG',
		short: 'IITKG',
		country: 'IN',
		region: 'AS',
		domains: ['iitkgp.ac.in'],
		rank: 222,
		color: '#A0522D',
		text: '#F2ECDC'
	},
	{
		id: 'iisc',
		name: 'IISc Bangalore',
		glyph: 'IISC',
		short: 'IISC',
		country: 'IN',
		region: 'AS',
		domains: ['iisc.ac.in'],
		rank: 219,
		color: '#0C2340',
		text: '#F2ECDC'
	},
	{
		id: 'iima',
		name: 'IIM Ahmedabad',
		glyph: 'IIMA',
		short: 'IIMA',
		country: 'IN',
		region: 'AS',
		domains: ['iima.ac.in'],
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'iimb',
		name: 'IIM Bangalore',
		glyph: 'IIMB',
		short: 'IIMB',
		country: 'IN',
		region: 'AS',
		domains: ['iimb.ac.in'],
		color: '#0A2A66',
		text: '#F2ECDC'
	},
	{
		id: 'iimc',
		name: 'IIM Calcutta',
		glyph: 'IIMC',
		short: 'IIMC',
		country: 'IN',
		region: 'AS',
		domains: ['iimcal.ac.in'],
		color: '#9C1F25',
		text: '#F2ECDC'
	},
	{
		id: 'isb',
		name: 'Indian School of Business',
		glyph: 'ISB',
		short: 'ISB',
		country: 'IN',
		region: 'AS',
		domains: ['isb.edu'],
		color: '#0A2A66',
		text: '#F2ECDC'
	},
	{
		id: 'delhi-u',
		name: 'Delhi University',
		glyph: 'DU',
		short: 'DU',
		country: 'IN',
		region: 'AS',
		domains: ['du.ac.in'],
		rank: 407,
		color: '#0033A0',
		text: '#F2ECDC'
	},
	{
		id: 'jnu',
		name: 'JNU New Delhi',
		glyph: 'JNU',
		short: 'JNU',
		country: 'IN',
		region: 'AS',
		domains: ['jnu.ac.in'],
		rank: 501,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'ntu-tw',
		name: 'NTU Taiwan',
		glyph: 'NTUT',
		short: 'NTUT',
		country: 'TW',
		region: 'AS',
		domains: ['ntu.edu.tw'],
		rank: 68,
		color: '#003F87',
		text: '#F2ECDC'
	},
	{
		id: 'nthu-tw',
		name: 'NTHU Taiwan',
		glyph: 'NTHU',
		short: 'NTHU',
		country: 'TW',
		region: 'AS',
		domains: ['nthu.edu.tw'],
		rank: 171,
		color: '#660874',
		text: '#F2ECDC'
	},
	{
		id: 'um',
		name: 'Universiti Malaya',
		glyph: 'UM',
		short: 'UM',
		country: 'MY',
		region: 'AS',
		domains: ['um.edu.my', 'siswa.um.edu.my'],
		rank: 60,
		color: '#003366',
		text: '#F2ECDC'
	},
	{
		id: 'chulalongkorn',
		name: 'Chulalongkorn',
		glyph: 'CHUL',
		short: 'CHUL',
		country: 'TH',
		region: 'AS',
		domains: ['chula.ac.th', 'student.chula.ac.th'],
		rank: 211,
		color: '#E92076',
		text: '#F2ECDC'
	},
	{
		id: 'mahidol',
		name: 'Mahidol',
		glyph: 'MAH',
		short: 'MAH',
		country: 'TH',
		region: 'AS',
		domains: ['mahidol.ac.th', 'student.mahidol.ac.th'],
		rank: 382,
		color: '#0033A0',
		text: '#F2ECDC'
	},
	{
		id: 'ui',
		name: 'Universitas Indonesia',
		glyph: 'UI',
		short: 'UI',
		country: 'ID',
		region: 'AS',
		domains: ['ui.ac.id'],
		rank: 206,
		color: '#FFD500',
		text: '#1A1A1A'
	},
	{
		id: 'ugm',
		name: 'Gadjah Mada',
		glyph: 'UGM',
		short: 'UGM',
		country: 'ID',
		region: 'AS',
		domains: ['ugm.ac.id', 'mail.ugm.ac.id'],
		rank: 263,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'itb',
		name: 'ITB Bandung',
		glyph: 'ITB',
		short: 'ITB',
		country: 'ID',
		region: 'AS',
		domains: ['itb.ac.id', 'students.itb.ac.id'],
		rank: 281,
		color: '#003366',
		text: '#F2ECDC'
	},
	{
		id: 'updiliman',
		name: 'UP Diliman',
		glyph: 'UP',
		short: 'UP',
		country: 'PH',
		region: 'AS',
		domains: ['up.edu.ph'],
		rank: 411,
		color: '#7B0000',
		text: '#FFC72C'
	},
	{
		id: 'ateneo',
		name: 'Ateneo de Manila',
		glyph: 'ADMU',
		short: 'ADMU',
		country: 'PH',
		region: 'AS',
		domains: ['ateneo.edu'],
		rank: 579,
		color: '#00457C',
		text: '#F2ECDC'
	},
	{
		id: 'vnu',
		name: 'Vietnam National University',
		glyph: 'VNU',
		short: 'VNU',
		country: 'VN',
		region: 'AS',
		domains: ['vnu.edu.vn'],
		rank: 851,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'huji',
		name: 'Hebrew University Jerusalem',
		glyph: 'HUJI',
		short: 'HUJI',
		country: 'IL',
		region: 'AS',
		domains: ['huji.ac.il', 'mail.huji.ac.il'],
		rank: 137,
		color: '#003366',
		text: '#F2ECDC'
	},
	{
		id: 'telaviv',
		name: 'Tel Aviv',
		glyph: 'TAU',
		short: 'TAU',
		country: 'IL',
		region: 'AS',
		domains: ['tau.ac.il', 'mail.tau.ac.il'],
		rank: 167,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'technion',
		name: 'Technion',
		glyph: 'TECH',
		short: 'TECH',
		country: 'IL',
		region: 'AS',
		domains: ['technion.ac.il', 'campus.technion.ac.il'],
		rank: 184,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'idc',
		name: 'Reichman University',
		glyph: 'RU',
		short: 'RU',
		country: 'IL',
		region: 'AS',
		domains: ['runi.ac.il', 'post.runi.ac.il'],
		color: '#0066B3',
		text: '#F2ECDC'
	},
	// Australia / NZ
	{
		id: 'unimelb',
		name: 'Melbourne',
		glyph: 'UMEL',
		short: 'UMEL',
		country: 'AU',
		region: 'AU',
		domains: ['unimelb.edu.au', 'student.unimelb.edu.au'],
		rank: 13,
		color: '#000F46',
		text: '#F2ECDC'
	},
	{
		id: 'sydney',
		name: 'Sydney',
		glyph: 'USYD',
		short: 'USYD',
		country: 'AU',
		region: 'AU',
		domains: ['sydney.edu.au', 'uni.sydney.edu.au'],
		rank: 18,
		color: '#E64626',
		text: '#F2ECDC'
	},
	{
		id: 'unsw',
		name: 'UNSW Sydney',
		glyph: 'UNSW',
		short: 'UNSW',
		country: 'AU',
		region: 'AU',
		domains: ['unsw.edu.au', 'student.unsw.edu.au'],
		rank: 19,
		color: '#FFD600',
		text: '#1A1A1A'
	},
	{
		id: 'anu',
		name: 'ANU',
		glyph: 'ANU',
		short: 'ANU',
		country: 'AU',
		region: 'AU',
		domains: ['anu.edu.au'],
		rank: 30,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'monash',
		name: 'Monash',
		glyph: 'MON',
		short: 'MON',
		country: 'AU',
		region: 'AU',
		domains: ['monash.edu', 'student.monash.edu'],
		rank: 37,
		color: '#005A9C',
		text: '#F2ECDC'
	},
	{
		id: 'uq',
		name: 'Queensland (UQ)',
		glyph: 'UQ',
		short: 'UQ',
		country: 'AU',
		region: 'AU',
		domains: ['uq.edu.au', 'student.uq.edu.au'],
		rank: 40,
		color: '#51247A',
		text: '#F2ECDC'
	},
	{
		id: 'uwa',
		name: 'Western Australia (UWA)',
		glyph: 'UWA',
		short: 'UWA',
		country: 'AU',
		region: 'AU',
		domains: ['uwa.edu.au', 'student.uwa.edu.au'],
		rank: 77,
		color: '#003087',
		text: '#F2ECDC'
	},
	{
		id: 'adelaide',
		name: 'Adelaide',
		glyph: 'UAD',
		short: 'UAD',
		country: 'AU',
		region: 'AU',
		domains: ['adelaide.edu.au', 'student.adelaide.edu.au'],
		rank: 82,
		color: '#002D62',
		text: '#F2ECDC'
	},
	{
		id: 'uts',
		name: 'UTS Sydney',
		glyph: 'UTS',
		short: 'UTS',
		country: 'AU',
		region: 'AU',
		domains: ['uts.edu.au', 'student.uts.edu.au'],
		rank: 88,
		color: '#000000',
		text: '#0F4D92'
	},
	{
		id: 'macquarie',
		name: 'Macquarie',
		glyph: 'MQ',
		short: 'MQ',
		country: 'AU',
		region: 'AU',
		domains: ['mq.edu.au', 'students.mq.edu.au'],
		rank: 178,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'rmit',
		name: 'RMIT',
		glyph: 'RMIT',
		short: 'RMIT',
		country: 'AU',
		region: 'AU',
		domains: ['rmit.edu.au', 'student.rmit.edu.au'],
		rank: 123,
		color: '#E22424',
		text: '#F2ECDC'
	},
	{
		id: 'curtin',
		name: 'Curtin',
		glyph: 'CUR',
		short: 'CUR',
		country: 'AU',
		region: 'AU',
		domains: ['curtin.edu.au', 'student.curtin.edu.au'],
		rank: 174,
		color: '#FFC400',
		text: '#000000'
	},
	{
		id: 'auckland',
		name: 'Auckland',
		glyph: 'UOA',
		short: 'UOA',
		country: 'NZ',
		region: 'AU',
		domains: ['auckland.ac.nz', 'aucklanduni.ac.nz'],
		rank: 65,
		color: '#00467F',
		text: '#F2ECDC'
	},
	{
		id: 'otago',
		name: 'Otago',
		glyph: 'OTAG',
		short: 'OTAG',
		country: 'NZ',
		region: 'AU',
		domains: ['otago.ac.nz', 'student.otago.ac.nz'],
		rank: 197,
		color: '#FFD500',
		text: '#1A1A1A'
	},
	{
		id: 'victoria-wlg',
		name: 'Wellington (VUW)',
		glyph: 'VUW',
		short: 'VUW',
		country: 'NZ',
		region: 'AU',
		domains: ['vuw.ac.nz', 'myvuw.ac.nz'],
		rank: 244,
		color: '#115C26',
		text: '#F2ECDC'
	},
	// North America · Canada
	{
		id: 'toronto',
		name: 'Toronto',
		glyph: 'UTOR',
		short: 'UTOR',
		country: 'CA',
		region: 'NA',
		domains: ['utoronto.ca', 'mail.utoronto.ca'],
		rank: 25,
		color: '#002A5C',
		text: '#F2ECDC'
	},
	{
		id: 'mcgill',
		name: 'McGill',
		glyph: 'MCG',
		short: 'MCG',
		country: 'CA',
		region: 'NA',
		domains: ['mcgill.ca', 'mail.mcgill.ca'],
		rank: 27,
		color: '#ED1B2F',
		text: '#F2ECDC'
	},
	{
		id: 'ubc',
		name: 'UBC',
		glyph: 'UBC',
		short: 'UBC',
		country: 'CA',
		region: 'NA',
		domains: ['ubc.ca', 'student.ubc.ca', 'mail.ubc.ca'],
		rank: 38,
		color: '#002145',
		text: '#FFC72C'
	},
	{
		id: 'mcmaster',
		name: 'McMaster',
		glyph: 'MCM',
		short: 'MCM',
		country: 'CA',
		region: 'NA',
		domains: ['mcmaster.ca'],
		rank: 176,
		color: '#7A003C',
		text: '#F2ECDC'
	},
	{
		id: 'montreal',
		name: 'Montréal',
		glyph: 'UDEM',
		short: 'UDEM',
		country: 'CA',
		region: 'NA',
		domains: ['umontreal.ca'],
		rank: 141,
		color: '#0033A0',
		text: '#F2ECDC'
	},
	{
		id: 'alberta',
		name: 'Alberta',
		glyph: 'UALB',
		short: 'UALB',
		country: 'CA',
		region: 'NA',
		domains: ['ualberta.ca'],
		rank: 111,
		color: '#007C41',
		text: '#F2ECDC'
	},
	{
		id: 'waterloo',
		name: 'Waterloo',
		glyph: 'WAT',
		short: 'WAT',
		country: 'CA',
		region: 'NA',
		domains: ['uwaterloo.ca', 'edu.uwaterloo.ca'],
		rank: 101,
		color: '#FFD100',
		text: '#000000'
	},
	{
		id: 'western-on',
		name: 'Western Ontario',
		glyph: 'UWO',
		short: 'UWO',
		country: 'CA',
		region: 'NA',
		domains: ['uwo.ca'],
		rank: 114,
		color: '#4F2683',
		text: '#F2ECDC'
	},
	{
		id: 'queens',
		name: "Queen's University",
		glyph: 'QUE',
		short: 'QUE',
		country: 'CA',
		region: 'NA',
		domains: ['queensu.ca'],
		rank: 209,
		color: '#9D1939',
		text: '#F2ECDC'
	},
	{
		id: 'calgary',
		name: 'Calgary',
		glyph: 'UCAL',
		short: 'UCAL',
		country: 'CA',
		region: 'NA',
		domains: ['ucalgary.ca'],
		rank: 182,
		color: '#D6001C',
		text: '#FFC72C'
	},
	{
		id: 'ottawa',
		name: 'Ottawa',
		glyph: 'UOTT',
		short: 'UOTT',
		country: 'CA',
		region: 'NA',
		domains: ['uottawa.ca'],
		rank: 203,
		color: '#8B0F22',
		text: '#F2ECDC'
	},
	{
		id: 'sfu',
		name: 'Simon Fraser',
		glyph: 'SFU',
		short: 'SFU',
		country: 'CA',
		region: 'NA',
		domains: ['sfu.ca'],
		rank: 318,
		color: '#A6192E',
		text: '#F2ECDC'
	},
	// Latin America
	{
		id: 'usp',
		name: 'São Paulo (USP)',
		glyph: 'USP',
		short: 'USP',
		country: 'BR',
		region: 'LATAM',
		domains: ['usp.br'],
		rank: 92,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'unicamp',
		name: 'Unicamp',
		glyph: 'UNIC',
		short: 'UNIC',
		country: 'BR',
		region: 'LATAM',
		domains: ['unicamp.br', 'dac.unicamp.br'],
		rank: 220,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'puc-rio',
		name: 'PUC-Rio',
		glyph: 'PUC',
		short: 'PUC',
		country: 'BR',
		region: 'LATAM',
		domains: ['puc-rio.br', 'aluno.puc-rio.br'],
		rank: 591,
		color: '#003366',
		text: '#F2ECDC'
	},
	{
		id: 'fgv',
		name: 'Fundação Getulio Vargas',
		glyph: 'FGV',
		short: 'FGV',
		country: 'BR',
		region: 'LATAM',
		domains: ['fgv.br', 'fgvmail.br'],
		color: '#1B365D',
		text: '#F2ECDC'
	},
	{
		id: 'unam',
		name: 'UNAM',
		glyph: 'UNAM',
		short: 'UNAM',
		country: 'MX',
		region: 'LATAM',
		domains: ['unam.mx', 'comunidad.unam.mx'],
		rank: 104,
		color: '#003E7E',
		text: '#F2ECDC'
	},
	{
		id: 'itesm',
		name: 'Tecnológico de Monterrey',
		glyph: 'TEC',
		short: 'TEC',
		country: 'MX',
		region: 'LATAM',
		domains: ['tec.mx', 'exatec.tec.mx'],
		rank: 184,
		color: '#003B5C',
		text: '#F2ECDC'
	},
	{
		id: 'uchile',
		name: 'Chile',
		glyph: 'UCHI',
		short: 'UCHI',
		country: 'CL',
		region: 'LATAM',
		domains: ['uchile.cl', 'ug.uchile.cl'],
		rank: 173,
		color: '#005CA9',
		text: '#F2ECDC'
	},
	{
		id: 'uc-cl',
		name: 'PUC Chile',
		glyph: 'UCAT',
		short: 'UCAT',
		country: 'CL',
		region: 'LATAM',
		domains: ['uc.cl', 'estudiante.uc.cl'],
		rank: 96,
		color: '#003D7C',
		text: '#F2ECDC'
	},
	// Middle East / Africa
	{
		id: 'kaust',
		name: 'KAUST',
		glyph: 'KAU',
		short: 'KAU',
		country: 'SA',
		region: 'MEA',
		domains: ['kaust.edu.sa'],
		rank: 172,
		color: '#005C84',
		text: '#F2ECDC'
	},
	{
		id: 'aub',
		name: 'American Univ of Beirut',
		glyph: 'AUB',
		short: 'AUB',
		country: 'LB',
		region: 'MEA',
		domains: ['aub.edu.lb', 'mail.aub.edu'],
		rank: 226,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'auc',
		name: 'American Univ in Cairo',
		glyph: 'AUC',
		short: 'AUC',
		country: 'EG',
		region: 'MEA',
		domains: ['aucegypt.edu'],
		rank: 411,
		color: '#3F1F69',
		text: '#F2ECDC'
	},
	{
		id: 'cairo-u',
		name: 'Cairo University',
		glyph: 'CU',
		short: 'CU',
		country: 'EG',
		region: 'MEA',
		domains: ['cu.edu.eg'],
		rank: 481,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	{
		id: 'uct',
		name: 'Cape Town',
		glyph: 'UCT',
		short: 'UCT',
		country: 'ZA',
		region: 'MEA',
		domains: ['uct.ac.za', 'myuct.ac.za'],
		rank: 173,
		color: '#003B5C',
		text: '#F2ECDC'
	},
	{
		id: 'wits',
		name: 'Witwatersrand (Wits)',
		glyph: 'WITS',
		short: 'WITS',
		country: 'ZA',
		region: 'MEA',
		domains: ['wits.ac.za', 'students.wits.ac.za'],
		rank: 264,
		color: '#0033A0',
		text: '#F2ECDC'
	},
	{
		id: 'stellenbosch',
		name: 'Stellenbosch',
		glyph: 'SUN',
		short: 'SUN',
		country: 'ZA',
		region: 'MEA',
		domains: ['sun.ac.za'],
		rank: 319,
		color: '#7B003F',
		text: '#F2ECDC'
	},
	{
		id: 'koc',
		name: 'Koç University',
		glyph: 'KOC',
		short: 'KOC',
		country: 'TR',
		region: 'MEA',
		domains: ['ku.edu.tr', 'student.ku.edu.tr'],
		rank: 425,
		color: '#0078B6',
		text: '#F2ECDC'
	},
	{
		id: 'bogazici',
		name: 'Boğaziçi',
		glyph: 'BOG',
		short: 'BOG',
		country: 'TR',
		region: 'MEA',
		domains: ['boun.edu.tr'],
		rank: 651,
		color: '#003D7C',
		text: '#F2ECDC'
	},
	{
		id: 'metu',
		name: 'METU Ankara',
		glyph: 'METU',
		short: 'METU',
		country: 'TR',
		region: 'MEA',
		domains: ['metu.edu.tr'],
		rank: 480,
		color: '#A6093D',
		text: '#F2ECDC'
	},
	// Retained from the prior roster — institutions absent from the
	// directory port but still resolvable for affiliations already held.
	{
		id: 'itam',
		name: 'ITAM',
		glyph: 'ITAM',
		short: 'ITAM',
		country: 'MX',
		region: 'LATAM',
		domains: ['itam.mx'],
		color: '#003E7E',
		text: '#F2ECDC'
	}
] as const;

/**
 * Country roster — ISO-3166 alpha-2 ids, emoji flags. Tracks the
 * top ~24 countries by predicted active-user volume; future expansion
 * is an additions-only change (no satellite migration needed).
 */
export const WORLDS_COUNTRIES: readonly WorldsAffiliationOption[] = [
	{ id: 'AR', name: 'Argentina', glyph: '🇦🇷' },
	{ id: 'AU', name: 'Australia', glyph: '🇦🇺' },
	{ id: 'BR', name: 'Brazil', glyph: '🇧🇷' },
	{ id: 'CA', name: 'Canada', glyph: '🇨🇦' },
	{ id: 'CH', name: 'Switzerland', glyph: '🇨🇭' },
	{ id: 'CN', name: 'China', glyph: '🇨🇳' },
	{ id: 'DE', name: 'Germany', glyph: '🇩🇪' },
	{ id: 'DK', name: 'Denmark', glyph: '🇩🇰' },
	{ id: 'ES', name: 'Spain', glyph: '🇪🇸' },
	{ id: 'FR', name: 'France', glyph: '🇫🇷' },
	{ id: 'GB', name: 'United Kingdom', glyph: '🇬🇧' },
	{ id: 'IN', name: 'India', glyph: '🇮🇳' },
	{ id: 'IT', name: 'Italy', glyph: '🇮🇹' },
	{ id: 'JP', name: 'Japan', glyph: '🇯🇵' },
	{ id: 'KR', name: 'Korea Rep.', glyph: '🇰🇷' },
	{ id: 'MX', name: 'Mexico', glyph: '🇲🇽' },
	{ id: 'NL', name: 'Netherlands', glyph: '🇳🇱' },
	{ id: 'PT', name: 'Portugal', glyph: '🇵🇹' },
	{ id: 'SE', name: 'Sweden', glyph: '🇸🇪' },
	{ id: 'SG', name: 'Singapore', glyph: '🇸🇬' },
	{ id: 'TR', name: 'Turkey', glyph: '🇹🇷' },
	{ id: 'US', name: 'United States', glyph: '🇺🇸' },
	{ id: 'ZA', name: 'South Africa', glyph: '🇿🇦' }
] as const;

/**
 * Indexed lookup for the FE — given a stored `affiliationIdentifier` + kind,
 * resolve to the display option. Returns `undefined` for ids no longer
 * in the static roster (e.g. an option was removed but a user still
 * carries the affiliation; the FE falls back to showing the id).
 */
export const lookupWorldsAffiliation = ({
	kind,
	id
}: {
	kind: AffiliationKind;
	id: string;
}): WorldsAffiliationOption | undefined => {
	const roster = kind === 'university' ? WORLDS_UNIVERSITIES : WORLDS_COUNTRIES;

	return roster.find((option) => option.id === id);
};
