<script lang="ts">
	import {
		renderFlowArt,
		type FlowArtCategory,
		type FlowArtState
	} from '$lib/utils/flow-art.utils';

	interface Props {
		// Visual language. One of the six prediction-market categories.
		category: FlowArtCategory;
		// Stable seed — pass `market.id` or any deterministic string /
		// number. Same seed + state always produces the same composition.
		seed: string | number;
		// Resolution state. Flow Mode only ever uses 'neutral'; 'won' /
		// 'lost' are reserved for Portfolio resolution crossfades.
		state?: FlowArtState;
		// Output size in CSS px. Standard scales: 80 (deck thumb),
		// 140 (list card), 220 (hero card on swipe surface).
		size?: number;
		// When true, draws an additional inset stroke frame inside the
		// composition. Off by default; FlowCard layers a separate frame.
		frame?: boolean;
		// Optional extra class on the wrapper for layout overrides.
		class?: string;
	}

	const {
		category,
		seed,
		state = 'neutral',
		size = 220,
		frame = false,
		class: extraClass = ''
	}: Props = $props();

	const svg = $derived(renderFlowArt({ category, seed, state, size, frame }));
</script>

<div
	style:width="{size}px"
	style:height="{size}px"
	class="flow-art-frame {extraClass}"
	aria-hidden="true"
>
	<!-- The SVG output is generated by `renderFlowArt` from a fixed palette
	     and numeric coordinates derived from a deterministic seed; no
	     user-controllable input flows into this string. Safe to inline. -->
	<!-- eslint-disable-next-line svelte/no-at-html-tags -->
	{@html svg}
</div>

<style lang="postcss">
	.flow-art-frame {
		display: inline-block;
		line-height: 0;
		border-radius: var(--r-12);
		overflow: hidden;
		box-shadow: var(--inset-hi);
		flex: 0 0 auto;
	}

	.flow-art-frame :global(svg) {
		display: block;
		width: 100%;
		height: 100%;
	}
</style>
