<script lang="ts">
	import { theme } from '$lib/stores/theme.store';
	import {
		flowArtViewBox,
		renderFlowArt,
		type FlowArtCategory,
		type FlowArtState
	} from '$lib/utils/flow-art.utils';

	interface Props {
		// Visual language — a taxonomy macro (folded onto one of the six
		// bespoke render buckets) or the `wc` tentpole editorial variant.
		category: FlowArtCategory;
		// Stable seed — pass `market.id` or any deterministic string /
		// number. Same seed + state always produces the same composition.
		seed: string | number;
		// Resolution state. Flow Mode only ever uses 'neutral'; 'won' /
		// 'lost' are reserved for Portfolio resolution crossfades.
		state?: FlowArtState;
		// Output size in CSS px. Standard scales: 80 (deck thumb),
		// 140 (list card), 220 (hero card on swipe surface).
		size?: number;
		// When true, draws an additional inset stroke frame inside the
		// composition. Off by default; FlowCard layers a separate frame.
		frame?: boolean;
		// When true, the frame fills its container (100% × 100%) instead
		// of rendering at the fixed `size`. Paired with the WC `slice`
		// viewBox this lets the art fill a tall bleed band — cropping
		// horizontally rather than letterboxing in the middle. `size`
		// still drives the SVG's internal resolution.
		fill?: boolean;
		// Optional market question text. Only the WC renderer consults it
		// — to look up per-market artwork in the `WC_MARKET_ART` catalogue
		// (then the heuristic resolver); omitting it leaves every render —
		// WC or otherwise — unchanged.
		title?: string;
		// Optional extra class on the wrapper for layout overrides.
		class?: string;
	}

	const {
		category,
		seed,
		state = 'neutral',
		size = 220,
		frame = false,
		fill = false,
		title,
		class: extraClass = ''
	}: Props = $props();

	const svg = $derived(renderFlowArt({ category, seed, state, theme: $theme, size, frame, title }));
	// `wc` renders into a 280×100 viewBox; default categories are 1:1.
	// Mirror that aspect on the host so the SVG isn't squished.
	const viewBox = $derived(flowArtViewBox(category));
	const heightPx = $derived(Math.round((size * viewBox.height) / viewBox.width));
</script>

<div
	style:width={fill ? null : `${size}px`}
	style:height={fill ? null : `${heightPx}px`}
	class="flow-art-frame {extraClass}"
	class:is-fill={fill}
	aria-hidden="true"
>
	<!-- The SVG output is generated by `renderFlowArt` from a fixed palette
	     and numeric coordinates derived from a deterministic seed; no
	     user-controllable input flows into this string. Safe to inline. -->
	<!-- eslint-disable-next-line svelte/no-at-html-tags -->
	{@html svg}
</div>

<style lang="postcss">
	.flow-art-frame {
		display: inline-block;
		line-height: 0;
		border-radius: var(--r-12);
		overflow: hidden;
		box-shadow: var(--inset-hi);
		flex: 0 0 auto;
	}

	/* Fill mode — stretch to the host band instead of the fixed size. */
	.flow-art-frame.is-fill {
		display: block;
		width: 100%;
		height: 100%;
		flex: 1 1 auto;
	}

	.flow-art-frame :global(svg) {
		display: block;
		width: 100%;
		height: 100%;
	}

	/* ── WC artwork motion ──────────────────────────────────────────
	   `renderFlowArt` tags three editorial layers in the WC tentpole
	   register: a faceted figure (`wc-figure`), two spotlight cones
	   (`wc-spot`, paired left/right), and 0–10 confetti shards
	   (`wc-cnf` with a per-shard `wc-cnf-${i}` for stagger). These
	   were inert until now — the CSS keyframes ship here
	   so every WC-tagged Flow card animates without changing the
	   render layer.

	   Motion is gentle and capped at ~6s loop; reduced-motion pauses
	   it. */

	.flow-art-frame :global(.wc-figure) {
		transform-box: fill-box;
		transform-origin: 50% 80%;
		animation: wc-figure-sway 5.2s ease-in-out infinite;
	}

	.flow-art-frame :global(.wc-spot) {
		transform-box: fill-box;
		transform-origin: 50% 0;
		animation: wc-spot-sweep 6s ease-in-out infinite;
	}

	.flow-art-frame :global(.wc-spot-right) {
		animation-delay: -3s;
	}

	.flow-art-frame :global(.wc-cnf) {
		transform-box: fill-box;
		transform-origin: 50% 50%;
		animation: wc-cnf-drift 4.8s linear infinite;
	}

	/* Per-shard stagger — keeps shards from drifting in lockstep. The
	   modulo-10 dispatcher inside `renderFlowArt` keeps indices in
	   range, so the 10 hooks below cover every shard. */
	.flow-art-frame :global(.wc-cnf-0) {
		animation-delay: 0s;
	}
	.flow-art-frame :global(.wc-cnf-1) {
		animation-delay: -0.4s;
	}
	.flow-art-frame :global(.wc-cnf-2) {
		animation-delay: -0.9s;
	}
	.flow-art-frame :global(.wc-cnf-3) {
		animation-delay: -1.3s;
	}
	.flow-art-frame :global(.wc-cnf-4) {
		animation-delay: -1.8s;
	}
	.flow-art-frame :global(.wc-cnf-5) {
		animation-delay: -2.2s;
	}
	.flow-art-frame :global(.wc-cnf-6) {
		animation-delay: -2.7s;
	}
	.flow-art-frame :global(.wc-cnf-7) {
		animation-delay: -3.1s;
	}
	.flow-art-frame :global(.wc-cnf-8) {
		animation-delay: -3.6s;
	}
	.flow-art-frame :global(.wc-cnf-9) {
		animation-delay: -4s;
	}

	@keyframes wc-figure-sway {
		0%,
		100% {
			transform: translateY(0) rotate(-0.6deg);
		}
		50% {
			transform: translateY(-1.2px) rotate(0.6deg);
		}
	}

	@keyframes wc-spot-sweep {
		0%,
		100% {
			transform: rotate(-3deg);
			opacity: 0.15;
		}
		50% {
			transform: rotate(3deg);
			opacity: 0.22;
		}
	}

	@keyframes wc-cnf-drift {
		0% {
			transform: translateY(0) rotate(0deg);
			opacity: 0;
		}
		15% {
			opacity: 0.85;
		}
		100% {
			transform: translateY(36px) rotate(180deg);
			opacity: 0;
		}
	}

	@media (prefers-reduced-motion: reduce) {
		.flow-art-frame :global(.wc-figure),
		.flow-art-frame :global(.wc-spot),
		.flow-art-frame :global(.wc-cnf) {
			animation: none;
		}
	}
</style>
