import { idlFactoryClearing, idlFactoryManagement, idlFactoryRegistry } from '$declarations';
import { isNullish, nonNullish } from '@dfinity/utils';
import { IDL } from '@icp-sdk/core/candid';

/**
 * Candid type definitions for inter-canister calls must never be hand-written:
 * they would silently drift from the icdc-core interface that
 * `src/declarations/**` mirrors (those `.idl.js` factories are downloaded +
 * generated by `npm run did`, see `scripts/import-candid.sh`).
 *
 * Each generated `idlFactory` is an `IDL.InterfaceFactory` — calling it builds
 * the full `IDL.ServiceClass`, whose `_fields` carry, per method, the exact
 * `argTypes` / `retTypes` the canister expects. {@link candidMethod} reads those
 * straight from the factory so satellite call sites encode/decode against the
 * single source of truth instead of re-declaring `IDL.Record` / `IDL.Variant`
 * shapes inline.
 *
 * (The generated `.idl.js` only exports `idlFactory`, not its inner type
 * consts, so deriving from the service is the only way to reuse them without
 * touching the `// @ts-nocheck` generated file.)
 */

const FACTORIES = {
	registry: idlFactoryRegistry,
	clearing: idlFactoryClearing,
	management: idlFactoryManagement
} satisfies Record<string, IDL.InterfaceFactory>;

type CanisterInterface = keyof typeof FACTORIES;

// Instantiating a factory builds the whole type table, so memoise per
// interface — method lookups then reuse the same service instance.
const services = new Map<CanisterInterface, IDL.ServiceClass>();

const serviceFor = (canister: CanisterInterface): IDL.ServiceClass => {
	const cached = services.get(canister);

	if (nonNullish(cached)) {
		return cached;
	}

	const service = FACTORIES[canister]({ IDL });
	services.set(canister, service);

	return service;
};

/**
 * Resolves the Candid `argTypes` (to pair with values in `call({ args })`) and
 * the single `result` type (for `call({ result })`) of a canister method,
 * derived from the generated IDL factory.
 *
 * @throws if the method is absent from the generated interface, or carries no
 * return type — both signal that the call site is out of sync with the current
 * `.did`.
 */
export const candidMethod = ({
	canister,
	method
}: {
	canister: CanisterInterface;
	method: string;
}): { argTypes: IDL.Type[]; result: IDL.Type } => {
	const field = serviceFor(canister)._fields.find(([name]) => name === method);

	if (isNullish(field)) {
		throw new Error(`Candid method '${method}' not found in the '${canister}' interface.`);
	}

	const [, func] = field;
	const [result] = func.retTypes;

	if (isNullish(result)) {
		throw new Error(`Candid method '${method}' on '${canister}' returns no value.`);
	}

	return { argTypes: func.argTypes, result };
};
