/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AcceptPositionTransferResult = { Ok: boolean } | { Err: TradeError };
export interface AccountState {
	user: Principal;
	reserved_margins_usd: Array<[BalanceDomain, bigint]>;
	cash_balances_usd: Array<[BalanceDomain, bigint]>;
	balances: Array<[BalanceDomain, Array<[string, bigint]>]>;
}
export type AccountStateError =
	| { MathOverflow: null }
	| { Asset: AssetError }
	| { NoAccountStateFound: null };
export interface AccountStateResponse {
	assets: Array<AssetWorth>;
	state: AccountState;
	total_equity_usd: bigint;
	available_margin_usd: bigint;
}
export type Asset = { Erc20: ErcToken } | { Icrc: Principal } | { NativeEvm: NativeEvmAsset };
export type AssetError =
	| { TransferError: string }
	| { InsufficientBalance: { balance: bigint; required: bigint } }
	| { MathOverflow: null }
	| { InvalidAssetId: string }
	| { CallError: { method: string; code: number; message: string } }
	| { InvalidAssetForHandler: null }
	| { UnsupportedAsset: null };
export interface AssetMetrics {
	haircut_bps: number;
	latest_transfer_fee: [] | [bigint];
	insurance_fee_ratio: [] | [number];
	last_updated_ns: [] | [bigint];
	protocol_fee_ratio: [] | [number];
	price_usd: DecimalValue;
}
export interface AssetWorth {
	pre_haircut_value_usd: bigint;
	haircut_bps: number;
	balance: bigint;
	value_usd: bigint;
	asset_id: string;
}
export type BalanceDomain = { Playground: null } | { Settlement: null };
export type CancelFundWithdrawalError =
	| { PlanNotFound: null }
	| { InvalidPlanStatus: null }
	| { Common: CommonError };
export interface CancelFundWithdrawalParams {
	request_id: string;
}
export type CancelFundWithdrawalResult = { Ok: null } | { Err: CancelFundWithdrawalError };
export interface CancelLimitOrderParams {
	order_id: string;
}
export interface CollateralAssetConfig {
	decimals: number;
	asset: Asset;
	is_enabled: boolean;
	allowed_balance_domains: Array<BalanceDomain>;
	oracle_id: [] | [string];
	asset_id: string;
	symbol: string;
}
export interface CollateralAssetInfo {
	metrics: [] | [AssetMetrics];
	config: CollateralAssetConfig;
}
export type CommonError =
	| { Internal: string }
	| { InvalidInput: string }
	| { MathOverflow: null }
	| { Unauthorized: null }
	| { RegistryNotSet: null };
export interface Config {
	insurance_fund_fee_ratio: number;
	internal_ledger: CollateralAssetConfig;
	signer_canister: Principal;
	version: number;
	evm_rpc: Principal;
	protocol_fee_ratio: number;
}
export interface DecimalValue {
	decimals: number;
	value: bigint;
}
export type DepositCollateralError =
	| {
			DomainNotAllowed: { domain: BalanceDomain; asset_id: string };
	  }
	| { MathOverflow: null }
	| { Asset: AssetError };
export interface DepositCollateralParams {
	deposit_id: string;
	domain: [] | [BalanceDomain];
	asset_id: string;
	amount: bigint;
}
export type DepositCollateralResult = { Ok: null } | { Err: DepositCollateralError };
export interface Description {
	html: [] | [string];
	markdown: [] | [string];
	plain: string;
}
export interface DomainPolicy {
	deposits_enabled: boolean;
	protocol_fee_ratio_override: [] | [number];
	label: string;
	withdrawals_enabled: boolean;
	insurance_fund_fee_ratio_override: [] | [number];
}
export interface ErcToken {
	decimals: number;
	token_address: string;
	chain_id: bigint;
}
export interface Event {
	qty: bigint;
	series_id: string;
	user: Principal;
	timestamp: bigint;
	event_id: bigint;
	price: Price;
	event_type: EventType;
	clearing_id: Principal;
}
export type EventType =
	| { OrderPlaced: null }
	| { Executed: null }
	| { Liquidated: null }
	| { Settled: null };
export type FiatUnit = { Chf: null } | { Eur: null } | { Gbp: null } | { Usd: null };
export interface FreezePositionForTransferParams {
	outcome_id: [] | [string];
	series_id: string;
	user: Principal;
	transfer_id: string;
	valuation_price: [] | [Price];
}
export type FundType = { Insurance: null } | { Treasury: null };
export interface GetAccountStateParams {
	domain: [] | [BalanceDomain];
	refresh: [] | [boolean];
}
export type GetAccountStateResult = { Ok: AccountStateResponse } | { Err: AccountStateError };
export interface GetFundsResult {
	insurance_fund: Array<[string, bigint]>;
	treasury: Array<[string, bigint]>;
}
export interface GetPositionParams {
	outcome_id: [] | [string];
	series_id: string;
}
export interface HttpRequest {
	url: string;
	method: string;
	body: Uint8Array;
	headers: Array<[string, string]>;
}
export interface HttpResponse {
	body: Uint8Array;
	headers: Array<[string, string]>;
	status_code: number;
}
export interface LimitOrder {
	qty: bigint;
	creator: Principal;
	outcome_id: [] | [string];
	blocked_margin_usd: bigint;
	series_id: string;
	side: Side;
	order_id: string;
	price: Price;
	balance_domain: BalanceDomain;
}
export interface ListOrdersParams {
	series_id: [] | [string];
}
export interface MigrateDomainParams {
	from_domain: BalanceDomain;
	migration_id: string;
	to_domain: BalanceDomain;
}
export type MigrateDomainResult = { Ok: null } | { Err: MigrationError };
export type MigrationError =
	| { NoStateTOMigrate: null }
	| { SameDomain: null }
	| { InFlightPlansExist: null }
	| { Common: CommonError };
export interface NativeEvmAsset {
	decimals: number;
	chain_id: bigint;
}
export type NonMonetaryUnit = { Points: null };
export interface Outcome {
	id: string;
	title: string;
	description: [] | [Description];
	icon_url: [] | [string];
}
export type PaymentIdempotency = { IcrcCreatedAtTimeNs: bigint };
export type PayoffType = { Put: null } | { Binary: null } | { Call: null } | { Categorical: null };
export type PayoutUnit = { Fiat: FiatUnit } | { Asset: Asset } | { NonMonetary: NonMonetaryUnit };
export type PlanStatus = { Finalised: null } | { Planned: null } | { Executing: null };
export interface Position {
	outcome_id: [] | [string];
	series_id: string;
	net_qty: bigint;
	user: Principal;
	reserved_margin_usd: bigint;
}
export interface PositionProof {
	qty: bigint;
	signature: Uint8Array;
	outcome_id: [] | [string];
	series_id: string;
	user: Principal;
	transfer_id: string;
	valuation_price: [] | [Price];
	clearing_id: Principal;
}
export interface Price {
	timestamp: [] | [bigint];
	oracle_id: [] | [string];
	decimal: DecimalValue;
}
export type RegisterIcrcAssetError =
	| { InvalidAllowedBalanceDomains: null }
	| { AssetAlreadyExists: null }
	| { VusdCannotBeCollateral: null }
	| { Common: CommonError };
export interface RegisterIcrcAssetParams {
	haircut_bps: number;
	is_enabled: boolean;
	allowed_balance_domains: Array<BalanceDomain>;
	ledger_id: Principal;
	oracle_id: [] | [string];
	asset_id: string;
}
export type RegisterIcrcAssetResult = { Ok: null } | { Err: RegisterIcrcAssetError };
export interface Series {
	title: string;
	strike: [] | [Price];
	creator: Principal;
	payoff_type: PayoffType;
	payout_unit: PayoutUnit;
	expiry_ns: bigint;
	banner_url: [] | [string];
	series_id: string;
	underlying: string;
	description: Description;
	outcomes: [] | [Array<Outcome>];
	created_at_ns: bigint;
	icon_url: [] | [string];
	price_precision: number;
	balance_domain: BalanceDomain;
	oracle_source: string;
}
export interface SettleSeriesParams {
	series_id: string;
	settlement: SettlementInput;
}
export type SettleSeriesResult = { Ok: null } | { Err: SettlementError } | { Processing: null };
export type SettlementError =
	| {
			InconsistentSettlementPrice: { requested: Price; existing: Price };
	  }
	| { MathOverflow: null }
	| {
			SolvencyViolation: {
				total_net_payoff: bigint;
				total_collateral_usd: bigint;
			};
	  }
	| { Asset: AssetError }
	| { Common: CommonError };
export type SettlementInput = { Price: Price } | { Outcome: string };
export interface SettlementPlan {
	status: PlanStatus;
	idempotency_ns: PaymentIdempotency;
	series_id: string;
	fee_usd: bigint;
	accounting_cursor: bigint;
	insurance_fee_usd: bigint;
	positions: Array<SettlementPosition>;
	accounting_applied: boolean;
	balance_domain: BalanceDomain;
	oracle_source: string;
	settlement: SettlementInput;
}
export interface SettlementPosition {
	outcome_id: [] | [string];
	net_qty: bigint;
	user: Principal;
	reserved_margin_usd: bigint;
	cashflow_usd: bigint;
}
export interface SettlementStatusView {
	status: PlanStatus;
	series_id: string;
	fee_usd: bigint;
	accounting_cursor: bigint;
	insurance_fee_usd: bigint;
	accounting_applied: boolean;
	balance_domain: BalanceDomain;
	oracle_source: string;
	total_positions: bigint;
	settlement: SettlementInput;
}
export type Side = { Buy: null } | { Sell: null };
export interface Stats {
	total_users: bigint;
	margin_balances: Array<[Asset, bigint]>;
	total_collateral_locked: bigint;
	total_trades: bigint;
	total_series: bigint;
	open_interest: bigint;
	event_counts: Array<[string, bigint]>;
}
export interface SubmitLimitOrderParams {
	qty: bigint;
	outcome_id: [] | [string];
	series_id: string;
	side: Side;
	order_id: string;
	price: Price;
}
export interface SubmitMarketOrderParams {
	trade_id: string;
	matching_order_id: string;
}
export interface SubmitMatchedTradeParams {
	qty: bigint;
	trade_id: string;
	outcome_id: [] | [string];
	series_id: string;
	seller: Principal;
	buyer_unblock_amount: [] | [bigint];
	buyer: Principal;
	price: Price;
	seller_unblock_amount: [] | [bigint];
}
export type SubmitMatchedTradeResult = { Ok: boolean } | { Err: TradeError };
export type TradeError =
	| { SelfTradingNotAllowed: null }
	| { OrderNotFound: string }
	| { ArbitrageLimitExceeded: { limit_usd: bigint; sum_usd: bigint } }
	| { RegistryError: string }
	| {
			InsufficientMargin: {
				balance: bigint;
				user: Principal;
				required: bigint;
			};
	  }
	| { NotOrderCreator: null }
	| { SeriesNotFound: string }
	| { Common: CommonError };
export interface UpdateAssetMetricsParams {
	metrics: AssetMetrics;
	asset_id: string;
}
export type UpdateAssetPriceError =
	| { AssetNotFound: null }
	| { AssetMetricsNotInitialized: null }
	| { OracleNotConfigured: null }
	| { Common: CommonError };
export interface UpdateAssetPriceParams {
	price: Price;
	asset_id: string;
}
export type UpdateAssetPriceResult = { Ok: null } | { Err: UpdateAssetPriceError };
export type UpdateCollateralAllowedDomainsError =
	| { AssetNotFound: null }
	| { InvalidAllowedBalanceDomains: null };
export interface UpdateCollateralAllowedDomainsParams {
	allowed_balance_domains: Array<BalanceDomain>;
	asset_id: string;
}
export type UpdateCollateralAllowedDomainsResult =
	| { Ok: null }
	| { Err: UpdateCollateralAllowedDomainsError };
export interface UpdateCollateralAssetParams {
	config: CollateralAssetConfig;
}
export interface UpdateDomainPolicyParams {
	domain: BalanceDomain;
	policy: DomainPolicy;
}
export type WithdrawCollateralError =
	| {
			InsufficientExcessMargin: { requested: bigint; available: bigint };
	  }
	| { DomainNotAllowed: { domain: BalanceDomain; asset_id: string } }
	| { MathOverflow: null }
	| { Asset: AssetError };
export interface WithdrawCollateralParams {
	domain: [] | [BalanceDomain];
	withdrawal_id: string;
	asset_id: string;
	amount: bigint;
}
export type WithdrawCollateralResult = { Ok: null } | { Err: WithdrawCollateralError };
export type WithdrawFundError =
	| { TransferFailed: string }
	| { InsufficientFunds: null }
	| { Common: CommonError };
export interface WithdrawFundParams {
	to: Principal;
	request_id: string;
	fund_type: FundType;
	asset_id: string;
	amount: bigint;
}
export type WithdrawFundResult = { Ok: bigint } | { Err: WithdrawFundError };
export interface _SERVICE {
	/**
	 * Accepts a position transfer from another clearing canister.
	 *
	 * This method validates the series and increases the target user's position based on the provided
	 * proof. This method is gated to canister controllers.
	 */
	accept_position_transfer: ActorMethod<[PositionProof], AcceptPositionTransferResult>;
	/**
	 * Cancels a stuck fund withdrawal and refunds the internal ledger balance.
	 *
	 * This method is gated to canister controllers.
	 */
	cancel_fund_withdrawal: ActorMethod<[CancelFundWithdrawalParams], CancelFundWithdrawalResult>;
	/**
	 * Cancels an existing limit order and releases the reserved collateral.
	 *
	 * Only the creator of the order can cancel it.
	 */
	cancel_limit_order: ActorMethod<[CancelLimitOrderParams], SubmitMatchedTradeResult>;
	/**
	 * Returns the current global configuration of the Clearing canister.
	 */
	config: ActorMethod<[], Config>;
	/**
	 * Deposits collateral into the user's account state.
	 *
	 * This is a multi-phase operation:
	 * 1. Building a [`DepositPlan`] for idempotency.
	 * 2. Executing the asynchronous ledger transfer (`transfer_from`).
	 * 3. Finalising the internal collateral balances.
	 */
	deposit_collateral: ActorMethod<[DepositCollateralParams], DepositCollateralResult>;
	/**
	 * Freezes a user's position to prepare it for transfer to another clearing canister.
	 *
	 * Once frozen, the position is removed from active state and a [`PositionProof`] is issued.
	 * This method is gated to canister controllers.
	 */
	freeze_position_for_transfer: ActorMethod<
		[FreezePositionForTransferParams],
		[] | [PositionProof]
	>;
	/**
	 * Retrieves the current user's account state, optionally refreshing balances.
	 *
	 * # Arguments
	 * * `params` - Includes an optional `refresh` flag to trigger external ledger checks.
	 */
	get_account_state: ActorMethod<[GetAccountStateParams], GetAccountStateResult>;
	/**
	 * Retrieves the current user's account state (query only).
	 *
	 * This does not refresh balances from external ledgers.
	 */
	get_account_state_query: ActorMethod<[], GetAccountStateResult>;
	/**
	 * Returns the current domain policies for all configured domains.
	 *
	 * This method is gated to canister controllers.
	 */
	get_domain_policies: ActorMethod<[], Array<[BalanceDomain, DomainPolicy]>>;
	/**
	 * Returns the current balances of the Insurance Fund and Treasury.
	 *
	 * This method is gated to canister controllers.
	 */
	get_funds: ActorMethod<[], GetFundsResult>;
	/**
	 * Retrieves all active limit orders for the caller.
	 */
	get_orders: ActorMethod<[], Array<LimitOrder>>;
	/**
	 * Retrieves a specific position for the caller.
	 */
	get_position: ActorMethod<[GetPositionParams], [] | [Position]>;
	/**
	 * Retrieves all open positions for the caller.
	 */
	get_positions: ActorMethod<[], Array<Position>>;
	/**
	 * Returns the principal of the Series Registry canister.
	 */
	get_registry_canister: ActorMethod<[], Principal>;
	/**
	 * Returns the full settlement plan including per-position accounting details (admin only).
	 */
	get_settlement_plan: ActorMethod<[string], [] | [SettlementPlan]>;
	/**
	 * Returns the public settlement progress for a derivative series without exposing user positions.
	 */
	get_settlement_status: ActorMethod<[string], [] | [SettlementStatusView]>;
	/**
	 * Retrieves the trade history (executed trades) for the caller.
	 */
	get_trade_history: ActorMethod<[], Array<Event>>;
	/**
	 * Handles incoming HTTP requests for Prometheus metrics.
	 *
	 * This endpoint is restricted to canister controllers and serves metrics at `/metrics`.
	 */
	http_request: ActorMethod<[HttpRequest], HttpResponse>;
	/**
	 * Returns a list of all supported collateral assets with their metrics.
	 */
	list_collateral_assets: ActorMethod<[], Array<CollateralAssetInfo>>;
	/**
	 * Returns a list of all active limit orders, potentially filtered by series.
	 */
	list_orders: ActorMethod<[ListOrdersParams], Array<LimitOrder>>;
	/**
	 * Returns a list of all derivative series currently cached in the clearing canister.
	 */
	list_series: ActorMethod<[], Array<Series>>;
	/**
	 * Exports internal state as Prometheus metrics.
	 *
	 * This method is gated to canister controllers.
	 */
	metrics: ActorMethod<[], string>;
	/**
	 * Migrates a user's entire domain state (balances, cash, margin, positions, orders)
	 * from one balance domain to another.
	 *
	 * This operation is idempotent: providing the same `migration_id` returns `Ok`
	 * if the migration was already finalised.
	 *
	 * Pre-conditions enforced:
	 * - `from_domain != to_domain`
	 * - No in-flight deposit, withdrawal, or settlement plans for the user in the source domain.
	 * - User must have state to migrate.
	 */
	migrate_domain: ActorMethod<[MigrateDomainParams], MigrateDomainResult>;
	/**
	 * Mints a complete set of categorical outcome positions.
	 *
	 * Returns 1 unit of every outcome position in the series in exchange for the
	 * full collateral requirement (1.0 USD vUSD).
	 */
	mint_complete_set: ActorMethod<[string, bigint], SubmitMatchedTradeResult>;
	/**
	 * Redeems a complete set of categorical outcome positions for collateral.
	 *
	 * Returns 1.0 USD (vUSD) for every full set of N outcome positions provided.
	 */
	redeem_complete_set: ActorMethod<[string, bigint], SubmitMatchedTradeResult>;
	/**
	 * Automatically registers an ICRC asset by fetching its metadata from the ledger.
	 *
	 * This method is gated to canister controllers.
	 */
	register_icrc_asset: ActorMethod<[RegisterIcrcAssetParams], RegisterIcrcAssetResult>;
	/**
	 * Admin function to manually resume a stuck settlement plan, e.g., if the timer was dropped during
	 * upgrade.
	 */
	resume_settlement: ActorMethod<[string], SettleSeriesResult>;
	/**
	 * Sets the principal of the Series Registry canister.
	 *
	 * This principal is used to discover and validate derivative series.
	 * This method is gated to canister controllers.
	 */
	set_registry_canister: ActorMethod<[Principal], undefined>;
	/**
	 * Settles a derivative series at a specific price.
	 *
	 * This is a background operation consisting of:
	 * 1. Creating or resuming a [`SettlementPlan`].
	 * 2. Updating internal USD cash balances for all participants based on payoffs.
	 * 3. Releasing margin requirements for the settled positions.
	 * 4. Finalising the plan and removing the series data.
	 *
	 * **Note on Chunking:** To avoid instruction limits, this method processes positions in batches
	 * of 100 per call. If there are many positions, the method will return
	 * [`SettleSeriesResult::Processing`]. The caller must repeatedly call `settle_series` with the
	 * same parameters until it returns [`SettleSeriesResult::Ok`].
	 *
	 * **Authorization:** Every call is gated to canister controllers or the designated oracle for
	 * the series. Unauthorized callers are rejected even if a plan already exists.
	 */
	settle_series: ActorMethod<[SettleSeriesParams], SettleSeriesResult>;
	/**
	 * Exports internal state as a structured `Stats` object.
	 *
	 * This method is gated to canister controllers.
	 */
	stats: ActorMethod<[], Stats>;
	/**
	 * Submits a limit order for the caller.
	 *
	 * This atomically blocks the required collateral for the order.
	 */
	submit_limit_order: ActorMethod<[SubmitLimitOrderParams], SubmitMatchedTradeResult>;
	/**
	 * Submits a market order to match an existing limit order.
	 *
	 * The caller is the taker.
	 */
	submit_market_order: ActorMethod<[SubmitMarketOrderParams], SubmitMatchedTradeResult>;
	/**
	 * Submits a matched trade from an exchange for clearing.
	 *
	 * NOTE: Access is currently restricted to authorized exchange intermediaries
	 * (represented by canister controllers in this version).
	 */
	submit_matched_trade: ActorMethod<[SubmitMatchedTradeParams], SubmitMatchedTradeResult>;
	/**
	 * Adds or updates dynamic metrics for a collateral asset.
	 *
	 * This method is gated to canister controllers.
	 */
	update_asset_metrics: ActorMethod<[UpdateAssetMetricsParams], undefined>;
	/**
	 * Updates the price of an asset.
	 *
	 * This method can be called by canister controllers or authorized oracles.
	 */
	update_asset_price: ActorMethod<[UpdateAssetPriceParams], UpdateAssetPriceResult>;
	/**
	 * Updates which balance domains may hold this collateral asset (deposits and withdrawals).
	 *
	 * This method is gated to canister controllers.
	 */
	update_collateral_allowed_domains: ActorMethod<
		[UpdateCollateralAllowedDomainsParams],
		UpdateCollateralAllowedDomainsResult
	>;
	/**
	 * Adds or updates a collateral asset configuration.
	 *
	 * This method is gated to canister controllers.
	 */
	update_collateral_asset: ActorMethod<[UpdateCollateralAssetParams], undefined>;
	/**
	 * Updates the global configuration for the Clearing canister.
	 *
	 * Immutable properties like `internal_ledger_id` and `version` are preserved from the existing
	 * state. This method is gated to canister controllers.
	 */
	update_config: ActorMethod<[Config], undefined>;
	/**
	 * Adds or updates the policy for a specific balance domain.
	 *
	 * This method is gated to canister controllers.
	 */
	update_domain_policy: ActorMethod<[UpdateDomainPolicyParams], undefined>;
	/**
	 * Withdraws collateral from the user's account state to an external address.
	 *
	 * This implements the "Deterministic Withdrawal Policy":
	 * 1. Calculate current account equity in USD.
	 * 2. Verify equity >= `reserved_margin_usd` (risk check).
	 * 3. If ok, proceed with asynchronous ledger transfer.
	 */
	withdraw_collateral: ActorMethod<[WithdrawCollateralParams], WithdrawCollateralResult>;
	/**
	 * Withdraws assets from the Insurance Fund or Treasury to an external wallet.
	 *
	 * This method is gated to canister controllers.
	 */
	withdraw_fund: ActorMethod<[WithdrawFundParams], WithdrawFundResult>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
