/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PositionProof = IDL.Record({
	qty: IDL.Int,
	signature: IDL.Vec(IDL.Nat8),
	series_id: IDL.Text,
	user: IDL.Principal,
	transfer_id: IDL.Text,
	clearing_id: IDL.Principal
});
export const CommonError = IDL.Variant({
	Internal: IDL.Text,
	MathOverflow: IDL.Null,
	Unauthorized: IDL.Null,
	RegistryNotSet: IDL.Null
});
export const TradeError = IDL.Variant({
	OrderNotFound: IDL.Text,
	RegistryError: IDL.Text,
	InsufficientMargin: IDL.Record({
		balance: IDL.Nat,
		user: IDL.Principal,
		required: IDL.Nat
	}),
	NotOrderCreator: IDL.Null,
	SeriesNotFound: IDL.Text,
	Common: CommonError
});
export const AcceptPositionTransferResult = IDL.Variant({
	Ok: IDL.Bool,
	Err: TradeError
});
export const Asset = IDL.Variant({ Icrc: IDL.Principal });
export const BlockCollateralParams = IDL.Record({
	asset: Asset,
	amount: IDL.Nat
});
export const BlockingError = IDL.Variant({
	InsufficientAvailableBalance: IDL.Record({
		requested: IDL.Nat,
		available: IDL.Nat
	}),
	MathOverflow: IDL.Null,
	InsufficientReservedBalance: IDL.Record({
		requested: IDL.Nat,
		reserved: IDL.Nat
	})
});
export const BlockCollateralResult = IDL.Variant({
	Ok: IDL.Null,
	Err: BlockingError
});
export const CancelLimitOrderParams = IDL.Record({ order_id: IDL.Text });
export const SubmitMatchedTradeResult = IDL.Variant({
	Ok: IDL.Bool,
	Err: TradeError
});
export const DepositCollateralParams = IDL.Record({
	deposit_id: IDL.Text,
	asset: Asset,
	amount: IDL.Nat
});
export const LedgerError = IDL.Variant({
	TransferError: IDL.Text,
	InsufficientBalance: IDL.Record({
		balance: IDL.Nat,
		required: IDL.Nat
	}),
	MathOverflow: IDL.Null,
	CallError: IDL.Record({
		method: IDL.Text,
		code: IDL.Int32,
		message: IDL.Text
	}),
	UnsupportedLedger: IDL.Null
});
export const DepositCollateralError = IDL.Variant({
	MathOverflow: IDL.Null,
	Ledger: LedgerError
});
export const DepositCollateralResult = IDL.Variant({
	Ok: IDL.Null,
	Err: DepositCollateralError
});
export const FreezePositionForTransferParams = IDL.Record({
	series_id: IDL.Text,
	user: IDL.Principal,
	transfer_id: IDL.Text
});
export const GetMarginAccountParams = IDL.Record({
	refresh: IDL.Opt(IDL.Bool)
});
export const MarginAccount = IDL.Record({
	required_margin: IDL.Nat,
	reserved_balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat)),
	user: IDL.Principal,
	balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat))
});
export const MarginAccountError = IDL.Variant({
	NoMarginAccountFound: IDL.Null,
	MathOverflow: IDL.Null,
	Ledger: LedgerError
});
export const GetMarginAccountResult = IDL.Variant({
	Ok: MarginAccount,
	Err: MarginAccountError
});
export const Side = IDL.Variant({ Buy: IDL.Null, Sell: IDL.Null });
export const DecimalValue = IDL.Record({
	decimals: IDL.Nat8,
	value: IDL.Nat
});
export const Price = IDL.Record({
	timestamp: IDL.Opt(IDL.Nat64),
	oracle_id: IDL.Opt(IDL.Text),
	decimal: DecimalValue
});
export const LimitOrder = IDL.Record({
	qty: IDL.Int,
	creator: IDL.Principal,
	block_index: IDL.Nat,
	series_id: IDL.Text,
	side: Side,
	order_id: IDL.Text,
	price: Price
});
export const GetPositionParams = IDL.Record({ series_id: IDL.Text });
export const Position = IDL.Record({
	series_id: IDL.Text,
	net_qty: IDL.Int,
	user: IDL.Principal,
	locked_collateral: IDL.Nat
});
export const EventType = IDL.Variant({
	OrderPlaced: IDL.Null,
	Executed: IDL.Null,
	Liquidated: IDL.Null,
	Settled: IDL.Null
});
export const Event = IDL.Record({
	qty: IDL.Int,
	series_id: IDL.Text,
	user: IDL.Principal,
	timestamp: IDL.Nat64,
	event_id: IDL.Nat64,
	price: Price,
	event_type: EventType,
	clearing_id: IDL.Principal
});
export const HttpRequest = IDL.Record({
	url: IDL.Text,
	method: IDL.Text,
	body: IDL.Vec(IDL.Nat8),
	headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))
});
export const HttpResponse = IDL.Record({
	body: IDL.Vec(IDL.Nat8),
	headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
	status_code: IDL.Nat16
});
export const PayoffType = IDL.Variant({
	Put: IDL.Null,
	Binary: IDL.Null,
	Call: IDL.Null
});
export const SettlementAsset = IDL.Variant({
	Icp: IDL.Null,
	CkUsdc: IDL.Null
});
export const Series = IDL.Record({
	title: IDL.Text,
	strike: IDL.Opt(Price),
	creator: IDL.Principal,
	payoff_type: PayoffType,
	expiry_ns: IDL.Nat64,
	series_id: IDL.Text,
	settlement_asset: SettlementAsset,
	underlying: IDL.Text,
	description: IDL.Text,
	created_at_ns: IDL.Nat64,
	price_precision: IDL.Nat8,
	oracle_source: IDL.Text
});
export const SettleSeriesParams = IDL.Record({
	series_id: IDL.Text,
	settlement_price: Price
});
export const SettlementError = IDL.Variant({
	UnsupportedSettlementAsset: IDL.Null,
	MathOverflow: IDL.Null,
	Ledger: LedgerError,
	Common: CommonError
});
export const SettleSeriesResult = IDL.Variant({
	Ok: IDL.Null,
	Err: SettlementError
});
export const Stats = IDL.Record({
	total_users: IDL.Nat64,
	margin_balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat)),
	total_collateral_locked: IDL.Nat,
	total_trades: IDL.Nat64,
	total_series: IDL.Nat64,
	open_interest: IDL.Nat,
	event_counts: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat64))
});
export const SubmitLimitOrderParams = IDL.Record({
	qty: IDL.Int,
	series_id: IDL.Text,
	side: Side,
	order_id: IDL.Text,
	price: Price
});
export const SubmitMarketOrderParams = IDL.Record({
	trade_id: IDL.Text,
	matching_order_id: IDL.Text
});
export const SubmitMatchedTradeParams = IDL.Record({
	qty: IDL.Int,
	trade_id: IDL.Text,
	series_id: IDL.Text,
	seller: IDL.Principal,
	buyer_unblock_amount: IDL.Opt(IDL.Nat),
	buyer: IDL.Principal,
	price: Price,
	seller_unblock_amount: IDL.Opt(IDL.Nat)
});
export const WithdrawCollateralParams = IDL.Record({
	asset: Asset,
	withdrawal_id: IDL.Text,
	amount: IDL.Nat
});
export const WithdrawCollateralError = IDL.Variant({
	InsufficientExcessMargin: IDL.Record({
		requested: IDL.Nat,
		available: IDL.Nat
	}),
	MathOverflow: IDL.Null,
	Ledger: LedgerError
});
export const WithdrawCollateralResult = IDL.Variant({
	Ok: IDL.Null,
	Err: WithdrawCollateralError
});

export const idlService = IDL.Service({
	accept_position_transfer: IDL.Func([PositionProof], [AcceptPositionTransferResult], []),
	block_collateral: IDL.Func([BlockCollateralParams], [BlockCollateralResult], []),
	cancel_limit_order: IDL.Func([CancelLimitOrderParams], [SubmitMatchedTradeResult], []),
	deposit_collateral: IDL.Func([DepositCollateralParams], [DepositCollateralResult], []),
	freeze_position_for_transfer: IDL.Func(
		[FreezePositionForTransferParams],
		[IDL.Opt(PositionProof)],
		[]
	),
	get_margin_account: IDL.Func([GetMarginAccountParams], [GetMarginAccountResult], []),
	get_margin_account_query: IDL.Func([], [GetMarginAccountResult], ['query']),
	get_orders: IDL.Func([], [IDL.Vec(LimitOrder)], ['query']),
	get_position: IDL.Func([GetPositionParams], [IDL.Opt(Position)], ['query']),
	get_positions: IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Position))], ['query']),
	get_trade_history: IDL.Func([], [IDL.Vec(Event)], ['query']),
	http_request: IDL.Func([HttpRequest], [HttpResponse], ['query']),
	list_series: IDL.Func([], [IDL.Vec(Series)], ['query']),
	metrics: IDL.Func([], [IDL.Text], ['query']),
	set_registry_canister: IDL.Func([IDL.Principal], [], []),
	settle_series: IDL.Func([SettleSeriesParams], [SettleSeriesResult], []),
	stats: IDL.Func([], [Stats], ['query']),
	submit_limit_order: IDL.Func([SubmitLimitOrderParams], [SubmitMatchedTradeResult], []),
	submit_market_order: IDL.Func([SubmitMarketOrderParams], [SubmitMatchedTradeResult], []),
	submit_matched_trade: IDL.Func([SubmitMatchedTradeParams], [SubmitMatchedTradeResult], []),
	unblock_collateral: IDL.Func([BlockCollateralParams], [BlockCollateralResult], []),
	withdraw_collateral: IDL.Func([WithdrawCollateralParams], [WithdrawCollateralResult], [])
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
	const PositionProof = IDL.Record({
		qty: IDL.Int,
		signature: IDL.Vec(IDL.Nat8),
		series_id: IDL.Text,
		user: IDL.Principal,
		transfer_id: IDL.Text,
		clearing_id: IDL.Principal
	});
	const CommonError = IDL.Variant({
		Internal: IDL.Text,
		MathOverflow: IDL.Null,
		Unauthorized: IDL.Null,
		RegistryNotSet: IDL.Null
	});
	const TradeError = IDL.Variant({
		OrderNotFound: IDL.Text,
		RegistryError: IDL.Text,
		InsufficientMargin: IDL.Record({
			balance: IDL.Nat,
			user: IDL.Principal,
			required: IDL.Nat
		}),
		NotOrderCreator: IDL.Null,
		SeriesNotFound: IDL.Text,
		Common: CommonError
	});
	const AcceptPositionTransferResult = IDL.Variant({
		Ok: IDL.Bool,
		Err: TradeError
	});
	const Asset = IDL.Variant({ Icrc: IDL.Principal });
	const BlockCollateralParams = IDL.Record({
		asset: Asset,
		amount: IDL.Nat
	});
	const BlockingError = IDL.Variant({
		InsufficientAvailableBalance: IDL.Record({
			requested: IDL.Nat,
			available: IDL.Nat
		}),
		MathOverflow: IDL.Null,
		InsufficientReservedBalance: IDL.Record({
			requested: IDL.Nat,
			reserved: IDL.Nat
		})
	});
	const BlockCollateralResult = IDL.Variant({
		Ok: IDL.Null,
		Err: BlockingError
	});
	const CancelLimitOrderParams = IDL.Record({ order_id: IDL.Text });
	const SubmitMatchedTradeResult = IDL.Variant({
		Ok: IDL.Bool,
		Err: TradeError
	});
	const DepositCollateralParams = IDL.Record({
		deposit_id: IDL.Text,
		asset: Asset,
		amount: IDL.Nat
	});
	const LedgerError = IDL.Variant({
		TransferError: IDL.Text,
		InsufficientBalance: IDL.Record({
			balance: IDL.Nat,
			required: IDL.Nat
		}),
		MathOverflow: IDL.Null,
		CallError: IDL.Record({
			method: IDL.Text,
			code: IDL.Int32,
			message: IDL.Text
		}),
		UnsupportedLedger: IDL.Null
	});
	const DepositCollateralError = IDL.Variant({
		MathOverflow: IDL.Null,
		Ledger: LedgerError
	});
	const DepositCollateralResult = IDL.Variant({
		Ok: IDL.Null,
		Err: DepositCollateralError
	});
	const FreezePositionForTransferParams = IDL.Record({
		series_id: IDL.Text,
		user: IDL.Principal,
		transfer_id: IDL.Text
	});
	const GetMarginAccountParams = IDL.Record({ refresh: IDL.Opt(IDL.Bool) });
	const MarginAccount = IDL.Record({
		required_margin: IDL.Nat,
		reserved_balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat)),
		user: IDL.Principal,
		balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat))
	});
	const MarginAccountError = IDL.Variant({
		NoMarginAccountFound: IDL.Null,
		MathOverflow: IDL.Null,
		Ledger: LedgerError
	});
	const GetMarginAccountResult = IDL.Variant({
		Ok: MarginAccount,
		Err: MarginAccountError
	});
	const Side = IDL.Variant({ Buy: IDL.Null, Sell: IDL.Null });
	const DecimalValue = IDL.Record({ decimals: IDL.Nat8, value: IDL.Nat });
	const Price = IDL.Record({
		timestamp: IDL.Opt(IDL.Nat64),
		oracle_id: IDL.Opt(IDL.Text),
		decimal: DecimalValue
	});
	const LimitOrder = IDL.Record({
		qty: IDL.Int,
		creator: IDL.Principal,
		block_index: IDL.Nat,
		series_id: IDL.Text,
		side: Side,
		order_id: IDL.Text,
		price: Price
	});
	const GetPositionParams = IDL.Record({ series_id: IDL.Text });
	const Position = IDL.Record({
		series_id: IDL.Text,
		net_qty: IDL.Int,
		user: IDL.Principal,
		locked_collateral: IDL.Nat
	});
	const EventType = IDL.Variant({
		OrderPlaced: IDL.Null,
		Executed: IDL.Null,
		Liquidated: IDL.Null,
		Settled: IDL.Null
	});
	const Event = IDL.Record({
		qty: IDL.Int,
		series_id: IDL.Text,
		user: IDL.Principal,
		timestamp: IDL.Nat64,
		event_id: IDL.Nat64,
		price: Price,
		event_type: EventType,
		clearing_id: IDL.Principal
	});
	const HttpRequest = IDL.Record({
		url: IDL.Text,
		method: IDL.Text,
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))
	});
	const HttpResponse = IDL.Record({
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
		status_code: IDL.Nat16
	});
	const PayoffType = IDL.Variant({
		Put: IDL.Null,
		Binary: IDL.Null,
		Call: IDL.Null
	});
	const SettlementAsset = IDL.Variant({
		Icp: IDL.Null,
		CkUsdc: IDL.Null
	});
	const Series = IDL.Record({
		title: IDL.Text,
		strike: IDL.Opt(Price),
		creator: IDL.Principal,
		payoff_type: PayoffType,
		expiry_ns: IDL.Nat64,
		series_id: IDL.Text,
		settlement_asset: SettlementAsset,
		underlying: IDL.Text,
		description: IDL.Text,
		created_at_ns: IDL.Nat64,
		price_precision: IDL.Nat8,
		oracle_source: IDL.Text
	});
	const SettleSeriesParams = IDL.Record({
		series_id: IDL.Text,
		settlement_price: Price
	});
	const SettlementError = IDL.Variant({
		UnsupportedSettlementAsset: IDL.Null,
		MathOverflow: IDL.Null,
		Ledger: LedgerError,
		Common: CommonError
	});
	const SettleSeriesResult = IDL.Variant({
		Ok: IDL.Null,
		Err: SettlementError
	});
	const Stats = IDL.Record({
		total_users: IDL.Nat64,
		margin_balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat)),
		total_collateral_locked: IDL.Nat,
		total_trades: IDL.Nat64,
		total_series: IDL.Nat64,
		open_interest: IDL.Nat,
		event_counts: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat64))
	});
	const SubmitLimitOrderParams = IDL.Record({
		qty: IDL.Int,
		series_id: IDL.Text,
		side: Side,
		order_id: IDL.Text,
		price: Price
	});
	const SubmitMarketOrderParams = IDL.Record({
		trade_id: IDL.Text,
		matching_order_id: IDL.Text
	});
	const SubmitMatchedTradeParams = IDL.Record({
		qty: IDL.Int,
		trade_id: IDL.Text,
		series_id: IDL.Text,
		seller: IDL.Principal,
		buyer_unblock_amount: IDL.Opt(IDL.Nat),
		buyer: IDL.Principal,
		price: Price,
		seller_unblock_amount: IDL.Opt(IDL.Nat)
	});
	const WithdrawCollateralParams = IDL.Record({
		asset: Asset,
		withdrawal_id: IDL.Text,
		amount: IDL.Nat
	});
	const WithdrawCollateralError = IDL.Variant({
		InsufficientExcessMargin: IDL.Record({
			requested: IDL.Nat,
			available: IDL.Nat
		}),
		MathOverflow: IDL.Null,
		Ledger: LedgerError
	});
	const WithdrawCollateralResult = IDL.Variant({
		Ok: IDL.Null,
		Err: WithdrawCollateralError
	});

	return IDL.Service({
		accept_position_transfer: IDL.Func([PositionProof], [AcceptPositionTransferResult], []),
		block_collateral: IDL.Func([BlockCollateralParams], [BlockCollateralResult], []),
		cancel_limit_order: IDL.Func([CancelLimitOrderParams], [SubmitMatchedTradeResult], []),
		deposit_collateral: IDL.Func([DepositCollateralParams], [DepositCollateralResult], []),
		freeze_position_for_transfer: IDL.Func(
			[FreezePositionForTransferParams],
			[IDL.Opt(PositionProof)],
			[]
		),
		get_margin_account: IDL.Func([GetMarginAccountParams], [GetMarginAccountResult], []),
		get_margin_account_query: IDL.Func([], [GetMarginAccountResult], ['query']),
		get_orders: IDL.Func([], [IDL.Vec(LimitOrder)], ['query']),
		get_position: IDL.Func([GetPositionParams], [IDL.Opt(Position)], ['query']),
		get_positions: IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Position))], ['query']),
		get_trade_history: IDL.Func([], [IDL.Vec(Event)], ['query']),
		http_request: IDL.Func([HttpRequest], [HttpResponse], ['query']),
		list_series: IDL.Func([], [IDL.Vec(Series)], ['query']),
		metrics: IDL.Func([], [IDL.Text], ['query']),
		set_registry_canister: IDL.Func([IDL.Principal], [], []),
		settle_series: IDL.Func([SettleSeriesParams], [SettleSeriesResult], []),
		stats: IDL.Func([], [Stats], ['query']),
		submit_limit_order: IDL.Func([SubmitLimitOrderParams], [SubmitMatchedTradeResult], []),
		submit_market_order: IDL.Func([SubmitMarketOrderParams], [SubmitMatchedTradeResult], []),
		submit_matched_trade: IDL.Func([SubmitMatchedTradeParams], [SubmitMatchedTradeResult], []),
		unblock_collateral: IDL.Func([BlockCollateralParams], [BlockCollateralResult], []),
		withdraw_collateral: IDL.Func([WithdrawCollateralParams], [WithdrawCollateralResult], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
