/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.1.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DecimalValue = IDL.Record({
	decimals: IDL.Nat8,
	value: IDL.Nat
});
export const Price = IDL.Record({
	timestamp: IDL.Opt(IDL.Nat64),
	oracle_id: IDL.Opt(IDL.Text),
	decimal: DecimalValue
});
export const PositionProof = IDL.Record({
	qty: IDL.Int,
	signature: IDL.Vec(IDL.Nat8),
	outcome_id: IDL.Opt(IDL.Text),
	series_id: IDL.Text,
	user: IDL.Principal,
	transfer_id: IDL.Text,
	valuation_price: IDL.Opt(Price),
	clearing_id: IDL.Principal
});
export const CommonError = IDL.Variant({
	Internal: IDL.Text,
	InvalidInput: IDL.Text,
	MathOverflow: IDL.Null,
	Unauthorized: IDL.Null,
	RegistryNotSet: IDL.Null
});
export const TradeError = IDL.Variant({
	OrderNotFound: IDL.Text,
	RegistryError: IDL.Text,
	InsufficientMargin: IDL.Record({
		balance: IDL.Nat,
		user: IDL.Principal,
		required: IDL.Nat
	}),
	NotOrderCreator: IDL.Null,
	SeriesNotFound: IDL.Text,
	Common: CommonError
});
export const AcceptPositionTransferResult = IDL.Variant({
	Ok: IDL.Bool,
	Err: TradeError
});
export const CancelFundWithdrawalParams = IDL.Record({
	request_id: IDL.Text
});
export const CancelFundWithdrawalError = IDL.Variant({
	PlanNotFound: IDL.Null,
	InvalidPlanStatus: IDL.Null,
	Common: CommonError
});
export const CancelFundWithdrawalResult = IDL.Variant({
	Ok: IDL.Null,
	Err: CancelFundWithdrawalError
});
export const CancelLimitOrderParams = IDL.Record({ order_id: IDL.Text });
export const SubmitMatchedTradeResult = IDL.Variant({
	Ok: IDL.Bool,
	Err: TradeError
});
export const DepositCollateralParams = IDL.Record({
	deposit_id: IDL.Text,
	asset_id: IDL.Text,
	amount: IDL.Nat
});
export const AssetError = IDL.Variant({
	TransferError: IDL.Text,
	InsufficientBalance: IDL.Record({
		balance: IDL.Nat,
		required: IDL.Nat
	}),
	MathOverflow: IDL.Null,
	InvalidAssetId: IDL.Text,
	CallError: IDL.Record({
		method: IDL.Text,
		code: IDL.Int32,
		message: IDL.Text
	}),
	InvalidAssetForHandler: IDL.Null,
	UnsupportedAsset: IDL.Null
});
export const DepositCollateralError = IDL.Variant({
	MathOverflow: IDL.Null,
	Asset: AssetError
});
export const DepositCollateralResult = IDL.Variant({
	Ok: IDL.Null,
	Err: DepositCollateralError
});
export const FreezePositionForTransferParams = IDL.Record({
	outcome_id: IDL.Opt(IDL.Text),
	series_id: IDL.Text,
	user: IDL.Principal,
	transfer_id: IDL.Text,
	valuation_price: IDL.Opt(Price)
});
export const GetAccountStateParams = IDL.Record({
	refresh: IDL.Opt(IDL.Bool)
});
export const AssetWorth = IDL.Record({
	pre_haircut_value_usd: IDL.Nat,
	haircut_bps: IDL.Nat16,
	balance: IDL.Nat,
	value_usd: IDL.Nat,
	asset_id: IDL.Text
});
export const AccountState = IDL.Record({
	user: IDL.Principal,
	cash_balance_usd: IDL.Int,
	reserved_margin_usd: IDL.Nat,
	collateral_balances: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))
});
export const AccountStateResponse = IDL.Record({
	assets: IDL.Vec(AssetWorth),
	available_equity_usd: IDL.Int,
	state: AccountState,
	total_equity_usd: IDL.Nat
});
export const AccountStateError = IDL.Variant({
	MathOverflow: IDL.Null,
	Asset: AssetError,
	NoAccountStateFound: IDL.Null
});
export const GetAccountStateResult = IDL.Variant({
	Ok: AccountStateResponse,
	Err: AccountStateError
});
export const AssetMetrics = IDL.Record({
	haircut_bps: IDL.Nat16,
	latest_transfer_fee: IDL.Opt(IDL.Nat),
	insurance_fee_ratio: IDL.Opt(IDL.Nat16),
	last_updated_ns: IDL.Opt(IDL.Nat64),
	protocol_fee_ratio: IDL.Opt(IDL.Nat16),
	price_usd: DecimalValue
});
export const ErcToken = IDL.Record({
	decimals: IDL.Nat8,
	token_address: IDL.Text,
	chain_id: IDL.Nat64
});
export const NativeEvmAsset = IDL.Record({
	decimals: IDL.Nat8,
	chain_id: IDL.Nat64
});
export const Asset = IDL.Variant({
	Erc20: ErcToken,
	Icrc: IDL.Principal,
	NativeEvm: NativeEvmAsset
});
export const CollateralAssetConfig = IDL.Record({
	decimals: IDL.Nat8,
	asset: Asset,
	is_enabled: IDL.Bool,
	oracle_id: IDL.Opt(IDL.Text),
	asset_id: IDL.Text,
	symbol: IDL.Text
});
export const CollateralAssetInfo = IDL.Record({
	metrics: IDL.Opt(AssetMetrics),
	config: CollateralAssetConfig
});
export const GetFundsResult = IDL.Record({
	insurance_fund: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
	treasury: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))
});
export const Side = IDL.Variant({ Buy: IDL.Null, Sell: IDL.Null });
export const LimitOrder = IDL.Record({
	qty: IDL.Int,
	creator: IDL.Principal,
	outcome_id: IDL.Opt(IDL.Text),
	blocked_margin_usd: IDL.Nat,
	series_id: IDL.Text,
	side: Side,
	order_id: IDL.Text,
	price: Price
});
export const GetPositionParams = IDL.Record({
	outcome_id: IDL.Opt(IDL.Text),
	series_id: IDL.Text
});
export const Position = IDL.Record({
	outcome_id: IDL.Opt(IDL.Text),
	series_id: IDL.Text,
	net_qty: IDL.Int,
	user: IDL.Principal,
	reserved_margin_usd: IDL.Nat
});
export const PlanStatus = IDL.Variant({
	Finalised: IDL.Null,
	Planned: IDL.Null,
	Executing: IDL.Null
});
export const PaymentIdempotency = IDL.Variant({
	IcrcCreatedAtTimeNs: IDL.Nat64
});
export const SettlementPosition = IDL.Record({
	outcome_id: IDL.Opt(IDL.Text),
	net_qty: IDL.Int,
	user: IDL.Principal,
	reserved_margin_usd: IDL.Nat,
	cashflow_usd: IDL.Int
});
export const SettlementInput = IDL.Variant({
	Price: Price,
	Outcome: IDL.Text
});
export const SettlementPlan = IDL.Record({
	status: PlanStatus,
	idempotency_ns: PaymentIdempotency,
	series_id: IDL.Text,
	fee_usd: IDL.Nat,
	accounting_cursor: IDL.Nat64,
	insurance_fee_usd: IDL.Nat,
	positions: IDL.Vec(SettlementPosition),
	accounting_applied: IDL.Bool,
	oracle_source: IDL.Text,
	settlement: SettlementInput
});
export const SettlementStatusView = IDL.Record({
	status: PlanStatus,
	series_id: IDL.Text,
	fee_usd: IDL.Nat,
	accounting_cursor: IDL.Nat64,
	insurance_fee_usd: IDL.Nat,
	accounting_applied: IDL.Bool,
	oracle_source: IDL.Text,
	total_positions: IDL.Nat64,
	settlement: SettlementInput
});
export const EventType = IDL.Variant({
	OrderPlaced: IDL.Null,
	Executed: IDL.Null,
	Liquidated: IDL.Null,
	Settled: IDL.Null
});
export const Event = IDL.Record({
	qty: IDL.Int,
	series_id: IDL.Text,
	user: IDL.Principal,
	timestamp: IDL.Nat64,
	event_id: IDL.Nat64,
	price: Price,
	event_type: EventType,
	clearing_id: IDL.Principal
});
export const HttpRequest = IDL.Record({
	url: IDL.Text,
	method: IDL.Text,
	body: IDL.Vec(IDL.Nat8),
	headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))
});
export const HttpResponse = IDL.Record({
	body: IDL.Vec(IDL.Nat8),
	headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
	status_code: IDL.Nat16
});
export const ListOrdersParams = IDL.Record({ series_id: IDL.Opt(IDL.Text) });
export const PayoffType = IDL.Variant({
	Put: IDL.Null,
	Binary: IDL.Null,
	Call: IDL.Null,
	Categorical: IDL.Null
});
export const FiatUnit = IDL.Variant({
	Chf: IDL.Null,
	Eur: IDL.Null,
	Gbp: IDL.Null,
	Usd: IDL.Null
});
export const NonMonetaryUnit = IDL.Variant({ Points: IDL.Null });
export const PayoutUnit = IDL.Variant({
	Fiat: FiatUnit,
	Asset: Asset,
	NonMonetary: NonMonetaryUnit
});
export const Description = IDL.Record({
	html: IDL.Opt(IDL.Text),
	markdown: IDL.Opt(IDL.Text),
	plain: IDL.Text
});
export const Outcome = IDL.Record({
	id: IDL.Text,
	title: IDL.Text,
	description: IDL.Opt(Description),
	icon_url: IDL.Opt(IDL.Text)
});
export const Series = IDL.Record({
	title: IDL.Text,
	strike: IDL.Opt(Price),
	creator: IDL.Principal,
	payoff_type: PayoffType,
	payout_unit: PayoutUnit,
	expiry_ns: IDL.Nat64,
	banner_url: IDL.Opt(IDL.Text),
	series_id: IDL.Text,
	underlying: IDL.Text,
	description: Description,
	outcomes: IDL.Opt(IDL.Vec(Outcome)),
	created_at_ns: IDL.Nat64,
	icon_url: IDL.Opt(IDL.Text),
	price_precision: IDL.Nat8,
	oracle_source: IDL.Text
});
export const SettlementError = IDL.Variant({
	InconsistentSettlementPrice: IDL.Record({
		requested: Price,
		existing: Price
	}),
	MathOverflow: IDL.Null,
	SolvencyViolation: IDL.Record({
		total_net_payoff: IDL.Nat,
		total_collateral_usd: IDL.Nat
	}),
	Asset: AssetError,
	Common: CommonError
});
export const SettleSeriesResult = IDL.Variant({
	Ok: IDL.Null,
	Err: SettlementError,
	Processing: IDL.Null
});
export const SettleSeriesParams = IDL.Record({
	series_id: IDL.Text,
	settlement: SettlementInput
});
export const Stats = IDL.Record({
	total_users: IDL.Nat64,
	margin_balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat)),
	total_collateral_locked: IDL.Nat,
	total_trades: IDL.Nat64,
	total_series: IDL.Nat64,
	open_interest: IDL.Nat,
	event_counts: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat64))
});
export const SubmitLimitOrderParams = IDL.Record({
	qty: IDL.Int,
	outcome_id: IDL.Opt(IDL.Text),
	series_id: IDL.Text,
	side: Side,
	order_id: IDL.Text,
	price: Price
});
export const SubmitMarketOrderParams = IDL.Record({
	trade_id: IDL.Text,
	matching_order_id: IDL.Text
});
export const SubmitMatchedTradeParams = IDL.Record({
	qty: IDL.Int,
	trade_id: IDL.Text,
	outcome_id: IDL.Opt(IDL.Text),
	series_id: IDL.Text,
	seller: IDL.Principal,
	buyer_unblock_amount: IDL.Opt(IDL.Nat),
	buyer: IDL.Principal,
	price: Price,
	seller_unblock_amount: IDL.Opt(IDL.Nat)
});
export const UpdateAssetMetricsParams = IDL.Record({
	metrics: AssetMetrics,
	asset_id: IDL.Text
});
export const UpdateAssetPriceParams = IDL.Record({
	price: Price,
	asset_id: IDL.Text
});
export const UpdateAssetPriceError = IDL.Variant({
	AssetNotFound: IDL.Null,
	AssetMetricsNotInitialized: IDL.Null,
	OracleNotConfigured: IDL.Null,
	Common: CommonError
});
export const UpdateAssetPriceResult = IDL.Variant({
	Ok: IDL.Null,
	Err: UpdateAssetPriceError
});
export const UpdateCollateralAssetParams = IDL.Record({
	config: CollateralAssetConfig
});
export const Config = IDL.Record({
	insurance_fund_fee_ratio: IDL.Nat16,
	signer_canister: IDL.Principal,
	evm_rpc: IDL.Principal,
	protocol_fee_ratio: IDL.Nat16
});
export const WithdrawCollateralParams = IDL.Record({
	withdrawal_id: IDL.Text,
	asset_id: IDL.Text,
	amount: IDL.Nat
});
export const WithdrawCollateralError = IDL.Variant({
	InsufficientExcessMargin: IDL.Record({
		requested: IDL.Nat,
		available: IDL.Nat
	}),
	MathOverflow: IDL.Null,
	Asset: AssetError
});
export const WithdrawCollateralResult = IDL.Variant({
	Ok: IDL.Null,
	Err: WithdrawCollateralError
});
export const FundType = IDL.Variant({
	Insurance: IDL.Null,
	Treasury: IDL.Null
});
export const WithdrawFundParams = IDL.Record({
	to: IDL.Principal,
	request_id: IDL.Text,
	fund_type: FundType,
	asset_id: IDL.Text,
	amount: IDL.Nat
});
export const WithdrawFundError = IDL.Variant({
	TransferFailed: IDL.Text,
	InsufficientFunds: IDL.Null,
	Common: CommonError
});
export const WithdrawFundResult = IDL.Variant({
	Ok: IDL.Nat,
	Err: WithdrawFundError
});

export const idlService = IDL.Service({
	accept_position_transfer: IDL.Func([PositionProof], [AcceptPositionTransferResult], []),
	cancel_fund_withdrawal: IDL.Func([CancelFundWithdrawalParams], [CancelFundWithdrawalResult], []),
	cancel_limit_order: IDL.Func([CancelLimitOrderParams], [SubmitMatchedTradeResult], []),
	debug_get_registry_canister: IDL.Func([], [IDL.Principal], ['query']),
	deposit_collateral: IDL.Func([DepositCollateralParams], [DepositCollateralResult], []),
	freeze_position_for_transfer: IDL.Func(
		[FreezePositionForTransferParams],
		[IDL.Opt(PositionProof)],
		[]
	),
	get_account_state: IDL.Func([GetAccountStateParams], [GetAccountStateResult], []),
	get_account_state_query: IDL.Func([], [GetAccountStateResult], ['query']),
	get_collateral_assets: IDL.Func([], [IDL.Vec(CollateralAssetInfo)], ['query']),
	get_funds: IDL.Func([], [GetFundsResult], ['query']),
	get_orders: IDL.Func([], [IDL.Vec(LimitOrder)], ['query']),
	get_position: IDL.Func([GetPositionParams], [IDL.Opt(Position)], ['query']),
	get_positions: IDL.Func([], [IDL.Vec(Position)], ['query']),
	get_settlement_plan: IDL.Func([IDL.Text], [IDL.Opt(SettlementPlan)], ['query']),
	get_settlement_status: IDL.Func([IDL.Text], [IDL.Opt(SettlementStatusView)], ['query']),
	get_trade_history: IDL.Func([], [IDL.Vec(Event)], ['query']),
	http_request: IDL.Func([HttpRequest], [HttpResponse], ['query']),
	list_collateral_assets: IDL.Func([], [IDL.Vec(CollateralAssetConfig)], ['query']),
	list_orders: IDL.Func([ListOrdersParams], [IDL.Vec(LimitOrder)], ['query']),
	list_series: IDL.Func([], [IDL.Vec(Series)], ['query']),
	metrics: IDL.Func([], [IDL.Text], ['query']),
	mint_complete_set: IDL.Func([IDL.Text, IDL.Int], [SubmitMatchedTradeResult], []),
	redeem_complete_set: IDL.Func([IDL.Text, IDL.Int], [SubmitMatchedTradeResult], []),
	resume_settlement: IDL.Func([IDL.Text], [SettleSeriesResult], []),
	set_registry_canister: IDL.Func([IDL.Principal], [], []),
	settle_series: IDL.Func([SettleSeriesParams], [SettleSeriesResult], []),
	stats: IDL.Func([], [Stats], ['query']),
	submit_limit_order: IDL.Func([SubmitLimitOrderParams], [SubmitMatchedTradeResult], []),
	submit_market_order: IDL.Func([SubmitMarketOrderParams], [SubmitMatchedTradeResult], []),
	submit_matched_trade: IDL.Func([SubmitMatchedTradeParams], [SubmitMatchedTradeResult], []),
	update_asset_metrics: IDL.Func([UpdateAssetMetricsParams], [], []),
	update_asset_price: IDL.Func([UpdateAssetPriceParams], [UpdateAssetPriceResult], []),
	update_collateral_asset: IDL.Func([UpdateCollateralAssetParams], [], []),
	update_config: IDL.Func([Config], [], []),
	withdraw_collateral: IDL.Func([WithdrawCollateralParams], [WithdrawCollateralResult], []),
	withdraw_fund: IDL.Func([WithdrawFundParams], [WithdrawFundResult], [])
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
	const DecimalValue = IDL.Record({ decimals: IDL.Nat8, value: IDL.Nat });
	const Price = IDL.Record({
		timestamp: IDL.Opt(IDL.Nat64),
		oracle_id: IDL.Opt(IDL.Text),
		decimal: DecimalValue
	});
	const PositionProof = IDL.Record({
		qty: IDL.Int,
		signature: IDL.Vec(IDL.Nat8),
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		user: IDL.Principal,
		transfer_id: IDL.Text,
		valuation_price: IDL.Opt(Price),
		clearing_id: IDL.Principal
	});
	const CommonError = IDL.Variant({
		Internal: IDL.Text,
		InvalidInput: IDL.Text,
		MathOverflow: IDL.Null,
		Unauthorized: IDL.Null,
		RegistryNotSet: IDL.Null
	});
	const TradeError = IDL.Variant({
		OrderNotFound: IDL.Text,
		RegistryError: IDL.Text,
		InsufficientMargin: IDL.Record({
			balance: IDL.Nat,
			user: IDL.Principal,
			required: IDL.Nat
		}),
		NotOrderCreator: IDL.Null,
		SeriesNotFound: IDL.Text,
		Common: CommonError
	});
	const AcceptPositionTransferResult = IDL.Variant({
		Ok: IDL.Bool,
		Err: TradeError
	});
	const CancelFundWithdrawalParams = IDL.Record({ request_id: IDL.Text });
	const CancelFundWithdrawalError = IDL.Variant({
		PlanNotFound: IDL.Null,
		InvalidPlanStatus: IDL.Null,
		Common: CommonError
	});
	const CancelFundWithdrawalResult = IDL.Variant({
		Ok: IDL.Null,
		Err: CancelFundWithdrawalError
	});
	const CancelLimitOrderParams = IDL.Record({ order_id: IDL.Text });
	const SubmitMatchedTradeResult = IDL.Variant({
		Ok: IDL.Bool,
		Err: TradeError
	});
	const DepositCollateralParams = IDL.Record({
		deposit_id: IDL.Text,
		asset_id: IDL.Text,
		amount: IDL.Nat
	});
	const AssetError = IDL.Variant({
		TransferError: IDL.Text,
		InsufficientBalance: IDL.Record({
			balance: IDL.Nat,
			required: IDL.Nat
		}),
		MathOverflow: IDL.Null,
		InvalidAssetId: IDL.Text,
		CallError: IDL.Record({
			method: IDL.Text,
			code: IDL.Int32,
			message: IDL.Text
		}),
		InvalidAssetForHandler: IDL.Null,
		UnsupportedAsset: IDL.Null
	});
	const DepositCollateralError = IDL.Variant({
		MathOverflow: IDL.Null,
		Asset: AssetError
	});
	const DepositCollateralResult = IDL.Variant({
		Ok: IDL.Null,
		Err: DepositCollateralError
	});
	const FreezePositionForTransferParams = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		user: IDL.Principal,
		transfer_id: IDL.Text,
		valuation_price: IDL.Opt(Price)
	});
	const GetAccountStateParams = IDL.Record({ refresh: IDL.Opt(IDL.Bool) });
	const AssetWorth = IDL.Record({
		pre_haircut_value_usd: IDL.Nat,
		haircut_bps: IDL.Nat16,
		balance: IDL.Nat,
		value_usd: IDL.Nat,
		asset_id: IDL.Text
	});
	const AccountState = IDL.Record({
		user: IDL.Principal,
		cash_balance_usd: IDL.Int,
		reserved_margin_usd: IDL.Nat,
		collateral_balances: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))
	});
	const AccountStateResponse = IDL.Record({
		assets: IDL.Vec(AssetWorth),
		available_equity_usd: IDL.Int,
		state: AccountState,
		total_equity_usd: IDL.Nat
	});
	const AccountStateError = IDL.Variant({
		MathOverflow: IDL.Null,
		Asset: AssetError,
		NoAccountStateFound: IDL.Null
	});
	const GetAccountStateResult = IDL.Variant({
		Ok: AccountStateResponse,
		Err: AccountStateError
	});
	const AssetMetrics = IDL.Record({
		haircut_bps: IDL.Nat16,
		latest_transfer_fee: IDL.Opt(IDL.Nat),
		insurance_fee_ratio: IDL.Opt(IDL.Nat16),
		last_updated_ns: IDL.Opt(IDL.Nat64),
		protocol_fee_ratio: IDL.Opt(IDL.Nat16),
		price_usd: DecimalValue
	});
	const ErcToken = IDL.Record({
		decimals: IDL.Nat8,
		token_address: IDL.Text,
		chain_id: IDL.Nat64
	});
	const NativeEvmAsset = IDL.Record({
		decimals: IDL.Nat8,
		chain_id: IDL.Nat64
	});
	const Asset = IDL.Variant({
		Erc20: ErcToken,
		Icrc: IDL.Principal,
		NativeEvm: NativeEvmAsset
	});
	const CollateralAssetConfig = IDL.Record({
		decimals: IDL.Nat8,
		asset: Asset,
		is_enabled: IDL.Bool,
		oracle_id: IDL.Opt(IDL.Text),
		asset_id: IDL.Text,
		symbol: IDL.Text
	});
	const CollateralAssetInfo = IDL.Record({
		metrics: IDL.Opt(AssetMetrics),
		config: CollateralAssetConfig
	});
	const GetFundsResult = IDL.Record({
		insurance_fund: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
		treasury: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))
	});
	const Side = IDL.Variant({ Buy: IDL.Null, Sell: IDL.Null });
	const LimitOrder = IDL.Record({
		qty: IDL.Int,
		creator: IDL.Principal,
		outcome_id: IDL.Opt(IDL.Text),
		blocked_margin_usd: IDL.Nat,
		series_id: IDL.Text,
		side: Side,
		order_id: IDL.Text,
		price: Price
	});
	const GetPositionParams = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text
	});
	const Position = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		net_qty: IDL.Int,
		user: IDL.Principal,
		reserved_margin_usd: IDL.Nat
	});
	const PlanStatus = IDL.Variant({
		Finalised: IDL.Null,
		Planned: IDL.Null,
		Executing: IDL.Null
	});
	const PaymentIdempotency = IDL.Variant({ IcrcCreatedAtTimeNs: IDL.Nat64 });
	const SettlementPosition = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		net_qty: IDL.Int,
		user: IDL.Principal,
		reserved_margin_usd: IDL.Nat,
		cashflow_usd: IDL.Int
	});
	const SettlementInput = IDL.Variant({
		Price: Price,
		Outcome: IDL.Text
	});
	const SettlementPlan = IDL.Record({
		status: PlanStatus,
		idempotency_ns: PaymentIdempotency,
		series_id: IDL.Text,
		fee_usd: IDL.Nat,
		accounting_cursor: IDL.Nat64,
		insurance_fee_usd: IDL.Nat,
		positions: IDL.Vec(SettlementPosition),
		accounting_applied: IDL.Bool,
		oracle_source: IDL.Text,
		settlement: SettlementInput
	});
	const SettlementStatusView = IDL.Record({
		status: PlanStatus,
		series_id: IDL.Text,
		fee_usd: IDL.Nat,
		accounting_cursor: IDL.Nat64,
		insurance_fee_usd: IDL.Nat,
		accounting_applied: IDL.Bool,
		oracle_source: IDL.Text,
		total_positions: IDL.Nat64,
		settlement: SettlementInput
	});
	const EventType = IDL.Variant({
		OrderPlaced: IDL.Null,
		Executed: IDL.Null,
		Liquidated: IDL.Null,
		Settled: IDL.Null
	});
	const Event = IDL.Record({
		qty: IDL.Int,
		series_id: IDL.Text,
		user: IDL.Principal,
		timestamp: IDL.Nat64,
		event_id: IDL.Nat64,
		price: Price,
		event_type: EventType,
		clearing_id: IDL.Principal
	});
	const HttpRequest = IDL.Record({
		url: IDL.Text,
		method: IDL.Text,
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))
	});
	const HttpResponse = IDL.Record({
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
		status_code: IDL.Nat16
	});
	const ListOrdersParams = IDL.Record({ series_id: IDL.Opt(IDL.Text) });
	const PayoffType = IDL.Variant({
		Put: IDL.Null,
		Binary: IDL.Null,
		Call: IDL.Null,
		Categorical: IDL.Null
	});
	const FiatUnit = IDL.Variant({
		Chf: IDL.Null,
		Eur: IDL.Null,
		Gbp: IDL.Null,
		Usd: IDL.Null
	});
	const NonMonetaryUnit = IDL.Variant({ Points: IDL.Null });
	const PayoutUnit = IDL.Variant({
		Fiat: FiatUnit,
		Asset: Asset,
		NonMonetary: NonMonetaryUnit
	});
	const Description = IDL.Record({
		html: IDL.Opt(IDL.Text),
		markdown: IDL.Opt(IDL.Text),
		plain: IDL.Text
	});
	const Outcome = IDL.Record({
		id: IDL.Text,
		title: IDL.Text,
		description: IDL.Opt(Description),
		icon_url: IDL.Opt(IDL.Text)
	});
	const Series = IDL.Record({
		title: IDL.Text,
		strike: IDL.Opt(Price),
		creator: IDL.Principal,
		payoff_type: PayoffType,
		payout_unit: PayoutUnit,
		expiry_ns: IDL.Nat64,
		banner_url: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		underlying: IDL.Text,
		description: Description,
		outcomes: IDL.Opt(IDL.Vec(Outcome)),
		created_at_ns: IDL.Nat64,
		icon_url: IDL.Opt(IDL.Text),
		price_precision: IDL.Nat8,
		oracle_source: IDL.Text
	});
	const SettlementError = IDL.Variant({
		InconsistentSettlementPrice: IDL.Record({
			requested: Price,
			existing: Price
		}),
		MathOverflow: IDL.Null,
		SolvencyViolation: IDL.Record({
			total_net_payoff: IDL.Nat,
			total_collateral_usd: IDL.Nat
		}),
		Asset: AssetError,
		Common: CommonError
	});
	const SettleSeriesResult = IDL.Variant({
		Ok: IDL.Null,
		Err: SettlementError,
		Processing: IDL.Null
	});
	const SettleSeriesParams = IDL.Record({
		series_id: IDL.Text,
		settlement: SettlementInput
	});
	const Stats = IDL.Record({
		total_users: IDL.Nat64,
		margin_balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat)),
		total_collateral_locked: IDL.Nat,
		total_trades: IDL.Nat64,
		total_series: IDL.Nat64,
		open_interest: IDL.Nat,
		event_counts: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat64))
	});
	const SubmitLimitOrderParams = IDL.Record({
		qty: IDL.Int,
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		side: Side,
		order_id: IDL.Text,
		price: Price
	});
	const SubmitMarketOrderParams = IDL.Record({
		trade_id: IDL.Text,
		matching_order_id: IDL.Text
	});
	const SubmitMatchedTradeParams = IDL.Record({
		qty: IDL.Int,
		trade_id: IDL.Text,
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		seller: IDL.Principal,
		buyer_unblock_amount: IDL.Opt(IDL.Nat),
		buyer: IDL.Principal,
		price: Price,
		seller_unblock_amount: IDL.Opt(IDL.Nat)
	});
	const UpdateAssetMetricsParams = IDL.Record({
		metrics: AssetMetrics,
		asset_id: IDL.Text
	});
	const UpdateAssetPriceParams = IDL.Record({
		price: Price,
		asset_id: IDL.Text
	});
	const UpdateAssetPriceError = IDL.Variant({
		AssetNotFound: IDL.Null,
		AssetMetricsNotInitialized: IDL.Null,
		OracleNotConfigured: IDL.Null,
		Common: CommonError
	});
	const UpdateAssetPriceResult = IDL.Variant({
		Ok: IDL.Null,
		Err: UpdateAssetPriceError
	});
	const UpdateCollateralAssetParams = IDL.Record({
		config: CollateralAssetConfig
	});
	const Config = IDL.Record({
		insurance_fund_fee_ratio: IDL.Nat16,
		signer_canister: IDL.Principal,
		evm_rpc: IDL.Principal,
		protocol_fee_ratio: IDL.Nat16
	});
	const WithdrawCollateralParams = IDL.Record({
		withdrawal_id: IDL.Text,
		asset_id: IDL.Text,
		amount: IDL.Nat
	});
	const WithdrawCollateralError = IDL.Variant({
		InsufficientExcessMargin: IDL.Record({
			requested: IDL.Nat,
			available: IDL.Nat
		}),
		MathOverflow: IDL.Null,
		Asset: AssetError
	});
	const WithdrawCollateralResult = IDL.Variant({
		Ok: IDL.Null,
		Err: WithdrawCollateralError
	});
	const FundType = IDL.Variant({
		Insurance: IDL.Null,
		Treasury: IDL.Null
	});
	const WithdrawFundParams = IDL.Record({
		to: IDL.Principal,
		request_id: IDL.Text,
		fund_type: FundType,
		asset_id: IDL.Text,
		amount: IDL.Nat
	});
	const WithdrawFundError = IDL.Variant({
		TransferFailed: IDL.Text,
		InsufficientFunds: IDL.Null,
		Common: CommonError
	});
	const WithdrawFundResult = IDL.Variant({
		Ok: IDL.Nat,
		Err: WithdrawFundError
	});

	return IDL.Service({
		accept_position_transfer: IDL.Func([PositionProof], [AcceptPositionTransferResult], []),
		cancel_fund_withdrawal: IDL.Func(
			[CancelFundWithdrawalParams],
			[CancelFundWithdrawalResult],
			[]
		),
		cancel_limit_order: IDL.Func([CancelLimitOrderParams], [SubmitMatchedTradeResult], []),
		debug_get_registry_canister: IDL.Func([], [IDL.Principal], ['query']),
		deposit_collateral: IDL.Func([DepositCollateralParams], [DepositCollateralResult], []),
		freeze_position_for_transfer: IDL.Func(
			[FreezePositionForTransferParams],
			[IDL.Opt(PositionProof)],
			[]
		),
		get_account_state: IDL.Func([GetAccountStateParams], [GetAccountStateResult], []),
		get_account_state_query: IDL.Func([], [GetAccountStateResult], ['query']),
		get_collateral_assets: IDL.Func([], [IDL.Vec(CollateralAssetInfo)], ['query']),
		get_funds: IDL.Func([], [GetFundsResult], ['query']),
		get_orders: IDL.Func([], [IDL.Vec(LimitOrder)], ['query']),
		get_position: IDL.Func([GetPositionParams], [IDL.Opt(Position)], ['query']),
		get_positions: IDL.Func([], [IDL.Vec(Position)], ['query']),
		get_settlement_plan: IDL.Func([IDL.Text], [IDL.Opt(SettlementPlan)], ['query']),
		get_settlement_status: IDL.Func([IDL.Text], [IDL.Opt(SettlementStatusView)], ['query']),
		get_trade_history: IDL.Func([], [IDL.Vec(Event)], ['query']),
		http_request: IDL.Func([HttpRequest], [HttpResponse], ['query']),
		list_collateral_assets: IDL.Func([], [IDL.Vec(CollateralAssetConfig)], ['query']),
		list_orders: IDL.Func([ListOrdersParams], [IDL.Vec(LimitOrder)], ['query']),
		list_series: IDL.Func([], [IDL.Vec(Series)], ['query']),
		metrics: IDL.Func([], [IDL.Text], ['query']),
		mint_complete_set: IDL.Func([IDL.Text, IDL.Int], [SubmitMatchedTradeResult], []),
		redeem_complete_set: IDL.Func([IDL.Text, IDL.Int], [SubmitMatchedTradeResult], []),
		resume_settlement: IDL.Func([IDL.Text], [SettleSeriesResult], []),
		set_registry_canister: IDL.Func([IDL.Principal], [], []),
		settle_series: IDL.Func([SettleSeriesParams], [SettleSeriesResult], []),
		stats: IDL.Func([], [Stats], ['query']),
		submit_limit_order: IDL.Func([SubmitLimitOrderParams], [SubmitMatchedTradeResult], []),
		submit_market_order: IDL.Func([SubmitMarketOrderParams], [SubmitMatchedTradeResult], []),
		submit_matched_trade: IDL.Func([SubmitMatchedTradeParams], [SubmitMatchedTradeResult], []),
		update_asset_metrics: IDL.Func([UpdateAssetMetricsParams], [], []),
		update_asset_price: IDL.Func([UpdateAssetPriceParams], [UpdateAssetPriceResult], []),
		update_collateral_asset: IDL.Func([UpdateCollateralAssetParams], [], []),
		update_config: IDL.Func([Config], [], []),
		withdraw_collateral: IDL.Func([WithdrawCollateralParams], [WithdrawCollateralResult], []),
		withdraw_fund: IDL.Func([WithdrawFundParams], [WithdrawFundResult], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
