/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const AppAcceptFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppCheckFriendshipArgs = IDL.Record({
		user_a: IDL.Text,
		user_b: IDL.Text
	});
	const AppCheckFriendshipResult = IDL.Record({ is_friend: IDL.Bool });
	const AppCheckNicknameAvailabilityArgs = IDL.Record({
		nickname: IDL.Text,
		exclude_principal_str: IDL.Text
	});
	const AppCheckNicknameAvailabilityResult = IDL.Record({
		available: IDL.Bool,
		reason: IDL.Opt(
			IDL.Variant({
				taken: IDL.Null,
				required: IDL.Null,
				too_short: IDL.Null
			})
		)
	});
	const AppFollowUserArgs = IDL.Record({ target: IDL.Text });
	const AppGetMarketMetadataArgs = IDL.Record({ series_id: IDL.Text });
	const AppGetMarketMetadataResult = IDL.Record({
		metadata: IDL.Opt(
			IDL.Record({
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				series_id: IDL.Text,
				resolution: IDL.Opt(
					IDL.Record({
						settles_at_ms: IDL.Opt(IDL.Float64),
						source: IDL.Text,
						text: IDL.Text
					})
				),
				events: IDL.Vec(
					IDL.Record({
						day: IDL.Float64,
						dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
						label: IDL.Text
					})
				),
				why_now: IDL.Opt(
					IDL.Record({
						kind: IDL.Variant({
							new: IDL.Null,
							social: IDL.Null,
							trending: IDL.Null,
							closing: IDL.Null,
							topical: IDL.Null
						}),
						text: IDL.Text
					})
				)
			})
		)
	});
	const AppGetProfileArgs = IDL.Record({ principal_str: IDL.Text });
	const AppGetProfileResult = IDL.Record({
		profile: IDL.Opt(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppListFollowersResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFollowingResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFriendRequestsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFriendsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListLeaderboardResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppListRejectedFriendshipsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppRejectFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppSearchProfilesArgs = IDL.Record({ query_str: IDL.Text });
	const AppSearchProfilesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppSendFriendRequestArgs = IDL.Record({ target: IDL.Text });
	const AppUpsertMarketMetadataArgs = IDL.Record({
		data: IDL.Record({
			resolution: IDL.Opt(
				IDL.Record({
					settles_at_ms: IDL.Opt(IDL.Float64),
					source: IDL.Text,
					text: IDL.Text
				})
			),
			events: IDL.Vec(
				IDL.Record({
					day: IDL.Float64,
					dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
					label: IDL.Text
				})
			),
			why_now: IDL.Opt(
				IDL.Record({
					kind: IDL.Variant({
						new: IDL.Null,
						social: IDL.Null,
						trending: IDL.Null,
						closing: IDL.Null,
						topical: IDL.Null
					}),
					text: IDL.Text
				})
			)
		}),
		series_id: IDL.Text
	});
	const AppUpsertMarketMetadataResult = IDL.Record({
		metadata: IDL.Record({
			updated_at: IDL.Float64,
			updated_by: IDL.Text,
			series_id: IDL.Text,
			resolution: IDL.Opt(
				IDL.Record({
					settles_at_ms: IDL.Opt(IDL.Float64),
					source: IDL.Text,
					text: IDL.Text
				})
			),
			events: IDL.Vec(
				IDL.Record({
					day: IDL.Float64,
					dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
					label: IDL.Text
				})
			),
			why_now: IDL.Opt(
				IDL.Record({
					kind: IDL.Variant({
						new: IDL.Null,
						social: IDL.Null,
						trending: IDL.Null,
						closing: IDL.Null,
						topical: IDL.Null
					}),
					text: IDL.Text
				})
			)
		})
	});

	return IDL.Service({
		app_accept_friend_request: IDL.Func([AppAcceptFriendRequestArgs], [], []),
		app_check_friendship: IDL.Func([AppCheckFriendshipArgs], [AppCheckFriendshipResult], ['query']),
		app_check_nickname_availability: IDL.Func(
			[AppCheckNicknameAvailabilityArgs],
			[AppCheckNicknameAvailabilityResult],
			['query']
		),
		app_follow_user: IDL.Func([AppFollowUserArgs], [], []),
		app_get_market_metadata: IDL.Func(
			[AppGetMarketMetadataArgs],
			[AppGetMarketMetadataResult],
			['query']
		),
		app_get_profile: IDL.Func([AppGetProfileArgs], [AppGetProfileResult], ['query']),
		app_list_followers: IDL.Func([], [AppListFollowersResult], ['query']),
		app_list_following: IDL.Func([], [AppListFollowingResult], ['query']),
		app_list_friend_requests: IDL.Func([], [AppListFriendRequestsResult], ['query']),
		app_list_friends: IDL.Func([], [AppListFriendsResult], ['query']),
		app_list_leaderboard: IDL.Func([], [AppListLeaderboardResult], ['query']),
		app_list_rejected_friendships: IDL.Func([], [AppListRejectedFriendshipsResult], ['query']),
		app_reject_friend_request: IDL.Func([AppRejectFriendRequestArgs], [], []),
		app_search_profiles: IDL.Func([AppSearchProfilesArgs], [AppSearchProfilesResult], ['query']),
		app_send_friend_request: IDL.Func([AppSendFriendRequestArgs], [], []),
		app_upsert_market_metadata: IDL.Func(
			[AppUpsertMarketMetadataArgs],
			[AppUpsertMarketMetadataResult],
			[]
		)
	});
};

export const init = ({ IDL }) => {
	return [];
};
