/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const AppAcceptFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppCancelFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppCheckFriendshipArgs = IDL.Record({
		user_a: IDL.Text,
		user_b: IDL.Text
	});
	const AppCheckFriendshipResult = IDL.Record({ is_friend: IDL.Bool });
	const AppCheckNicknameAvailabilityArgs = IDL.Record({
		nickname: IDL.Text,
		exclude_principal_str: IDL.Text
	});
	const AppCheckNicknameAvailabilityResult = IDL.Record({
		available: IDL.Bool,
		reason: IDL.Opt(
			IDL.Variant({
				taken: IDL.Null,
				required: IDL.Null,
				too_short: IDL.Null
			})
		)
	});
	const AppFollowUserArgs = IDL.Record({ target: IDL.Text });
	const AppGetMarketMetadataArgs = IDL.Record({ series_id: IDL.Text });
	const AppGetMarketMetadataResult = IDL.Record({
		metadata: IDL.Opt(
			IDL.Record({
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				suggested: IDL.Bool,
				series_id: IDL.Text,
				tags: IDL.Vec(IDL.Text),
				events: IDL.Vec(
					IDL.Record({
						day: IDL.Float64,
						dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
						label: IDL.Text
					})
				),
				why_now: IDL.Opt(
					IDL.Record({
						kind: IDL.Variant({
							new: IDL.Null,
							social: IDL.Null,
							trending: IDL.Null,
							closing: IDL.Null,
							topical: IDL.Null
						}),
						text: IDL.Text
					})
				)
			})
		)
	});
	const AppGetMarketTranslationArgs = IDL.Record({
		series_id: IDL.Text,
		locale: IDL.Text
	});
	const AppGetMarketTranslationResult = IDL.Record({
		translation: IDL.Opt(
			IDL.Record({
				title: IDL.Text,
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				series_id: IDL.Text,
				locale: IDL.Text,
				description: IDL.Text,
				outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
			})
		)
	});
	const AppGetMyReferralCodeResult = IDL.Record({ code: IDL.Opt(IDL.Text) });
	const AppGetProfileArgs = IDL.Record({ principal_str: IDL.Text });
	const AppGetProfileResult = IDL.Record({
		profile: IDL.Opt(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				contrarian_wins: IDL.Float64,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				unlocked_achievements: IDL.Vec(IDL.Text),
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppListFollowersResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFollowingResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFriendRequestsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFriendsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListLeaderboardResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				contrarian_wins: IDL.Float64,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				unlocked_achievements: IDL.Vec(IDL.Text),
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppListMarketTranslationsArgs = IDL.Record({ series_id: IDL.Text });
	const AppListMarketTranslationsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				title: IDL.Text,
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				series_id: IDL.Text,
				locale: IDL.Text,
				description: IDL.Text,
				outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
			})
		)
	});
	const AppListMyReferralsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				within_referrer_cap: IDL.Bool,
				referee_payout: IDL.Record({
					last_error: IDL.Opt(IDL.Text),
					status: IDL.Variant({
						none: IDL.Null,
						owed: IDL.Null,
						paid: IDL.Null,
						processing: IDL.Null
					}),
					block_index: IDL.Opt(IDL.Text),
					amount_base_units: IDL.Text
				}),
				referrer: IDL.Text,
				code: IDL.Text,
				redeemed_at_ms: IDL.Float64,
				referee: IDL.Text,
				referrer_payout: IDL.Record({
					last_error: IDL.Opt(IDL.Text),
					status: IDL.Variant({
						none: IDL.Null,
						owed: IDL.Null,
						paid: IDL.Null,
						processing: IDL.Null
					}),
					block_index: IDL.Opt(IDL.Text),
					amount_base_units: IDL.Text
				})
			})
		)
	});
	const AppListSentFriendRequestsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppLookupReferralCodeArgs = IDL.Record({ code: IDL.Text });
	const AppLookupReferralCodeResult = IDL.Record({
		owner: IDL.Opt(IDL.Text)
	});
	const AppRedeemReferralCodeArgs = IDL.Record({ code: IDL.Text });
	const AppRejectFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppSearchProfilesArgs = IDL.Record({ query_str: IDL.Text });
	const AppSearchProfilesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				contrarian_wins: IDL.Float64,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				unlocked_achievements: IDL.Vec(IDL.Text),
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppSendFriendRequestArgs = IDL.Record({ target: IDL.Text });
	const AppUpsertMarketMetadataArgs = IDL.Record({
		data: IDL.Record({
			suggested: IDL.Bool,
			tags: IDL.Vec(IDL.Text),
			events: IDL.Vec(
				IDL.Record({
					day: IDL.Float64,
					dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
					label: IDL.Text
				})
			),
			why_now: IDL.Opt(
				IDL.Record({
					kind: IDL.Variant({
						new: IDL.Null,
						social: IDL.Null,
						trending: IDL.Null,
						closing: IDL.Null,
						topical: IDL.Null
					}),
					text: IDL.Text
				})
			)
		}),
		series_id: IDL.Text
	});
	const AppUpsertMarketMetadataResult = IDL.Record({
		metadata: IDL.Record({
			updated_at: IDL.Float64,
			updated_by: IDL.Text,
			suggested: IDL.Bool,
			series_id: IDL.Text,
			tags: IDL.Vec(IDL.Text),
			events: IDL.Vec(
				IDL.Record({
					day: IDL.Float64,
					dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
					label: IDL.Text
				})
			),
			why_now: IDL.Opt(
				IDL.Record({
					kind: IDL.Variant({
						new: IDL.Null,
						social: IDL.Null,
						trending: IDL.Null,
						closing: IDL.Null,
						topical: IDL.Null
					}),
					text: IDL.Text
				})
			)
		})
	});
	const AppUpsertMarketTranslationArgs = IDL.Record({
		data: IDL.Record({
			title: IDL.Text,
			description: IDL.Text,
			outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
		}),
		series_id: IDL.Text,
		locale: IDL.Text
	});
	const AppUpsertMarketTranslationResult = IDL.Record({
		translation: IDL.Record({
			title: IDL.Text,
			updated_at: IDL.Float64,
			updated_by: IDL.Text,
			series_id: IDL.Text,
			locale: IDL.Text,
			description: IDL.Text,
			outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
		})
	});

	return IDL.Service({
		app_accept_friend_request: IDL.Func([AppAcceptFriendRequestArgs], [], []),
		app_cancel_friend_request: IDL.Func([AppCancelFriendRequestArgs], [], []),
		app_check_friendship: IDL.Func([AppCheckFriendshipArgs], [AppCheckFriendshipResult], ['query']),
		app_check_nickname_availability: IDL.Func(
			[AppCheckNicknameAvailabilityArgs],
			[AppCheckNicknameAvailabilityResult],
			['query']
		),
		app_follow_user: IDL.Func([AppFollowUserArgs], [], []),
		app_get_market_metadata: IDL.Func(
			[AppGetMarketMetadataArgs],
			[AppGetMarketMetadataResult],
			['query']
		),
		app_get_market_translation: IDL.Func(
			[AppGetMarketTranslationArgs],
			[AppGetMarketTranslationResult],
			['query']
		),
		app_get_my_referral_code: IDL.Func([], [AppGetMyReferralCodeResult], ['query']),
		app_get_profile: IDL.Func([AppGetProfileArgs], [AppGetProfileResult], ['query']),
		app_list_followers: IDL.Func([], [AppListFollowersResult], ['query']),
		app_list_following: IDL.Func([], [AppListFollowingResult], ['query']),
		app_list_friend_requests: IDL.Func([], [AppListFriendRequestsResult], ['query']),
		app_list_friends: IDL.Func([], [AppListFriendsResult], ['query']),
		app_list_leaderboard: IDL.Func([], [AppListLeaderboardResult], ['query']),
		app_list_market_translations: IDL.Func(
			[AppListMarketTranslationsArgs],
			[AppListMarketTranslationsResult],
			['query']
		),
		app_list_my_referrals: IDL.Func([], [AppListMyReferralsResult], ['query']),
		app_list_sent_friend_requests: IDL.Func([], [AppListSentFriendRequestsResult], ['query']),
		app_lookup_referral_code: IDL.Func(
			[AppLookupReferralCodeArgs],
			[AppLookupReferralCodeResult],
			['query']
		),
		app_redeem_referral_code: IDL.Func([AppRedeemReferralCodeArgs], [], []),
		app_reject_friend_request: IDL.Func([AppRejectFriendRequestArgs], [], []),
		app_search_profiles: IDL.Func([AppSearchProfilesArgs], [AppSearchProfilesResult], ['query']),
		app_send_friend_request: IDL.Func([AppSendFriendRequestArgs], [], []),
		app_upsert_market_metadata: IDL.Func(
			[AppUpsertMarketMetadataArgs],
			[AppUpsertMarketMetadataResult],
			[]
		),
		app_upsert_market_translation: IDL.Func(
			[AppUpsertMarketTranslationArgs],
			[AppUpsertMarketTranslationResult],
			[]
		)
	});
};

export const init = ({ IDL }) => {
	return [];
};
