/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const AppAcceptFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppBackfillStreakUnderpaymentsArgs = IDL.Record({
		dry_run: IDL.Opt(IDL.Bool)
	});
	const AppBackfillStreakUnderpaymentsResult = IDL.Record({
		total_shortfall_base_units: IDL.Text,
		already_backfilled: IDL.Float64,
		minted: IDL.Float64,
		scanned: IDL.Float64,
		underpaid: IDL.Float64,
		failed: IDL.Float64
	});
	const AppCancelFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppCheckFriendshipArgs = IDL.Record({
		user_a: IDL.Text,
		user_b: IDL.Text
	});
	const AppCheckFriendshipResult = IDL.Record({ is_friend: IDL.Bool });
	const AppCheckNicknameAvailabilityArgs = IDL.Record({
		nickname: IDL.Text,
		exclude_principal_str: IDL.Text
	});
	const AppCheckNicknameAvailabilityResult = IDL.Record({
		available: IDL.Bool,
		reason: IDL.Opt(
			IDL.Variant({
				taken: IDL.Null,
				invalid: IDL.Null,
				required: IDL.Null,
				too_short: IDL.Null
			})
		)
	});
	const AppClaimCalibrationRewardArgs = IDL.Record({
		series_id: IDL.Text,
		chosen_side: IDL.Variant({ NO: IDL.Null, YES: IDL.Null })
	});
	const AppClaimCalibrationRewardResult = IDL.Record({
		block_index: IDL.Opt(IDL.Text),
		new_balance_base_units: IDL.Opt(IDL.Text),
		error_message: IDL.Opt(IDL.Text),
		correct: IDL.Bool,
		paid_now: IDL.Bool,
		reward_base_units: IDL.Opt(IDL.Text),
		already_claimed: IDL.Bool,
		reason: IDL.Opt(
			IDL.Variant({
				not_binary: IDL.Null,
				not_engaged_yet: IDL.Null,
				transfer_failed: IDL.Null,
				rate_limited_daily: IDL.Null,
				anonymous: IDL.Null,
				balance_above_floor: IDL.Null,
				not_finalised: IDL.Null,
				outcome_undetermined: IDL.Null,
				not_vici_market: IDL.Null,
				rate_limited_hourly: IDL.Null
			})
		)
	});
	const AppClaimReferralFriendshipArgs = IDL.Record({ code: IDL.Text });
	const AppClaimTournamentPrizeArgs = IDL.Record({
		tournament_id: IDL.Text
	});
	const AppClaimTournamentPrizeResult = IDL.Record({
		ok: IDL.Bool,
		awards_created: IDL.Opt(IDL.Float64),
		awards_already_claimed: IDL.Opt(IDL.Float64),
		total_vxp_credited: IDL.Opt(IDL.Float64),
		reason: IDL.Opt(
			IDL.Variant({
				tournament_not_found: IDL.Null,
				tournament_not_concluded: IDL.Null,
				not_member_of_top_league: IDL.Null
			})
		)
	});
	const AppClaimWorldsPodiumPrizeArgs = IDL.Record({
		month_anchor: IDL.Text
	});
	const AppClaimWorldsPodiumPrizeResult = IDL.Record({
		month_anchor: IDL.Text,
		not_eligible: IDL.Bool,
		awards_created: IDL.Float64,
		awards_already_claimed: IDL.Float64
	});
	const AppDeleteAnalyticsEventsArgs = IDL.Record({
		keys: IDL.Vec(IDL.Text)
	});
	const AppDeleteAnalyticsEventsResult = IDL.Record({
		deleted: IDL.Float64
	});
	const AppDeleteMyAccountArgs = IDL.Record({
		note: IDL.Text,
		league_resolutions: IDL.Opt(
			IDL.Vec(
				IDL.Record({
					action: IDL.Variant({
						delete: IDL.Null,
						transfer: IDL.Null
					}),
					league_id: IDL.Text,
					transfer_to: IDL.Opt(IDL.Text)
				})
			)
		),
		reason: IDL.Text
	});
	const AppDeleteMyAccountResult = IDL.Record({
		ok: IDL.Bool,
		resolution_reason: IDL.Opt(IDL.Text),
		blocking_league_ids: IDL.Opt(IDL.Vec(IDL.Text)),
		failed_league_id: IDL.Opt(IDL.Text),
		soft_deleted: IDL.Opt(IDL.Bool),
		reason: IDL.Opt(
			IDL.Variant({
				league_resolution_failed: IDL.Null,
				owns_non_empty_league: IDL.Null,
				invalid_input: IDL.Null
			})
		)
	});
	const AppFollowUserArgs = IDL.Record({ target: IDL.Text });
	const AppGetAffiliationStatsArgs = IDL.Record({
		kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
		affiliation_identifier: IDL.Text
	});
	const AppGetAffiliationStatsResult = IDL.Record({
		stats: IDL.Opt(
			IDL.Record({
				month_anchor: IDL.Text,
				kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
				wins: IDL.Float64,
				month_wins: IDL.Float64,
				updated_at_ms: IDL.Float64,
				total_calls: IDL.Float64,
				month_total_calls: IDL.Float64,
				affiliation_identifier: IDL.Text
			})
		)
	});
	const AppGetAnalyticsEventsArgs = IDL.Record({
		after_updated_at_ns: IDL.Opt(IDL.Text),
		limit: IDL.Float64,
		after_key: IDL.Opt(IDL.Text)
	});
	const AppGetAnalyticsEventsResult = IDL.Record({
		rows: IDL.Vec(
			IDL.Record({
				ok: IDL.Opt(IDL.Bool),
				key: IDL.Text,
				ts_ms: IDL.Float64,
				battle_id: IDL.Opt(IDL.Text),
				country: IDL.Opt(IDL.Text),
				league_id: IDL.Opt(IDL.Text),
				session_id: IDL.Text,
				value: IDL.Opt(IDL.Float64),
				source: IDL.Opt(IDL.Text),
				market_id: IDL.Opt(IDL.Text),
				series_id: IDL.Opt(IDL.Text),
				name: IDL.Variant({
					delete_confirmed: IDL.Null,
					privacy_sharing_toggled: IDL.Null,
					school_picked: IDL.Null,
					battle_viewed: IDL.Null,
					transactions_viewed: IDL.Null,
					resolution_disputed: IDL.Null,
					streak_milestone: IDL.Null,
					school_verify_email_submitted: IDL.Null,
					market_shared: IDL.Null,
					flow_completed: IDL.Null,
					flow_card_expanded: IDL.Null,
					affiliation_removed: IDL.Null,
					league_invite_sent: IDL.Null,
					pwa_install_prompted: IDL.Null,
					notification_opened: IDL.Null,
					position_taken: IDL.Null,
					flow_abandoned: IDL.Null,
					market_category_filter: IDL.Null,
					watchlist_removed: IDL.Null,
					delete_succeeded: IDL.Null,
					friend_feed_reaction: IDL.Null,
					referral_link_copied: IDL.Null,
					market_translation_toggled: IDL.Null,
					comment_posted: IDL.Null,
					flow_swipe: IDL.Null,
					referral_converted: IDL.Null,
					pwa_install_dismissed: IDL.Null,
					transactions_filtered: IDL.Null,
					school_verify_code_submitted: IDL.Null,
					signed_in: IDL.Null,
					signed_up: IDL.Null,
					order_placed: IDL.Null,
					order_cancelled: IDL.Null,
					onboarding_started: IDL.Null,
					payout_settled: IDL.Null,
					battle_proposed: IDL.Null,
					perf_metric: IDL.Null,
					provider_linked: IDL.Null,
					friend_digest_opened: IDL.Null,
					leaderboard_viewed: IDL.Null,
					friend_request_sent: IDL.Null,
					battle_accepted: IDL.Null,
					battle_declined: IDL.Null,
					vxp_awarded: IDL.Null,
					league_joined: IDL.Null,
					exit_signal: IDL.Null,
					referral_sent: IDL.Null,
					resolution_proposed: IDL.Null,
					app_error: IDL.Null,
					resolution_confirmed: IDL.Null,
					flow_session_started: IDL.Null,
					school_picker_opened: IDL.Null,
					onboarding_completed: IDL.Null,
					watchlist_added: IDL.Null,
					position_closed: IDL.Null,
					handle_checked: IDL.Null,
					battle_resolved: IDL.Null,
					market_searched: IDL.Null,
					sound_toggled: IDL.Null,
					league_created: IDL.Null,
					onboarding_step: IDL.Null,
					market_viewed: IDL.Null,
					battle_expired: IDL.Null,
					delete_flow_opened: IDL.Null,
					affiliation_set: IDL.Null,
					session_started: IDL.Null,
					referral_redeemed: IDL.Null,
					prediction_created: IDL.Null,
					faucet_claimed: IDL.Null,
					pwa_install_accepted: IDL.Null,
					chat_sent: IDL.Null,
					orderbook_viewed: IDL.Null,
					signed_out: IDL.Null
				}),
				path: IDL.Opt(IDL.Text),
				count: IDL.Opt(IDL.Float64),
				step: IDL.Opt(IDL.Float64),
				locale: IDL.Opt(IDL.Text),
				updated_at_ns: IDL.Text,
				principal_text: IDL.Opt(IDL.Text),
				label: IDL.Opt(IDL.Text),
				created_at_ns: IDL.Text,
				version: IDL.Opt(IDL.Text),
				duration_ms: IDL.Opt(IDL.Float64),
				owner_text: IDL.Opt(IDL.Text)
			})
		),
		has_more: IDL.Bool
	});
	const AppGetAnalyticsProfileCreatedArgs = IDL.Record({
		limit: IDL.Float64,
		after_key: IDL.Opt(IDL.Text)
	});
	const AppGetAnalyticsProfileCreatedResult = IDL.Record({
		rows: IDL.Vec(IDL.Record({ key: IDL.Text, created_at_ns: IDL.Text })),
		has_more: IDL.Bool
	});
	const AppGetAnalyticsSummaryArgs = IDL.Record({ days: IDL.Float64 });
	const AppGetAnalyticsSummaryResult = IDL.Record({
		rows: IDL.Vec(
			IDL.Record({
				day: IDL.Float64,
				name: IDL.Variant({
					delete_confirmed: IDL.Null,
					privacy_sharing_toggled: IDL.Null,
					school_picked: IDL.Null,
					battle_viewed: IDL.Null,
					transactions_viewed: IDL.Null,
					resolution_disputed: IDL.Null,
					streak_milestone: IDL.Null,
					school_verify_email_submitted: IDL.Null,
					market_shared: IDL.Null,
					flow_completed: IDL.Null,
					flow_card_expanded: IDL.Null,
					affiliation_removed: IDL.Null,
					league_invite_sent: IDL.Null,
					pwa_install_prompted: IDL.Null,
					notification_opened: IDL.Null,
					position_taken: IDL.Null,
					flow_abandoned: IDL.Null,
					market_category_filter: IDL.Null,
					watchlist_removed: IDL.Null,
					delete_succeeded: IDL.Null,
					friend_feed_reaction: IDL.Null,
					referral_link_copied: IDL.Null,
					market_translation_toggled: IDL.Null,
					comment_posted: IDL.Null,
					flow_swipe: IDL.Null,
					referral_converted: IDL.Null,
					pwa_install_dismissed: IDL.Null,
					transactions_filtered: IDL.Null,
					school_verify_code_submitted: IDL.Null,
					signed_in: IDL.Null,
					signed_up: IDL.Null,
					order_placed: IDL.Null,
					order_cancelled: IDL.Null,
					onboarding_started: IDL.Null,
					payout_settled: IDL.Null,
					battle_proposed: IDL.Null,
					perf_metric: IDL.Null,
					provider_linked: IDL.Null,
					friend_digest_opened: IDL.Null,
					leaderboard_viewed: IDL.Null,
					friend_request_sent: IDL.Null,
					battle_accepted: IDL.Null,
					battle_declined: IDL.Null,
					vxp_awarded: IDL.Null,
					league_joined: IDL.Null,
					exit_signal: IDL.Null,
					referral_sent: IDL.Null,
					resolution_proposed: IDL.Null,
					app_error: IDL.Null,
					resolution_confirmed: IDL.Null,
					flow_session_started: IDL.Null,
					school_picker_opened: IDL.Null,
					onboarding_completed: IDL.Null,
					watchlist_added: IDL.Null,
					position_closed: IDL.Null,
					handle_checked: IDL.Null,
					battle_resolved: IDL.Null,
					market_searched: IDL.Null,
					sound_toggled: IDL.Null,
					league_created: IDL.Null,
					onboarding_step: IDL.Null,
					market_viewed: IDL.Null,
					battle_expired: IDL.Null,
					delete_flow_opened: IDL.Null,
					affiliation_set: IDL.Null,
					session_started: IDL.Null,
					referral_redeemed: IDL.Null,
					prediction_created: IDL.Null,
					faucet_claimed: IDL.Null,
					pwa_install_accepted: IDL.Null,
					chat_sent: IDL.Null,
					orderbook_viewed: IDL.Null,
					signed_out: IDL.Null
				}),
				count: IDL.Float64,
				start: IDL.Float64
			})
		)
	});
	const AppGetAnalyticsUserStatsResult = IDL.Record({
		registered: IDL.Float64
	});
	const AppGetCurrentTournamentResult = IDL.Record({
		tournament: IDL.Opt(
			IDL.Record({
				id: IDL.Text,
				seeded_league_ids: IDL.Vec(IDL.Text),
				month_start_ms: IDL.Float64,
				created_at_ms: IDL.Float64,
				state: IDL.Variant({
					concluded: IDL.Null,
					in_flight: IDL.Null
				}),
				bracket_size: IDL.Float64,
				month_end_ms: IDL.Float64
			})
		),
		matches: IDL.Vec(
			IDL.Record({
				winner_league_id: IDL.Opt(IDL.Text),
				to_league_id: IDL.Opt(IDL.Text),
				start_ms: IDL.Float64,
				to_start_calls: IDL.Opt(IDL.Float64),
				to_start_wins: IDL.Opt(IDL.Float64),
				from_league_id: IDL.Opt(IDL.Text),
				to_acc: IDL.Opt(IDL.Float64),
				from_start_wins: IDL.Opt(IDL.Float64),
				tournament_id: IDL.Text,
				from_acc: IDL.Opt(IDL.Float64),
				from_start_calls: IDL.Opt(IDL.Float64),
				index: IDL.Float64,
				round: IDL.Variant({
					r1: IDL.Null,
					final: IDL.Null,
					semifinal: IDL.Null,
					quarter: IDL.Null
				}),
				end_ms: IDL.Float64
			})
		)
	});
	const AppGetMarketMetadataArgs = IDL.Record({ series_id: IDL.Text });
	const AppGetMarketMetadataResult = IDL.Record({
		metadata: IDL.Opt(
			IDL.Record({
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				suggested: IDL.Bool,
				series_id: IDL.Text,
				tags: IDL.Vec(IDL.Text),
				events: IDL.Vec(
					IDL.Record({
						day: IDL.Float64,
						dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
						label: IDL.Text
					})
				),
				why_now: IDL.Opt(
					IDL.Record({
						kind: IDL.Variant({
							new: IDL.Null,
							social: IDL.Null,
							trending: IDL.Null,
							closing: IDL.Null,
							topical: IDL.Null
						}),
						text: IDL.Text
					})
				),
				subtitle: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppGetMarketTagsResult = IDL.Record({
		buckets: IDL.Vec(IDL.Record({ tag: IDL.Text, series_ids: IDL.Vec(IDL.Text) }))
	});
	const AppGetMarketTranslationArgs = IDL.Record({
		series_id: IDL.Text,
		locale: IDL.Text
	});
	const AppGetMarketTranslationResult = IDL.Record({
		translation: IDL.Opt(
			IDL.Record({
				title: IDL.Text,
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				series_id: IDL.Text,
				locale: IDL.Text,
				description: IDL.Text,
				resolution: IDL.Text,
				outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
			})
		)
	});
	const AppGetMonthlyLeaderboardArgs = IDL.Record({
		month_anchor: IDL.Text
	});
	const AppGetMonthlyLeaderboardResult = IDL.Record({
		bold_callers: IDL.Vec(
			IDL.Record({
				owner: IDL.Text,
				month_wins: IDL.Float64,
				median_consensus: IDL.Float64,
				month_calls: IDL.Float64,
				accuracy: IDL.Float64
			})
		),
		items: IDL.Vec(
			IDL.Record({
				placement: IDL.Float64,
				owner: IDL.Text,
				month_wins: IDL.Float64,
				month_calls: IDL.Float64,
				accuracy: IDL.Float64
			})
		)
	});
	const AppGetMyBattleStatsResult = IDL.Record({ bouts_won: IDL.Float64 });
	const AppGetMyReferralCodeResult = IDL.Record({ code: IDL.Opt(IDL.Text) });
	const AppGetMyRivalResult = IDL.Record({
		rival_is_trailing: IDL.Bool,
		rival: IDL.Opt(
			IDL.Record({
				pnl: IDL.Float64,
				sharpest_eye_best_tier: IDL.Opt(IDL.Text),
				streak: IDL.Float64,
				top_decile_streak: IDL.Float64,
				nickname: IDL.Text,
				hibernated_at_ms: IDL.Opt(IDL.Float64),
				comebacks: IDL.Float64,
				daily_goal_date: IDL.Opt(IDL.Text),
				daily_goal_done: IDL.Float64,
				contrarian_wins: IDL.Float64,
				leagues_joined: IDL.Float64,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				bouts_won: IDL.Float64,
				handle_last_change_ms: IDL.Opt(IDL.Float64),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Record({
					favorite_participant_id: IDL.Text,
					favorite_side: IDL.Text,
					notify: IDL.Record({
						market_alerts: IDL.Bool,
						friend_activity: IDL.Bool,
						weekly_digest: IDL.Bool,
						streak_reminder: IDL.Bool
					}),
					haptics_enabled: IDL.Bool,
					sharing: IDL.Record({
						worlds_opt_in: IDL.Bool,
						leaderboard_opt_in: IDL.Bool,
						calls_public: IDL.Bool,
						profile_visibility: IDL.Text
					}),
					sound_enabled: IDL.Bool,
					onboarding_completed: IDL.Bool,
					default_amount: IDL.Record({
						flow: IDL.Text,
						manual: IDL.Text
					}),
					world_cup_mode: IDL.Bool,
					saved_market_ids: IDL.Vec(IDL.Text),
					flow_tags: IDL.Vec(IDL.Text),
					flow_session_length: IDL.Float64
				}),
				longest_streak: IDL.Float64,
				archetype: IDL.Text,
				school_status: IDL.Opt(IDL.Text),
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				last_top_decile_day: IDL.Opt(IDL.Text),
				win_rate: IDL.Float64,
				best_upset_consensus: IDL.Opt(IDL.Float64),
				avatar_parts: IDL.Text,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				leagues_founded: IDL.Float64,
				daily_streak: IDL.Float64,
				unlocked_achievements: IDL.Vec(IDL.Text),
				earned_menagerie: IDL.Opt(IDL.Vec(IDL.Text)),
				deleted_at_ms: IDL.Opt(IDL.Float64),
				winning_categories: IDL.Float64,
				points: IDL.Float64,
				avatar: IDL.Text,
				on_fire_streak: IDL.Float64,
				accuracy: IDL.Float64
			})
		)
	});
	const AppGetProfileArgs = IDL.Record({ principal_str: IDL.Text });
	const AppGetProfileResult = IDL.Record({
		profile: IDL.Opt(
			IDL.Record({
				pnl: IDL.Float64,
				sharpest_eye_best_tier: IDL.Opt(IDL.Text),
				streak: IDL.Float64,
				top_decile_streak: IDL.Float64,
				nickname: IDL.Text,
				hibernated_at_ms: IDL.Opt(IDL.Float64),
				comebacks: IDL.Float64,
				daily_goal_date: IDL.Opt(IDL.Text),
				daily_goal_done: IDL.Float64,
				contrarian_wins: IDL.Float64,
				leagues_joined: IDL.Float64,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				bouts_won: IDL.Float64,
				handle_last_change_ms: IDL.Opt(IDL.Float64),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Record({
					favorite_participant_id: IDL.Text,
					favorite_side: IDL.Text,
					notify: IDL.Record({
						market_alerts: IDL.Bool,
						friend_activity: IDL.Bool,
						weekly_digest: IDL.Bool,
						streak_reminder: IDL.Bool
					}),
					haptics_enabled: IDL.Bool,
					sharing: IDL.Record({
						worlds_opt_in: IDL.Bool,
						leaderboard_opt_in: IDL.Bool,
						calls_public: IDL.Bool,
						profile_visibility: IDL.Text
					}),
					sound_enabled: IDL.Bool,
					onboarding_completed: IDL.Bool,
					default_amount: IDL.Record({
						flow: IDL.Text,
						manual: IDL.Text
					}),
					world_cup_mode: IDL.Bool,
					saved_market_ids: IDL.Vec(IDL.Text),
					flow_tags: IDL.Vec(IDL.Text),
					flow_session_length: IDL.Float64
				}),
				longest_streak: IDL.Float64,
				archetype: IDL.Text,
				school_status: IDL.Opt(IDL.Text),
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				last_top_decile_day: IDL.Opt(IDL.Text),
				win_rate: IDL.Float64,
				best_upset_consensus: IDL.Opt(IDL.Float64),
				avatar_parts: IDL.Text,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				leagues_founded: IDL.Float64,
				daily_streak: IDL.Float64,
				unlocked_achievements: IDL.Vec(IDL.Text),
				earned_menagerie: IDL.Opt(IDL.Vec(IDL.Text)),
				deleted_at_ms: IDL.Opt(IDL.Float64),
				winning_categories: IDL.Float64,
				points: IDL.Float64,
				avatar: IDL.Text,
				on_fire_streak: IDL.Float64,
				accuracy: IDL.Float64
			})
		)
	});
	const AppGetUserRankAndCountArgs = IDL.Record({ principal_str: IDL.Text });
	const AppGetUserRankAndCountResult = IDL.Record({
		count: IDL.Float64,
		rank: IDL.Opt(IDL.Float64)
	});
	const AppHibernateMyAccountResult = IDL.Record({
		ok: IDL.Bool,
		reason: IDL.Opt(IDL.Variant({ deleted: IDL.Null, no_profile: IDL.Null }))
	});
	const AppListAffiliationChampionshipsArgs = IDL.Record({
		kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
		affiliation_identifier: IDL.Text
	});
	const AppListAffiliationChampionshipsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				month_anchor: IDL.Text,
				month_total_calls: IDL.Float64,
				accuracy: IDL.Float64
			})
		)
	});
	const AppListAffiliationStatsArgs = IDL.Record({
		kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
		limit: IDL.Opt(IDL.Float64)
	});
	const AppListAffiliationStatsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				month_anchor: IDL.Text,
				kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
				wins: IDL.Float64,
				month_wins: IDL.Float64,
				updated_at_ms: IDL.Float64,
				total_calls: IDL.Float64,
				month_total_calls: IDL.Float64,
				affiliation_identifier: IDL.Text
			})
		)
	});
	const AppListChallengeableLeaguesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				id: IDL.Text,
				accent_color: IDL.Opt(IDL.Text),
				image_url: IDL.Opt(IDL.Text),
				owner: IDL.Text,
				name: IDL.Text,
				invite_code: IDL.Text,
				description: IDL.Opt(IDL.Text),
				emblem: IDL.Opt(IDL.Text),
				created_at_ms: IDL.Float64,
				privacy: IDL.Variant({ open: IDL.Null, private: IDL.Null })
			})
		)
	});
	const AppListFollowersResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFollowingResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFriendRecommendedLeaguesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				league: IDL.Record({
					id: IDL.Text,
					accent_color: IDL.Opt(IDL.Text),
					image_url: IDL.Opt(IDL.Text),
					owner: IDL.Text,
					name: IDL.Text,
					invite_code: IDL.Text,
					description: IDL.Opt(IDL.Text),
					emblem: IDL.Opt(IDL.Text),
					created_at_ms: IDL.Float64,
					privacy: IDL.Variant({ open: IDL.Null, private: IDL.Null })
				}),
				friend_members: IDL.Vec(IDL.Text),
				member_count: IDL.Float64
			})
		)
	});
	const AppListFriendRequestsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListFriendResolvedResultsArgs = IDL.Record({
		friends: IDL.Vec(IDL.Text)
	});
	const AppListFriendResolvedResultsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				title: IDL.Text,
				owner: IDL.Text,
				market_id: IDL.Text,
				net_vxp: IDL.Float64,
				side: IDL.Text,
				outcome: IDL.Variant({ win: IDL.Null, loss: IDL.Null }),
				resolved_at_ms: IDL.Float64
			})
		)
	});
	const AppListFriendsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListLeaderboardResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				contrarian_wins: IDL.Float64,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				avatar_parts: IDL.Text,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				unlocked_achievements: IDL.Vec(IDL.Text),
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppListLeagueBattlesArgs = IDL.Record({ league_id: IDL.Text });
	const AppListLeagueBattlesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				id: IDL.Text,
				trash_talk: IDL.Opt(IDL.Text),
				respond_by_ms: IDL.Opt(IDL.Float64),
				responded_at_ms: IDL.Opt(IDL.Float64),
				kind: IDL.Variant({ duel: IDL.Null, league: IDL.Null }),
				winner: IDL.Opt(IDL.Variant({ A: IDL.Null, B: IDL.Null, draw: IDL.Null })),
				calls_a: IDL.Opt(IDL.Float64),
				calls_b: IDL.Opt(IDL.Float64),
				score_a: IDL.Opt(IDL.Float64),
				score_b: IDL.Opt(IDL.Float64),
				scope: IDL.Opt(IDL.Text),
				state: IDL.Variant({
					resolved: IDL.Null,
					expired: IDL.Null,
					proposed: IDL.Null,
					in_flight: IDL.Null,
					accepted: IDL.Null,
					declined: IDL.Null
				}),
				side_a: IDL.Text,
				side_b: IDL.Text,
				proposer: IDL.Text,
				kickoff_ms: IDL.Float64,
				wager: IDL.Opt(IDL.Float64),
				resolved_at_ms: IDL.Opt(IDL.Float64),
				settle_ms: IDL.Float64
			})
		)
	});
	const AppListLeagueMembersArgs = IDL.Record({ league_id: IDL.Text });
	const AppListLeagueMembersResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				member: IDL.Text,
				league_id: IDL.Text,
				role: IDL.Variant({
					member: IDL.Null,
					admin: IDL.Null,
					owner: IDL.Null
				}),
				joined_at_ms: IDL.Float64
			})
		)
	});
	const AppListMarketTranslationsArgs = IDL.Record({ series_id: IDL.Text });
	const AppListMarketTranslationsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				title: IDL.Text,
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				series_id: IDL.Text,
				locale: IDL.Text,
				description: IDL.Text,
				resolution: IDL.Text,
				outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
			})
		)
	});
	const AppListMarketTranslationsForLocalesArgs = IDL.Record({
		locales: IDL.Vec(IDL.Text),
		series_ids: IDL.Vec(IDL.Text)
	});
	const AppListMarketTranslationsForLocalesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				title: IDL.Text,
				updated_at: IDL.Float64,
				updated_by: IDL.Text,
				series_id: IDL.Text,
				locale: IDL.Text,
				description: IDL.Text,
				resolution: IDL.Text,
				outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
			})
		)
	});
	const AppListMyAffiliationsResult = IDL.Record({
		country: IDL.Opt(
			IDL.Record({
				member: IDL.Text,
				locked_until_ms: IDL.Float64,
				kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
				joined_at_ms: IDL.Float64,
				affiliation_identifier: IDL.Text
			})
		),
		university: IDL.Opt(
			IDL.Record({
				member: IDL.Text,
				locked_until_ms: IDL.Float64,
				kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
				joined_at_ms: IDL.Float64,
				affiliation_identifier: IDL.Text
			})
		)
	});
	const AppListMyBattlesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				id: IDL.Text,
				trash_talk: IDL.Opt(IDL.Text),
				respond_by_ms: IDL.Opt(IDL.Float64),
				responded_at_ms: IDL.Opt(IDL.Float64),
				kind: IDL.Variant({ duel: IDL.Null, league: IDL.Null }),
				winner: IDL.Opt(IDL.Variant({ A: IDL.Null, B: IDL.Null, draw: IDL.Null })),
				calls_a: IDL.Opt(IDL.Float64),
				calls_b: IDL.Opt(IDL.Float64),
				score_a: IDL.Opt(IDL.Float64),
				score_b: IDL.Opt(IDL.Float64),
				scope: IDL.Opt(IDL.Text),
				state: IDL.Variant({
					resolved: IDL.Null,
					expired: IDL.Null,
					proposed: IDL.Null,
					in_flight: IDL.Null,
					accepted: IDL.Null,
					declined: IDL.Null
				}),
				side_a: IDL.Text,
				side_b: IDL.Text,
				proposer: IDL.Text,
				kickoff_ms: IDL.Float64,
				wager: IDL.Opt(IDL.Float64),
				resolved_at_ms: IDL.Opt(IDL.Float64),
				settle_ms: IDL.Float64
			})
		)
	});
	const AppListMyBlockingLeaguesResult = IDL.Record({
		league_ids: IDL.Vec(IDL.Text)
	});
	const AppListMyLeaguesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				role: IDL.Variant({
					member: IDL.Null,
					admin: IDL.Null,
					owner: IDL.Null
				}),
				joined_at_ms: IDL.Float64,
				league: IDL.Record({
					id: IDL.Text,
					accent_color: IDL.Opt(IDL.Text),
					image_url: IDL.Opt(IDL.Text),
					owner: IDL.Text,
					name: IDL.Text,
					invite_code: IDL.Text,
					description: IDL.Opt(IDL.Text),
					emblem: IDL.Opt(IDL.Text),
					created_at_ms: IDL.Float64,
					privacy: IDL.Variant({ open: IDL.Null, private: IDL.Null })
				}),
				member_count: IDL.Float64
			})
		)
	});
	const AppListMyReferralsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				within_referrer_cap: IDL.Bool,
				referee_payout: IDL.Record({
					last_error: IDL.Opt(IDL.Text),
					status: IDL.Variant({
						none: IDL.Null,
						owed: IDL.Null,
						paid: IDL.Null,
						processing: IDL.Null
					}),
					block_index: IDL.Opt(IDL.Text),
					amount_base_units: IDL.Text
				}),
				referrer: IDL.Text,
				code: IDL.Text,
				redeemed_at_ms: IDL.Float64,
				referee: IDL.Text,
				referrer_payout: IDL.Record({
					last_error: IDL.Opt(IDL.Text),
					status: IDL.Variant({
						none: IDL.Null,
						owed: IDL.Null,
						paid: IDL.Null,
						processing: IDL.Null
					}),
					block_index: IDL.Opt(IDL.Text),
					amount_base_units: IDL.Text
				})
			})
		)
	});
	const AppListSentFriendRequestsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				viewer_role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				participants: IDL.Vec(IDL.Text),
				is_friend: IDL.Opt(IDL.Bool),
				state: IDL.Variant({
					REJECTED: IDL.Null,
					PENDING: IDL.Null,
					BLOCKED: IDL.Null,
					ACTIVE: IDL.Null
				}),
				category: IDL.Variant({
					GROUP: IDL.Null,
					FRIEND: IDL.Null,
					follow: IDL.Null
				}),
				viewer_principal: IDL.Opt(IDL.Text)
			})
		)
	});
	const AppListWorldsMemberCountsArgs = IDL.Record({
		kind: IDL.Variant({ country: IDL.Null, university: IDL.Null })
	});
	const AppListWorldsMemberCountsResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
				member_count: IDL.Float64,
				affiliation_identifier: IDL.Text
			})
		)
	});
	const AppListWorldsRosterArgs = IDL.Record({
		kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
		affiliation_identifier: IDL.Text
	});
	const AppListWorldsRosterResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				member: IDL.Text,
				locked_until_ms: IDL.Float64,
				kind: IDL.Variant({ country: IDL.Null, university: IDL.Null }),
				joined_at_ms: IDL.Float64,
				affiliation_identifier: IDL.Text
			})
		)
	});
	const AppLookupLeagueByInviteArgs = IDL.Record({ invite_code: IDL.Text });
	const AppLookupLeagueByInviteResult = IDL.Record({
		league: IDL.Opt(
			IDL.Record({
				id: IDL.Text,
				accent_color: IDL.Opt(IDL.Text),
				image_url: IDL.Opt(IDL.Text),
				owner: IDL.Text,
				name: IDL.Text,
				invite_code: IDL.Text,
				description: IDL.Opt(IDL.Text),
				emblem: IDL.Opt(IDL.Text),
				created_at_ms: IDL.Float64,
				privacy: IDL.Variant({ open: IDL.Null, private: IDL.Null })
			})
		)
	});
	const AppLookupReferralCodeArgs = IDL.Record({ code: IDL.Text });
	const AppLookupReferralCodeResult = IDL.Record({
		owner: IDL.Opt(IDL.Text)
	});
	const AppPruneResolvedResultsResult = IDL.Record({ pruned: IDL.Float64 });
	const AppReadBattleLiveScoreArgs = IDL.Record({ battle_id: IDL.Text });
	const AppReadBattleLiveScoreResult = IDL.Record({
		score: IDL.Opt(
			IDL.Record({
				calls_a: IDL.Float64,
				calls_b: IDL.Float64,
				score_a: IDL.Float64,
				score_b: IDL.Float64,
				leader: IDL.Variant({
					A: IDL.Null,
					B: IDL.Null,
					draw: IDL.Null
				})
			})
		)
	});
	const AppRebuildMarketTagIndexResult = IDL.Record({
		series: IDL.Float64,
		buckets: IDL.Float64
	});
	const AppRecomputeActivityReactionCountsResult = IDL.Record({
		recomputed: IDL.Float64
	});
	const AppRecordFlowSwipeArgs = IDL.Record({ day_key: IDL.Text });
	const AppRecordFlowSwipeResult = IDL.Record({
		daily_goal_date: IDL.Text,
		daily_goal_done: IDL.Float64,
		cap_reached: IDL.Bool
	});
	const AppRecoverMyAccountResult = IDL.Record({
		ok: IDL.Bool,
		recovered: IDL.Opt(IDL.Bool),
		reason: IDL.Opt(IDL.Variant({ expired: IDL.Null }))
	});
	const AppRedeemReferralCodeArgs = IDL.Record({ code: IDL.Text });
	const AppRejectFriendRequestArgs = IDL.Record({ relation_id: IDL.Text });
	const AppResolveBattleArgs = IDL.Record({ battle_id: IDL.Text });
	const AppResolveBattleResult = IDL.Record({
		battle: IDL.Record({
			id: IDL.Text,
			trash_talk: IDL.Opt(IDL.Text),
			respond_by_ms: IDL.Opt(IDL.Float64),
			responded_at_ms: IDL.Opt(IDL.Float64),
			kind: IDL.Variant({ duel: IDL.Null, league: IDL.Null }),
			winner: IDL.Opt(IDL.Variant({ A: IDL.Null, B: IDL.Null, draw: IDL.Null })),
			calls_a: IDL.Opt(IDL.Float64),
			calls_b: IDL.Opt(IDL.Float64),
			score_a: IDL.Opt(IDL.Float64),
			score_b: IDL.Opt(IDL.Float64),
			scope: IDL.Opt(IDL.Text),
			state: IDL.Variant({
				resolved: IDL.Null,
				expired: IDL.Null,
				proposed: IDL.Null,
				in_flight: IDL.Null,
				accepted: IDL.Null,
				declined: IDL.Null
			}),
			side_a: IDL.Text,
			side_b: IDL.Text,
			proposer: IDL.Text,
			kickoff_ms: IDL.Float64,
			wager: IDL.Opt(IDL.Float64),
			resolved_at_ms: IDL.Opt(IDL.Float64),
			settle_ms: IDL.Float64
		})
	});
	const AppResolveTournamentRoundArgs = IDL.Record({
		tournament_id: IDL.Text,
		round: IDL.Text
	});
	const AppResolveTournamentRoundResult = IDL.Record({
		ok: IDL.Bool,
		tournament_concluded: IDL.Opt(IDL.Bool),
		matches_resolved: IDL.Opt(IDL.Float64),
		reason: IDL.Opt(
			IDL.Variant({
				tournament_not_found: IDL.Null,
				previous_round_not_resolved: IDL.Null,
				invalid_input: IDL.Null,
				round_not_yet_closed: IDL.Null,
				no_matches: IDL.Null
			})
		)
	});
	const AppResumeMyAccountResult = IDL.Record({
		ok: IDL.Bool,
		resumed: IDL.Bool
	});
	const AppSearchProfilesArgs = IDL.Record({ query_str: IDL.Text });
	const AppSearchProfilesResult = IDL.Record({
		items: IDL.Vec(
			IDL.Record({
				pnl: IDL.Float64,
				streak: IDL.Float64,
				nickname: IDL.Text,
				contrarian_wins: IDL.Float64,
				owner: IDL.Text,
				interests: IDL.Vec(IDL.Text),
				role: IDL.Opt(
					IDL.Variant({
						controller: IDL.Null,
						creator: IDL.Null,
						admin: IDL.Null,
						solver: IDL.Null
					})
				),
				email: IDL.Text,
				level: IDL.Float64,
				preferences: IDL.Opt(
					IDL.Record({
						default_amount: IDL.Record({
							flow: IDL.Text,
							manual: IDL.Text
						})
					})
				),
				archetype: IDL.Text,
				last_active_day: IDL.Opt(IDL.Text),
				total_trades: IDL.Float64,
				win_rate: IDL.Float64,
				avatar_parts: IDL.Text,
				visibility: IDL.Variant({
					friends_and_followers: IDL.Null,
					public: IDL.Null,
					friends_only: IDL.Null
				}),
				daily_streak: IDL.Float64,
				unlocked_achievements: IDL.Vec(IDL.Text),
				points: IDL.Float64,
				avatar: IDL.Text,
				accuracy: IDL.Float64
			})
		)
	});
	const AppSendFriendRequestArgs = IDL.Record({ target: IDL.Text });
	const AppSendFriendRequestResult = IDL.Record({
		status: IDL.Variant({
			sent: IDL.Null,
			auto_accepted: IDL.Null,
			already_friends: IDL.Null,
			rejected_cooldown: IDL.Null,
			already_pending: IDL.Null
		}),
		retry_at_ms: IDL.Opt(IDL.Float64)
	});
	const AppSettleFounderAwardsResult = IDL.Record({ settled: IDL.Float64 });
	const AppSettleReferralArgs = IDL.Record({ referee: IDL.Text });
	const AppSubmitSchoolArgs = IDL.Record({
		country: IDL.Opt(IDL.Text),
		name: IDL.Text,
		school_id: IDL.Opt(IDL.Text),
		locale: IDL.Text,
		email: IDL.Text
	});
	const AppSubmitSchoolResult = IDL.Record({ submission_id: IDL.Text });
	const AppSweepExpiredDeletionsResult = IDL.Record({ swept: IDL.Float64 });
	const AppTrackEventsArgs = IDL.Record({
		events: IDL.Vec(
			IDL.Record({
				ok: IDL.Opt(IDL.Bool),
				battle_id: IDL.Opt(IDL.Text),
				country: IDL.Opt(IDL.Text),
				league_id: IDL.Opt(IDL.Text),
				session_id: IDL.Text,
				value: IDL.Opt(IDL.Float64),
				source: IDL.Opt(IDL.Text),
				occurred_at_ms: IDL.Opt(IDL.Float64),
				market_id: IDL.Opt(IDL.Text),
				series_id: IDL.Opt(IDL.Text),
				name: IDL.Variant({
					delete_confirmed: IDL.Null,
					privacy_sharing_toggled: IDL.Null,
					school_picked: IDL.Null,
					battle_viewed: IDL.Null,
					transactions_viewed: IDL.Null,
					resolution_disputed: IDL.Null,
					streak_milestone: IDL.Null,
					school_verify_email_submitted: IDL.Null,
					market_shared: IDL.Null,
					flow_completed: IDL.Null,
					flow_card_expanded: IDL.Null,
					affiliation_removed: IDL.Null,
					league_invite_sent: IDL.Null,
					pwa_install_prompted: IDL.Null,
					notification_opened: IDL.Null,
					position_taken: IDL.Null,
					flow_abandoned: IDL.Null,
					market_category_filter: IDL.Null,
					watchlist_removed: IDL.Null,
					delete_succeeded: IDL.Null,
					friend_feed_reaction: IDL.Null,
					referral_link_copied: IDL.Null,
					market_translation_toggled: IDL.Null,
					comment_posted: IDL.Null,
					flow_swipe: IDL.Null,
					referral_converted: IDL.Null,
					pwa_install_dismissed: IDL.Null,
					transactions_filtered: IDL.Null,
					school_verify_code_submitted: IDL.Null,
					signed_in: IDL.Null,
					signed_up: IDL.Null,
					order_placed: IDL.Null,
					order_cancelled: IDL.Null,
					onboarding_started: IDL.Null,
					payout_settled: IDL.Null,
					battle_proposed: IDL.Null,
					perf_metric: IDL.Null,
					provider_linked: IDL.Null,
					friend_digest_opened: IDL.Null,
					leaderboard_viewed: IDL.Null,
					friend_request_sent: IDL.Null,
					battle_accepted: IDL.Null,
					battle_declined: IDL.Null,
					vxp_awarded: IDL.Null,
					league_joined: IDL.Null,
					exit_signal: IDL.Null,
					referral_sent: IDL.Null,
					resolution_proposed: IDL.Null,
					app_error: IDL.Null,
					resolution_confirmed: IDL.Null,
					flow_session_started: IDL.Null,
					school_picker_opened: IDL.Null,
					onboarding_completed: IDL.Null,
					watchlist_added: IDL.Null,
					position_closed: IDL.Null,
					handle_checked: IDL.Null,
					battle_resolved: IDL.Null,
					market_searched: IDL.Null,
					sound_toggled: IDL.Null,
					league_created: IDL.Null,
					onboarding_step: IDL.Null,
					market_viewed: IDL.Null,
					battle_expired: IDL.Null,
					delete_flow_opened: IDL.Null,
					affiliation_set: IDL.Null,
					session_started: IDL.Null,
					referral_redeemed: IDL.Null,
					prediction_created: IDL.Null,
					faucet_claimed: IDL.Null,
					pwa_install_accepted: IDL.Null,
					chat_sent: IDL.Null,
					orderbook_viewed: IDL.Null,
					signed_out: IDL.Null
				}),
				path: IDL.Opt(IDL.Text),
				count: IDL.Opt(IDL.Float64),
				step: IDL.Opt(IDL.Float64),
				locale: IDL.Opt(IDL.Text),
				label: IDL.Opt(IDL.Text),
				duration_ms: IDL.Opt(IDL.Float64)
			})
		)
	});
	const AppTrackEventsResult = IDL.Record({ accepted: IDL.Float64 });
	const AppTransferLeagueOwnershipArgs = IDL.Record({
		new_owner_principal: IDL.Text,
		league_id: IDL.Text
	});
	const AppTransferLeagueOwnershipResult = IDL.Record({
		ok: IDL.Bool,
		reason: IDL.Opt(
			IDL.Variant({
				league_not_found: IDL.Null,
				new_owner_is_caller: IDL.Null,
				new_owner_not_member: IDL.Null,
				not_owner: IDL.Null,
				invalid_input: IDL.Null
			})
		)
	});
	const AppTriggerTournamentDrawArgs = IDL.Record({
		month_anchor: IDL.Text
	});
	const AppTriggerTournamentDrawResult = IDL.Record({
		ok: IDL.Bool,
		available_leagues: IDL.Opt(IDL.Float64),
		tournament_id: IDL.Opt(IDL.Text),
		reason: IDL.Opt(
			IDL.Variant({
				insufficient_leagues: IDL.Null,
				already_drawn: IDL.Null,
				invalid_input: IDL.Null,
				month_not_started: IDL.Null
			})
		)
	});
	const AppUpsertMarketMetadataArgs = IDL.Record({
		data: IDL.Record({
			suggested: IDL.Bool,
			tags: IDL.Vec(IDL.Text),
			events: IDL.Vec(
				IDL.Record({
					day: IDL.Float64,
					dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
					label: IDL.Text
				})
			),
			why_now: IDL.Opt(
				IDL.Record({
					kind: IDL.Variant({
						new: IDL.Null,
						social: IDL.Null,
						trending: IDL.Null,
						closing: IDL.Null,
						topical: IDL.Null
					}),
					text: IDL.Text
				})
			),
			subtitle: IDL.Opt(IDL.Text)
		}),
		series_id: IDL.Text
	});
	const AppUpsertMarketMetadataResult = IDL.Record({
		metadata: IDL.Record({
			updated_at: IDL.Float64,
			updated_by: IDL.Text,
			suggested: IDL.Bool,
			series_id: IDL.Text,
			tags: IDL.Vec(IDL.Text),
			events: IDL.Vec(
				IDL.Record({
					day: IDL.Float64,
					dir: IDL.Variant({ up: IDL.Null, down: IDL.Null }),
					label: IDL.Text
				})
			),
			why_now: IDL.Opt(
				IDL.Record({
					kind: IDL.Variant({
						new: IDL.Null,
						social: IDL.Null,
						trending: IDL.Null,
						closing: IDL.Null,
						topical: IDL.Null
					}),
					text: IDL.Text
				})
			),
			subtitle: IDL.Opt(IDL.Text)
		})
	});
	const AppUpsertMarketTranslationArgs = IDL.Record({
		data: IDL.Record({
			title: IDL.Text,
			description: IDL.Text,
			resolution: IDL.Text,
			outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
		}),
		series_id: IDL.Text,
		locale: IDL.Text
	});
	const AppUpsertMarketTranslationResult = IDL.Record({
		translation: IDL.Record({
			title: IDL.Text,
			updated_at: IDL.Float64,
			updated_by: IDL.Text,
			series_id: IDL.Text,
			locale: IDL.Text,
			description: IDL.Text,
			resolution: IDL.Text,
			outcomes: IDL.Vec(IDL.Record({ id: IDL.Text, title: IDL.Text }))
		})
	});
	const AppVerifySchoolCodeArgs = IDL.Record({
		code: IDL.Text,
		submission_id: IDL.Text
	});
	const AppVerifySchoolCodeResult = IDL.Record({
		ok: IDL.Bool,
		status: IDL.Opt(IDL.Variant({ pending: IDL.Null, public: IDL.Null })),
		school_id: IDL.Opt(IDL.Text),
		message: IDL.Opt(IDL.Text)
	});

	return IDL.Service({
		app_accept_friend_request: IDL.Func([AppAcceptFriendRequestArgs], [], []),
		app_backfill_streak_underpayments: IDL.Func(
			[AppBackfillStreakUnderpaymentsArgs],
			[AppBackfillStreakUnderpaymentsResult],
			[]
		),
		app_cancel_friend_request: IDL.Func([AppCancelFriendRequestArgs], [], []),
		app_check_friendship: IDL.Func([AppCheckFriendshipArgs], [AppCheckFriendshipResult], ['query']),
		app_check_nickname_availability: IDL.Func(
			[AppCheckNicknameAvailabilityArgs],
			[AppCheckNicknameAvailabilityResult],
			['query']
		),
		app_claim_calibration_reward: IDL.Func(
			[AppClaimCalibrationRewardArgs],
			[AppClaimCalibrationRewardResult],
			[]
		),
		app_claim_referral_friendship: IDL.Func([AppClaimReferralFriendshipArgs], [], []),
		app_claim_tournament_prize: IDL.Func(
			[AppClaimTournamentPrizeArgs],
			[AppClaimTournamentPrizeResult],
			[]
		),
		app_claim_worlds_podium_prize: IDL.Func(
			[AppClaimWorldsPodiumPrizeArgs],
			[AppClaimWorldsPodiumPrizeResult],
			[]
		),
		app_delete_analytics_events: IDL.Func(
			[AppDeleteAnalyticsEventsArgs],
			[AppDeleteAnalyticsEventsResult],
			[]
		),
		app_delete_my_account: IDL.Func([AppDeleteMyAccountArgs], [AppDeleteMyAccountResult], []),
		app_follow_user: IDL.Func([AppFollowUserArgs], [], []),
		app_get_affiliation_stats: IDL.Func(
			[AppGetAffiliationStatsArgs],
			[AppGetAffiliationStatsResult],
			['query']
		),
		app_get_analytics_events: IDL.Func(
			[AppGetAnalyticsEventsArgs],
			[AppGetAnalyticsEventsResult],
			['query']
		),
		app_get_analytics_profile_created: IDL.Func(
			[AppGetAnalyticsProfileCreatedArgs],
			[AppGetAnalyticsProfileCreatedResult],
			['query']
		),
		app_get_analytics_summary: IDL.Func(
			[AppGetAnalyticsSummaryArgs],
			[AppGetAnalyticsSummaryResult],
			['query']
		),
		app_get_analytics_user_stats: IDL.Func([], [AppGetAnalyticsUserStatsResult], ['query']),
		app_get_current_tournament: IDL.Func([], [AppGetCurrentTournamentResult], ['query']),
		app_get_market_metadata: IDL.Func(
			[AppGetMarketMetadataArgs],
			[AppGetMarketMetadataResult],
			['query']
		),
		app_get_market_tags: IDL.Func([], [AppGetMarketTagsResult], ['query']),
		app_get_market_translation: IDL.Func(
			[AppGetMarketTranslationArgs],
			[AppGetMarketTranslationResult],
			['query']
		),
		app_get_monthly_leaderboard: IDL.Func(
			[AppGetMonthlyLeaderboardArgs],
			[AppGetMonthlyLeaderboardResult],
			['query']
		),
		app_get_my_battle_stats: IDL.Func([], [AppGetMyBattleStatsResult], ['query']),
		app_get_my_referral_code: IDL.Func([], [AppGetMyReferralCodeResult], ['query']),
		app_get_my_rival: IDL.Func([], [AppGetMyRivalResult], ['query']),
		app_get_profile: IDL.Func([AppGetProfileArgs], [AppGetProfileResult], ['query']),
		app_get_user_rank_and_count: IDL.Func(
			[AppGetUserRankAndCountArgs],
			[AppGetUserRankAndCountResult],
			['query']
		),
		app_hibernate_my_account: IDL.Func([], [AppHibernateMyAccountResult], []),
		app_list_affiliation_championships: IDL.Func(
			[AppListAffiliationChampionshipsArgs],
			[AppListAffiliationChampionshipsResult],
			['query']
		),
		app_list_affiliation_stats: IDL.Func(
			[AppListAffiliationStatsArgs],
			[AppListAffiliationStatsResult],
			['query']
		),
		app_list_challengeable_leagues: IDL.Func([], [AppListChallengeableLeaguesResult], ['query']),
		app_list_followers: IDL.Func([], [AppListFollowersResult], ['query']),
		app_list_following: IDL.Func([], [AppListFollowingResult], ['query']),
		app_list_friend_recommended_leagues: IDL.Func(
			[],
			[AppListFriendRecommendedLeaguesResult],
			['query']
		),
		app_list_friend_requests: IDL.Func([], [AppListFriendRequestsResult], ['query']),
		app_list_friend_resolved_results: IDL.Func(
			[AppListFriendResolvedResultsArgs],
			[AppListFriendResolvedResultsResult],
			['query']
		),
		app_list_friends: IDL.Func([], [AppListFriendsResult], ['query']),
		app_list_leaderboard: IDL.Func([], [AppListLeaderboardResult], ['query']),
		app_list_league_battles: IDL.Func(
			[AppListLeagueBattlesArgs],
			[AppListLeagueBattlesResult],
			['query']
		),
		app_list_league_members: IDL.Func(
			[AppListLeagueMembersArgs],
			[AppListLeagueMembersResult],
			['query']
		),
		app_list_market_translations: IDL.Func(
			[AppListMarketTranslationsArgs],
			[AppListMarketTranslationsResult],
			['query']
		),
		app_list_market_translations_for_locales: IDL.Func(
			[AppListMarketTranslationsForLocalesArgs],
			[AppListMarketTranslationsForLocalesResult],
			['query']
		),
		app_list_my_affiliations: IDL.Func([], [AppListMyAffiliationsResult], ['query']),
		app_list_my_battles: IDL.Func([], [AppListMyBattlesResult], ['query']),
		app_list_my_blocking_leagues: IDL.Func([], [AppListMyBlockingLeaguesResult], ['query']),
		app_list_my_leagues: IDL.Func([], [AppListMyLeaguesResult], ['query']),
		app_list_my_referrals: IDL.Func([], [AppListMyReferralsResult], ['query']),
		app_list_sent_friend_requests: IDL.Func([], [AppListSentFriendRequestsResult], ['query']),
		app_list_worlds_member_counts: IDL.Func(
			[AppListWorldsMemberCountsArgs],
			[AppListWorldsMemberCountsResult],
			['query']
		),
		app_list_worlds_roster: IDL.Func(
			[AppListWorldsRosterArgs],
			[AppListWorldsRosterResult],
			['query']
		),
		app_lookup_league_by_invite: IDL.Func(
			[AppLookupLeagueByInviteArgs],
			[AppLookupLeagueByInviteResult],
			['query']
		),
		app_lookup_referral_code: IDL.Func(
			[AppLookupReferralCodeArgs],
			[AppLookupReferralCodeResult],
			['query']
		),
		app_prune_resolved_results: IDL.Func([], [AppPruneResolvedResultsResult], []),
		app_read_battle_live_score: IDL.Func(
			[AppReadBattleLiveScoreArgs],
			[AppReadBattleLiveScoreResult],
			[]
		),
		app_rebuild_market_tag_index: IDL.Func([], [AppRebuildMarketTagIndexResult], []),
		app_recompute_activity_reaction_counts: IDL.Func(
			[],
			[AppRecomputeActivityReactionCountsResult],
			[]
		),
		app_record_flow_swipe: IDL.Func([AppRecordFlowSwipeArgs], [AppRecordFlowSwipeResult], []),
		app_recover_my_account: IDL.Func([], [AppRecoverMyAccountResult], []),
		app_redeem_referral_code: IDL.Func([AppRedeemReferralCodeArgs], [], []),
		app_reject_friend_request: IDL.Func([AppRejectFriendRequestArgs], [], []),
		app_resolve_battle: IDL.Func([AppResolveBattleArgs], [AppResolveBattleResult], []),
		app_resolve_tournament_round: IDL.Func(
			[AppResolveTournamentRoundArgs],
			[AppResolveTournamentRoundResult],
			[]
		),
		app_resume_my_account: IDL.Func([], [AppResumeMyAccountResult], []),
		app_search_profiles: IDL.Func([AppSearchProfilesArgs], [AppSearchProfilesResult], ['query']),
		app_send_friend_request: IDL.Func([AppSendFriendRequestArgs], [AppSendFriendRequestResult], []),
		app_settle_founder_awards: IDL.Func([], [AppSettleFounderAwardsResult], []),
		app_settle_referral: IDL.Func([AppSettleReferralArgs], [], []),
		app_submit_school: IDL.Func([AppSubmitSchoolArgs], [AppSubmitSchoolResult], []),
		app_sweep_expired_deletions: IDL.Func([], [AppSweepExpiredDeletionsResult], []),
		app_track_events: IDL.Func([AppTrackEventsArgs], [AppTrackEventsResult], []),
		app_transfer_league_ownership: IDL.Func(
			[AppTransferLeagueOwnershipArgs],
			[AppTransferLeagueOwnershipResult],
			[]
		),
		app_trigger_tournament_draw: IDL.Func(
			[AppTriggerTournamentDrawArgs],
			[AppTriggerTournamentDrawResult],
			[]
		),
		app_upsert_market_metadata: IDL.Func(
			[AppUpsertMarketMetadataArgs],
			[AppUpsertMarketMetadataResult],
			[]
		),
		app_upsert_market_translation: IDL.Func(
			[AppUpsertMarketTranslationArgs],
			[AppUpsertMarketTranslationResult],
			[]
		),
		app_verify_school_code: IDL.Func([AppVerifySchoolCodeArgs], [AppVerifySchoolCodeResult], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
