import { functions } from '$declarations/satellite/satellite.api';
import { Collection } from '$lib/constants/collections.constants';
import { safeGetIdentityOnce } from '$lib/services/identity.services';
import type { BoutDoc } from '$lib/types/bout';
import {
	LEAGUE_DESCRIPTION_MAX_LENGTH,
	LEAGUE_INVITE_CODE_REGEX,
	LEAGUE_NAME_MAX_LENGTH,
	LEAGUE_NAME_MIN_LENGTH,
	type LeagueDoc
} from '$lib/types/league';
import {
	leagueMemberKey,
	type LeagueMemberDoc,
	type LeagueMemberRole
} from '$lib/types/league-member';
import { deleteDoc, getDoc, setDoc } from '@junobuild/core';

/**
 * Thin service layer wrapping the satellite's social-cohort
 * endpoints. UI screens import the camelCase domain types from
 * here so they never have to touch the snake_case wire schemas
 * generated by `juno functions build`.
 *
 * Writes go through `@junobuild/core`'s `setDoc` / `deleteDoc`;
 * reads go through the typed `functions.*` client. Both paths are
 * gated server-side by the asserts shipped in
 * through BE-5.
 */

/** League hydrated with the caller's membership role. */
export interface LeagueWithRole {
	league: LeagueDoc;
	role: LeagueMemberRole;
	joinedAtMs: number;
}

// ─── Reads ───────────────────────────────────────────────────────────────

/**
 * List every league the caller is a member of, paired with their
 * role. Sorted newest-join first per the satellite query.
 */
export const listMyLeagues = async (): Promise<LeagueWithRole[]> => {
	const { items } = await functions.listMyLeagues();

	return items.map(({ league, role, joined_at_ms }) => ({
		league: {
			id: league.id,
			name: league.name,
			description: league.description,
			inviteCode: league.invite_code,
			owner: league.owner,
			createdAtMs: league.created_at_ms,
			accentColor: league.accent_color
		},
		role,
		joinedAtMs: joined_at_ms
	}));
};

/**
 * Resolve a 6-char invite code to its league, or `undefined` if no
 * league carries that code. Callers should treat the undefined
 * branch as "invalid code" UX, not an error.
 */
export const lookupLeagueByInvite = async ({
	inviteCode
}: {
	inviteCode: string;
}): Promise<LeagueDoc | undefined> => {
	const { league } = await functions.lookupLeagueByInvite({ inviteCode });

	if (!league) {
		return;
	}

	return {
		id: league.id,
		name: league.name,
		description: league.description,
		inviteCode: league.invite_code,
		owner: league.owner,
		createdAtMs: league.created_at_ms,
		accentColor: league.accent_color
	};
};

// ─── Writes ──────────────────────────────────────────────────────────────

/**
 * Validate a league name + description per the same rules the
 * satellite assert enforces. Surfaced so the FE form can show
 * inline errors before submitting.
 */
export const validateLeagueDraft = ({
	name,
	description
}: {
	name: string;
	description?: string;
}):
	| { ok: true }
	| { ok: false; reason: 'name_too_short' | 'name_too_long' | 'description_too_long' } => {
	if (name.length < LEAGUE_NAME_MIN_LENGTH) {
		return { ok: false, reason: 'name_too_short' };
	}

	if (name.length > LEAGUE_NAME_MAX_LENGTH) {
		return { ok: false, reason: 'name_too_long' };
	}

	if (description !== undefined && description.length > LEAGUE_DESCRIPTION_MAX_LENGTH) {
		return { ok: false, reason: 'description_too_long' };
	}

	return { ok: true };
};

/**
 * Derive a stable, URL-friendly league id from a display name.
 * Lowercase, ASCII alphanumerics + hyphen, collapsed and trimmed.
 * Callers may pass a creation timestamp so the slug is unique even
 * when two users pick the same name.
 */
export const deriveLeagueId = ({
	name,
	suffix
}: {
	name: string;
	suffix: number | string;
}): string => {
	const slug = name
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '')
		.slice(0, 24);

	return `${slug || 'league'}-${suffix}`;
};

/**
 * Generate a fresh 6-char `[A-Z0-9]` invite code via the platform
 * crypto. Matches `LEAGUE_INVITE_CODE_REGEX` from `$lib/types/league`
 * so the satellite assert accepts it on first write.
 */
export const generateInviteCode = (): string => {
	const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
	const buf = new Uint8Array(6);
	crypto.getRandomValues(buf);

	let code = '';

	for (const byte of buf) {
		code += alphabet[byte % alphabet.length];
	}

	return code;
};

/**
 * Create a new league + write the owner-membership row. The
 * satellite assert enforces caller-binds-owner on both writes, so
 * the FE just signs and submits.
 *
 * Returns the created `LeagueDoc` so the caller can route to the
 * detail page or update their local list optimistically.
 */
export const createLeague = async ({
	name,
	description
}: {
	name: string;
	description?: string;
}): Promise<LeagueDoc> => {
	const validation = validateLeagueDraft({ name, description });

	if (!validation.ok) {
		throw new Error(`Invalid league draft: ${validation.reason}`);
	}

	const identity = await safeGetIdentityOnce();
	const ownerPrincipal = identity.getPrincipal().toText();
	const createdAtMs = Date.now();
	const leagueId = deriveLeagueId({ name, suffix: createdAtMs });
	const inviteCode = generateInviteCode();

	if (!LEAGUE_INVITE_CODE_REGEX.test(inviteCode)) {
		// `generateInviteCode` is built to satisfy the regex; this
		// branch is here so a future change to either side trips the
		// FE error path instead of failing on the satellite assert.
		throw new Error('Generated invite code is malformed.');
	}

	const league: LeagueDoc = {
		id: leagueId,
		name,
		description,
		inviteCode,
		owner: ownerPrincipal,
		createdAtMs
	};

	await setDoc<LeagueDoc>({
		collection: Collection.LEAGUES,
		doc: {
			key: leagueId,
			data: league
		}
	});

	const ownerMembership: LeagueMemberDoc = {
		leagueId,
		member: ownerPrincipal,
		joinedAtMs: createdAtMs,
		role: 'owner'
	};

	await setDoc<LeagueMemberDoc>({
		collection: Collection.LEAGUE_MEMBERS,
		doc: {
			key: leagueMemberKey({ leagueId, memberPrincipal: ownerPrincipal }),
			data: ownerMembership
		}
	});

	return league;
};

/**
 * Join a league via its 6-char invite code. Looks the league up,
 * then writes a `LeagueMemberDoc` for the caller. Returns the
 * resolved league so the caller can route into it.
 *
 * Throws if the code is malformed, unknown, or the caller is
 * already a member (the satellite assert rejects the second-write
 * branch).
 */
export const joinLeagueByInvite = async ({
	inviteCode
}: {
	inviteCode: string;
}): Promise<LeagueDoc> => {
	if (!LEAGUE_INVITE_CODE_REGEX.test(inviteCode)) {
		throw new Error('Invite code is malformed.');
	}

	const league = await lookupLeagueByInvite({ inviteCode });

	if (!league) {
		throw new Error('No league found for that invite code.');
	}

	const identity = await safeGetIdentityOnce();
	const memberPrincipal = identity.getPrincipal().toText();
	const joinedAtMs = Date.now();
	const key = leagueMemberKey({ leagueId: league.id, memberPrincipal });

	// If the caller is already a member, the assert would reject the
	// write with "identity fields immutable" on a stale joinedAtMs.
	// Pre-empt with a getDoc to surface a clearer error.
	const existing = await getDoc<LeagueMemberDoc>({
		collection: Collection.LEAGUE_MEMBERS,
		key
	});

	if (existing) {
		throw new Error('Already a member of this league.');
	}

	const membership: LeagueMemberDoc = {
		leagueId: league.id,
		member: memberPrincipal,
		joinedAtMs,
		role: 'member'
	};

	await setDoc<LeagueMemberDoc>({
		collection: Collection.LEAGUE_MEMBERS,
		doc: {
			key,
			data: membership
		}
	});

	return league;
};

/**
 * Leave a league — deletes the caller's membership row. The
 * satellite assert rejects this for the owner principal, so
 * ownership transfer is a precondition. Callers should disable the
 * "Leave" CTA on owner rows.
 */
export const leaveLeague = async ({ leagueId }: { leagueId: string }): Promise<void> => {
	const identity = await safeGetIdentityOnce();
	const memberPrincipal = identity.getPrincipal().toText();
	const key = leagueMemberKey({ leagueId, memberPrincipal });

	const existing = await getDoc<LeagueMemberDoc>({
		collection: Collection.LEAGUE_MEMBERS,
		key
	});

	if (!existing) {
		// Idempotent — no row to delete is success. Avoids racing
		// against an admin kick.
		return;
	}

	await deleteDoc<LeagueMemberDoc>({
		collection: Collection.LEAGUE_MEMBERS,
		doc: existing
	});
};

/**
 * Transfer league ownership to another member. The current owner
 * calls this; the satellite swaps `LEAGUES.owner` and the matching
 * `LEAGUE_MEMBERS` role rows (old owner → admin, new owner → owner).
 *
 * The call surfaces structured refusal reasons so the FE can render
 * a meaningful error: `not_owner`, `league_not_found`,
 * `new_owner_not_member`, `new_owner_is_caller`, `invalid_input`.
 * On success returns `{ ok: true }`.
 */
export interface TransferLeagueOwnershipResult {
	ok: boolean;
	reason?:
		| 'not_owner'
		| 'league_not_found'
		| 'new_owner_not_member'
		| 'new_owner_is_caller'
		| 'invalid_input';
}

export const transferLeagueOwnership = ({
	leagueId,
	newOwnerPrincipal
}: {
	leagueId: string;
	newOwnerPrincipal: string;
}): Promise<TransferLeagueOwnershipResult> =>
	functions.transferLeagueOwnership({ leagueId, newOwnerPrincipal });

// ─── Bouts ───────────────────────────────────────────────────────────────

const projectBoutWire = (b: {
	id: string;
	kind: BoutDoc['kind'];
	side_a: string;
	side_b: string;
	proposer: string;
	state: BoutDoc['state'];
	kickoff_ms: number;
	settle_ms: number;
	score_a?: number;
	score_b?: number;
	winner?: BoutDoc['winner'];
}): BoutDoc => ({
	id: b.id,
	kind: b.kind,
	sideA: b.side_a,
	sideB: b.side_b,
	proposer: b.proposer,
	state: b.state,
	kickoffMs: b.kickoff_ms,
	settleMs: b.settle_ms,
	scoreA: b.score_a,
	scoreB: b.score_b,
	winner: b.winner
});

/**
 * List every bout involving the given league — both sides scanned.
 * Projects the satellite's snake_case wire schema to camelCase
 * `BoutDoc` for the FE.
 */
export const listLeagueBouts = async ({ leagueId }: { leagueId: string }): Promise<BoutDoc[]> => {
	const { items } = await functions.listLeagueBouts({ leagueId });

	return items.map(projectBoutWire);
};

/**
 * List every bout across every league the caller belongs to. Powers
 * the `/arena/bouts` cross-league inbox. Sorted server-side by
 * `kickoffMs` ascending.
 */
export const listMyBouts = async (): Promise<BoutDoc[]> => {
	const { items } = await functions.listMyBouts();

	return items.map(projectBoutWire);
};

/**
 * Propose a new bout (kind='league'). Caller must own the `sideA`
 * league; the satellite assert hard-rejects otherwise. The opponent
 * (sideB) league doesn't need to exist on the satellite for the
 * proposal to land — accept goes through a separate assert pass
 * under the opponent owner's caller identity.
 */
export const proposeBout = async ({
	sideA,
	sideB,
	kickoffMs,
	settleMs
}: {
	sideA: string;
	sideB: string;
	kickoffMs: number;
	settleMs: number;
}): Promise<BoutDoc> => {
	if (kickoffMs >= settleMs) {
		throw new Error('Kickoff must be strictly before settle.');
	}

	const identity = await safeGetIdentityOnce();
	const proposerPrincipal = identity.getPrincipal().toText();
	const boutId = `${sideA}--vs--${sideB}-${Date.now().toString(36)}`;

	const bout: BoutDoc = {
		id: boutId,
		kind: 'league',
		sideA,
		sideB,
		proposer: proposerPrincipal,
		state: 'proposed',
		kickoffMs,
		settleMs
	};

	await setDoc<BoutDoc>({
		collection: Collection.BOUTS,
		doc: { key: boutId, data: bout }
	});

	return bout;
};

/**
 * Bout state transitions — thin write helpers. The satellite assert
 * (BE-6) enforces the forward-only state machine + per-transition
 * authorisation; the FE just packages the doc + signs the call.
 *
 * All three reads the existing doc first so we round-trip the
 * server's `updated_at` token, which `setDoc` needs for the
 * conflict-free update path.
 */
export const acceptBout = async ({ bout }: { bout: BoutDoc }): Promise<BoutDoc> => {
	const next: BoutDoc = { ...bout, state: 'accepted' };
	await writeBoutTransition({ bout, next });

	return next;
};

export const kickoffBout = async ({ bout }: { bout: BoutDoc }): Promise<BoutDoc> => {
	const next: BoutDoc = { ...bout, state: 'in_flight' };
	await writeBoutTransition({ bout, next });

	return next;
};

/**
 * Retract a `proposed`-state bout. Only the original proposer can
 * call this; the satellite assert hard-rejects anyone else and any
 * bout past `proposed`.
 */
export const retractBout = async ({ bout }: { bout: BoutDoc }): Promise<void> => {
	if (bout.state !== 'proposed') {
		throw new Error('Only proposed bouts can be retracted.');
	}

	const existing = await getDoc<BoutDoc>({
		collection: Collection.BOUTS,
		key: bout.id
	});

	if (!existing) {
		throw new Error('Bout no longer exists.');
	}

	await deleteDoc<BoutDoc>({
		collection: Collection.BOUTS,
		doc: {
			key: bout.id,
			data: existing.data,
			updated_at: existing.updated_at
		}
	});
};

export const resolveBout = async ({
	bout,
	scoreA,
	scoreB
}: {
	bout: BoutDoc;
	scoreA: number;
	scoreB: number;
}): Promise<BoutDoc> => {
	const winner = scoreA > scoreB ? 'A' : scoreA < scoreB ? 'B' : 'draw';
	const next: BoutDoc = { ...bout, state: 'resolved', scoreA, scoreB, winner };
	await writeBoutTransition({ bout, next });

	return next;
};

const writeBoutTransition = async ({
	bout,
	next
}: {
	bout: BoutDoc;
	next: BoutDoc;
}): Promise<void> => {
	const existing = await getDoc<BoutDoc>({
		collection: Collection.BOUTS,
		key: bout.id
	});

	if (!existing) {
		throw new Error('Bout no longer exists.');
	}

	await setDoc<BoutDoc>({
		collection: Collection.BOUTS,
		doc: {
			key: bout.id,
			data: next,
			updated_at: existing.updated_at
		}
	});
};
